### ISSUE TITLE
Is there a possibility to support earlier version of Django (specifically 1.7) ?

### ISSUE THREAD

**Issue by gilgenbergg** [axnsan12/drf-yasg#101]
drf-yasg works great on 1.11 Django but I need to generate scheme of project`s API which was developed using 1.7 version. Is it possible to get support for this version?

**Comment by axnsan12** [comment]
No. Django 1.7 [has been end of life for more than 3 years](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/), and the lowest version of Django still supported by its developers is Django 1.11. I'm not willing to weigh down the codebase with support code for ancient versions of Django.

That said, I have no idea if it's going to work, theoretically there is no hard dependency on Django itself, you can try and see. However there is a hard dependency on DRF >=3.7.7.
