### ISSUE TITLE
Support for postgres ArrayField

### ISSUE THREAD

**Issue by dly0n** [axnsan12/drf-yasg#102]
Django >= 1.8 supports the _ArrayField_ of django.contrib.postgres.fields. I'm using it as an array of strings that's serliazed with drf as _MultipleChoiceField_.

#models.py
`array_field = ArrayField(models.CharField(choices=TYPES, max_length=3))`

#serlializers.py
`array_field = serializers.MultipleChoiceField(choices=TYPES)`

When generating the swagger doc, I hit the following error:
    Exception Type: AttributeError at /swagger/
    **Exception Value: 'NoneType' object has no attribute 'get'**

The issue is that _get_basic_type_info_ returns None [here](https://github.com/axnsan12/drf-yasg/blob/fb240f6a5b304fe14a059c9c7afb70124eb85319/src/drf_yasg/inspectors/field.py#L413).

Adding _ArrayField_ to _model_field_to_basic_type_ works for me but I haven't thoroughly tested it. 
```
from django.contrib.postgres.fields import ArrayField
...
model_field_to_basic_type = [
    (models.AutoField, (openapi.TYPE_INTEGER, None)),
    (models.BinaryField, (openapi.TYPE_STRING, openapi.FORMAT_BINARY)),
    (models.BooleanField, (openapi.TYPE_BOOLEAN, None)),
    (models.NullBooleanField, (openapi.TYPE_BOOLEAN, None)),
    (models.DateTimeField, (openapi.TYPE_STRING, openapi.FORMAT_DATETIME)),
    (models.DateField, (openapi.TYPE_STRING, openapi.FORMAT_DATE)),
    (models.DecimalField, (decimal_field_type, openapi.FORMAT_DECIMAL)),
    (models.DurationField, (openapi.TYPE_INTEGER, None)),
    (models.FloatField, (openapi.TYPE_NUMBER, None)),
    (models.IntegerField, (openapi.TYPE_INTEGER, None)),
    (models.IPAddressField, (openapi.TYPE_STRING, openapi.FORMAT_IPV4)),
    (models.GenericIPAddressField, (openapi.TYPE_STRING, openapi.FORMAT_IPV6)),
    (models.SlugField, (openapi.TYPE_STRING, openapi.FORMAT_SLUG)),
    (models.TextField, (openapi.TYPE_STRING, None)),
    (models.TimeField, (openapi.TYPE_STRING, None)),
    (models.UUIDField, (openapi.TYPE_STRING, openapi.FORMAT_UUID)),
    (models.CharField, (openapi.TYPE_STRING, None)),
    (ArrayField, (openapi.TYPE_STRING, openapi.TYPE_ARRAY)),
]
```

The generated ymal looks like this:
```
      array_field:
        type: array
        items:
          type: string
          enum:
            - TYPE1
```

Do you see any issue adding this support for Django >= 1.8? 

Thanks for the project, it has been really useful.

**Comment by axnsan12** [comment]
Actually, thinking again, adding ``ArrayField`` to ``model_field_to_basic_type`` doesn't really make sense. Just fixing the crash should be enough, the rest is handled by the code for interpreting ``MultipleChoiceField``s.

I'll look into it when I get the chance.

**Comment by dly0n** [comment]
Agreed. My focus was more narrowly on the issue I am facing because I was less sure about the scope of the change for a more generic solution.
