### ISSUE TITLE
No 'read_only_fields' in response

### ISSUE THREAD

**Issue by lzakharov** [axnsan12/drf-yasg#107]
I have serializer:

```
class TransactionSerializer(serializers.ModelSerializer):
    class Meta:
        model = Transaction
        fields = ('uuid', 'source', 'destination', 'amount', 'is_approved')
        read_only_fields = ('uuid', 'is_approved')
```

So fields marked as `read_only` not displayed in request parameters (it's ok) but also in response schema.

**Comment by axnsan12** [comment]
I can't seem to reproduce this. Can you provide more details, maybe a small project showing the issue?

**Comment by axnsan12** [comment]
Possibly fixed by https://github.com/axnsan12/drf-yasg/commit/aa90723703e238ea4a0c9fa07ddf760b197455d6?
