### ISSUE TITLE
Can't install with Django 2.0 using pipenv

### ISSUE THREAD

**Issue by knyghty** [axnsan12/drf-yasg#113]
It seems like pipenv doesn't parse the version comments very well, it spits them out like this.

```
drf-yasg==1.7.0           requires coreapi>=2.3.3, coreapi>=2.3.3, coreschema>=0.0.4, coreschema>=0.0.4, Django<2.0,>=1.11.7; python_version <= "2.7", Django>=1.11.7; python_version >= "3.4", Django>=1.11.7; python_version >= "3.4"; python_version >= "3.4", djangorestframework>=3.7.7, djangorestframework>=3.7.7, future>=0.16.0, future>=0.16.0, inflection>=0.3.1, inflection>=0.3.1, openapi-codec>=1.3.2, openapi-codec>=1.3.2, ruamel.yaml>=0.15.34, ruamel.yaml>=0.15.34, six>=1.10.0, six>=1.10.0, uritemplate>=3.0.0, uritemplate>=3.0.0
```

I thought pipenv just wasn't respecting it at first, but I'm not sure. It does seem to check the python versions, but somehow ends up with the wrong dependencies, so I'm not sure if something can be done on this side or if I need to report to pipenv.

**Comment by axnsan12** [comment]
It works with ``pip``, doesn't work with ``pipenv`` => looks like a pipenv issue to me :smile:

If it's not some issue on your end I would report it to the ``pipenv`` folks.

What exactly is the problem you're hitting, and what do you mean by "ends up with the wrong dependencies"?

**Comment by knyghty** [comment]
Sorry, was in a bit of a rush when I reported this. Here's a minimal failing Pipfile

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "*"
drf-yasg = "*"

[dev-packages]

[requires]
python_version = "3.6"
```

Should install django 2.0, but instead installs 1.11, I'm not sure if it's because pipenv is parsing drf-yasg's dependencies improperly or or if there's something that could fix it on this end.

**Comment by axnsan12** [comment]
> or if there's something that could fix it on this end.

``Django = ">=2.0"`` would certainly fix it on your end :stuck_out_tongue: 

But pipenv is definitely at fault for not resolving that automatically from the ``drf-yasg`` requirements.

**Comment by knyghty** [comment]
I think you're right, but isn't it kind of unnecessary?

Surely you can just put `Django >=1.11.7` in your requirements, as Django 2.0 has its own `python_required` specified: https://github.com/django/django/blob/master/setup.py

So if you try to install this package with py2.7, it should correctly install Django 1.11

**Comment by axnsan12** [comment]
Indeed you are right, the requirement here is redundant, so I removed it.
