### ISSUE TITLE
Make .yaml optional

### ISSUE THREAD

**Issue by daniel878** [axnsan12/drf-yasg#115]
It could be great to make .json as the default format and .yaml as an optional one.
Dependencies for yaml would be installed in a similar way as validation:
> pip install drf-yasg[yaml]

**Comment by axnsan12** [comment]
In the openapi ecosystem YAML is the preferred and recommended format, mostly for its increased readability, so it makes sense for it to be a first-class citizen.

There is also the issue that introducing this would be a breaking change - people would have to manually adjust their dependencies to switch to the ``[yaml]`` variant.

I don't really see the benefit of this, is it just to remove the single ``ruamel.yaml`` dependency?

**Comment by daniel878** [comment]
Yep, probably not so much benefit.
Thanks for the library and the quick response.
