### ISSUE TITLE
Inspector class priority order

### ISSUE THREAD

**Issue by pratikjarande** [axnsan12/drf-yasg#121]
I'm trying to disable schema generation by default across all endpoints and enable it only on select few. The priority order in func `get_operation` of class `OpenAPISchemaGenerator` seems to achieve what I want. However, this does not work as expected when you've set `None` on `DEFAULT_AUTO_SCHEMA_CLASS` and `swagger_schema` but with a valid value for `auto_schema`.

```
# settings.py
SWAGGER_SETTINGS = {
    'DEFAULT_AUTO_SCHEMA_CLASS': None
}

# views.py
class ArticleViewSet(viewsets.ModelViewSet):
    swagger_schema = None

    @swagger_auto_schema(auto_schema=SwaggerAutoSchema)
    def create(self, request, *args, **kwargs):
        return super(...) 
```

The code never reaches [to the point where it evaluates the priority](https://github.com/axnsan12/drf-yasg/blob/23ebe2ff3eec19f0d7782462abf58ddcd49f7017/src/drf_yasg/generators.py#L361)  of inspector class for that endpoint because early on in the code that [endpoint is discarded](https://github.com/axnsan12/drf-yasg/blob/23ebe2ff3eec19f0d7782462abf58ddcd49f7017/src/drf_yasg/generators.py#L49)  because you set `None` on class-wide attr `swagger_schema`

**Comment by axnsan12** [comment]
Hello @pratikjarande !

Your observation is correct, and in a black box I'd say it's an inconsistency that should be fixed.
However, sadly it's been [documented behaviour](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html?highlight=swagger_schema#excluding-endpoints) for quite a while, so I don't think the ``swagger_schema = None`` will be removed any time soon.

Your options in the meantime are:

* exclude specific methods of the class using``@swagger_auto_schema(auto_schema=None)`` 
* use a no-op ``SwaggerAutoSchema`` at the class level:

```python
class NoopAutoSchema(SwaggerAutoSchema):
    def get_operation(self, *args, **kwargs):
        return None
```

**Comment by pratikjarande** [comment]
Hello @axnsan12,

Thanks for your help!

The first option is not convenient as I have a bunch of such methods.
The second option runs into following error

```
Traceback (most recent call last):
  File "../lib/python2.7/site-packages/drf_yasg/views.py", line 85, in get
    schema = generator.get_schema(request, self.public)
  File "../lib/python2.7/site-packages/drf_yasg/generators.py", line 204, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/Users/pratik/.venv/medusa2/lib/python2.7/site-packages/drf_yasg/generators.py", line 318, in get_paths
    operations[method.lower()] = self.get_operation(view, path, prefix, method, components, request)
  File "../lib/python2.7/site-packages/drf_yasg/generators.py", line 359, in get_operation
    if 'consumes' in operation and set(operation.consumes) == set(self.consumes):
TypeError: argument of type 'NoneType' is not iterable
```

I have a workaround where I'm disabling the check for swagger_schema [here](https://github.com/axnsan12/drf-yasg/blob/23ebe2ff3eec19f0d7782462abf58ddcd49f7017/src/drf_yasg/generators.py#L49-L50) and it seems to works fine. What's your opinion on this ?

**Comment by axnsan12** [comment]
> The second option runs into following error

https://github.com/axnsan12/drf-yasg/commit/a4a11ad1ab0a594da7b5844126924466638db496 should fix that... pushing in a release soon

> I have a workaround where I'm disabling the check for swagger_schema here and it seems to works fine. What's your opinion on this ?

If you edited it directly, I don't think it's worth maintaining a fork for that. If you just subclassed ``EndpointEnumerator`` it's probably fine.

**Comment by pratikjarande** [comment]
Yeah, I did just that! Thanks again.
