### ISSUE TITLE
Error when using ListField(DictField(read_only=True))

### ISSUE THREAD

**Issue by Cediddi** [axnsan12/drf-yasg#127]
The error is at _dump_dict method of OpenAPICodecJson. I use a serializer which needs a list of dictionaries. yasg doesn't support this and throws an meaningless message. I found my issue under `spec['definitions']['...']['properties']['...']['readOnly']`

```
class ExampleSerializer(serializers.Serializer):
        myfield = serializers.ListField(serializers.DictField(read_only=True))
```

Django==1.11.13
djangorestframework==3.8.2

**Comment by axnsan12** [comment]
> and throws an meaningless message

Which meaningless message, exactly?

**Comment by Cediddi** [comment]
```
  File "/.../.venv/lib/python3.6/site-packages/drf_yasg/codecs.py", line 73, in encode
    raise SwaggerValidationError("spec validation failed", errors, spec, self)
drf_yasg.errors.SwaggerValidationError: spec validation failed
[19/May/2018 18:19:11] "GET /yasg/?format=openapi HTTP/1.1" 500 104113
```

I have set `validators=[]` in my schema_view

**Comment by Cediddi** [comment]
I've tried generate_swagger management command. Now it's producing a better output.
```
TypeError: Object of type 'DictField' is not JSON serializable
```

BTW I forgot to tell you my django and drf versions. I'm updating my first comment.

**Comment by axnsan12** [comment]
http://www.django-rest-framework.org/api-guide/fields/#listfield

You are using ``ListField`` wrong. The child type must be passed into the ``child=`` kwarg.

The error arises because the first positional argument of ``ListField`` is actually ``read_only``, so you end up inserting a ``DictField`` instance instead of a boolean into the ``read_only`` field.

**Comment by Cediddi** [comment]
Oh, wow. Thank you. I guess this is unclear in documentation because child is not marked as kwarg only in neither docs or source code and my program was working without a problem. Thank you for fixing my code :) It works beautifully now.
