### ISSUE TITLE
How to get rid of common prefixes and version in urlpatterns in swagger ui?

### ISSUE THREAD

**Issue by tehdoorsareopen** [axnsan12/drf-yasg#128]
Hello!

I've developed an API with urlpatterns like:
```
urlpatterns = [
  #----- v1 -----#
  path('api/v1/examples/', include('examples.urls', namespace='v1')),
  path('api/v1/moreexamples/', include('moreexamples.urls', namespace='v1')),
  #----- v2 -----#
  path('api/v1/examples/', include('examples.urls', namespace='v2')),
  path('api/v1/moreexamples/', include('moreexamples.urls', namespace='v2')),
]
```

But i can't figure out how can I get rid of /api/{version}/ in swagger ui schema. And how can I switch the ui depending on API <version>?

I've found in Documentation this one:

> When using API versioning with NamespaceVersioning or URLPathVersioning, versioned endpoints that do not match the version used to access the SchemaView will be excluded from the endpoint list - for example, /api/v1.0/endpoint will be shown when viewing /api/v1.0/swagger/, while /api/v2.0/endpoint will not

> the longest common path prefix of all the urls in your API - see determine_path_prefix()

But it couldn't help me. Maybe it's possible to clarify how could I deal with the situation? Any examples any?

Thank you

**Comment by axnsan12** [comment]
If ALL the urls included in your API start with /api/, the prefix should automatically be elided into the ``basePath``.

For versioning, if ``NamespaceVersioning`` is properly configured in your project, and you serve your schema from the ``v1`` and/or ``v2`` namespace, the view in each namespace should only "see" its respective endpoints.

Both behaviours are documented, and if they're not working for you, you'll have to provide and example project showing the issue.

**Comment by tehdoorsareopen** [comment]
Maybe I miss smth, so ill provide the examples:

0. 
djangorestframework==3.8.2
drf-yasg==1.7.4

1. http://i.prntscr.com/x-dWOgd2S3e1dLdQd6WScA.png - UI
2. Settings.py

```
# Django REST rramework
REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100
}

# DRF - YASG
SWAGGER_SETTINGS = {
    'LOGIN_URL': '/',
}
```

3. urls

```
from django.conf import settings

from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from jira_templates import views as jira_templates_views

#---------- Swagger Section ----------#
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
  openapi.Info(
    title="Jira Templates API",
    default_version='v1',
    description='',
  ),
  public=True,
  permission_classes=(permissions.IsAuthenticated,),
)

swagger_urlpatterns = [
  path('api/v1/swagger/', schema_view.with_ui('swagger', cache_timeout=None), name='schema-swagger-ui'),
  #path('api/v2/swagger/', schema_view.with_ui('swagger', cache_timeout=None), name='schema-swagger-ui'),
]
#---------- Swagger Section ----------#

#---------- Django REST ----------#
rest_urlpatterns = [
  path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
  path('api/', jira_templates_views.api_root),
]

rest_versioning_urlpatterns = [
  #----- v1 -----#
  path('api/v1/templates/', include('jira_templates.urls', namespace='v1')),
  #----- v2 -----#
  path('api/v2/templates/', include('jira_templates.urls', namespace='v2')),
]
#---------- Django REST ----------#

urlpatterns = [
  path('', admin.site.urls),
  path('jet/', include('jet.urls', namespace='jet')),
  path('bookmarklet/', jira_templates_views.bookmarklet),
]

urlpatterns += swagger_urlpatterns
urlpatterns += rest_urlpatterns
urlpatterns += rest_versioning_urlpatterns
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()
```

4. jira_templates.urls

```
from django.urls import path

from . import views

app_name = 'jira_templates'
urlpatterns = [
  path('', views.TemplateList.as_view(), name='template-list'),
]
```

I really can't understand what I'm doing wrong. Sorry ):

**Comment by axnsan12** [comment]
```
  path('api/v1/swagger/', schema_view.with_ui('swagger', cache_timeout=None), name='schema-swagger-ui'),
  #path('api/v2/swagger/', schema_view.with_ui('swagger', cache_timeout=None), name='schema-swagger-ui'),
```

Here you are not adding the swagger views into a namespace, so they cannot possibly be versioned.

```
  path('api/', jira_templates_views.api_root),
```

Here you are adding the root ``api/`` endpoint to your views. This might be a ``drf-yasg`` bug preventing the ellision of the ``/api/`` prefix into ``/``. Does the prefix elimination work if you remove this endpoint?

**Comment by axnsan12** [comment]
```
 path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
```

And also here you are adding ``api-auth/`` to the root urlconf, so ``/api/`` is not the common prefix of all endpoints in your project. Therefore there is no way it would be eliminated.

**Comment by tehdoorsareopen** [comment]
Hello there! Thank you for the answers!

I've just removed   `path('api/', jira_templates_views.api_root),` from urlpatterns and it works for me.
Also I've rewrote swagger_urlpatterns:

```
swagger_urlpatterns = [
  path('api/v1/swagger/', include('jira_templates.urlstwo', namespace='v1')),
  path('api/v2/swagger/', include('jira_templates.urlstwo', namespace='v2')),
]
```

And it works great. And there is no API root path (which I actually don't want to see in Swagger).

Thank you for your helpful answers once again! And for the project, it's great and very useful, keep going! (:

**Comment by bulkerke** [comment]
@tehdoorsareopen I'm struggling with the same issue. Can you help me please? What is the` jira_templates.urlstwo` in this part:

```
swagger_urlpatterns = [
  path('api/v1/swagger/', include('jira_templates.urlstwo', namespace='v1')),
  path('api/v2/swagger/', include('jira_templates.urlstwo', namespace='v2')),
]
```
