### ISSUE TITLE
Provide example in Serializer Meta

### ISSUE THREAD

**Issue by daniel878** [axnsan12/drf-yasg#132]
In order to be able to provide examples of object definitions, allow a syntax like:

```
class MySerializer(serializers.Serializer):
    month = serializers.CharField()

     class Meta:
           example = {
              'month': "03"
           }
````
That map to something like: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-example

could be great.

**Comment by axnsan12** [comment]
Seems like a good idea. Should probably be namespaced in a dict or prefixed with something like ``swagger_`` or ``drf_yasg_``, but in principle it makes sense.
