### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by intellisense** [axnsan12/drf-yasg#135]
I have followed all basic steps for installations and when I go to `http://0.0.0.0:8081/api/swagger/` I am getting `400 Bad Request` don't know what to do here.

- Added `drf_yasg` in `INSTALLED_APPS`
- Created an app named as `apidocs` and added that `myproject.apps.apidocs` in `INSTALLED_APPS`
    **views.py**
    ```python
    from drf_yasg.views import get_schema_view
    from drf_yasg import openapi
    from rest_framework import permissions


    SchemaView = get_schema_view(
        openapi.Info(
            title="Snippets API",
            default_version='v1',
            description="Test description",
            terms_of_service="https://www.google.com/policies/terms/",
            contact=openapi.Contact(email="contact@snippets.local"),
            license=openapi.License(name="BSD License"),
        ),
        validators=['flex', 'ssv'],
        public=True,
        permission_classes=(permissions.AllowAny,),
    )
    ```

    **urls.py**
    ```python
    from django.conf.urls import url

    from . import views

    urlpatterns = [
        url(r'^swagger(?P<format>\.json|\.yaml)$', views.SchemaView.without_ui(cache_timeout=0), name='schema-json'),
        url(r'^swagger/$', views.SchemaView.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    ]
    ```
- Added `apidocs` app urls in main urls:
    ```python
    url('^api/', include('myproject.apps.apidocs.urls', namespace='apidocs')),
    ```

Using:
- Django==1.11.10
- djangorestframework==3.7.7
- drf-yasg==1.8.0
- flex==6.13.2

**Comment by axnsan12** [comment]
You're going to have to provide a more complete code example (i.e. archive of whole project). I don't see anything wrong with the code you've shown.

**Comment by intellisense** [comment]
That's exactly what has happened, an exception was swallowed. My view set was returning a dynamic serializer based on field type in data and in `get_serializer_class` we run a validator on `data` to validate field type is ok if not it raises an `APIException`:
```python
    def get_serializer_class(self):
        if self.request:
            validator = serializers.MyValidator(data=self.request.data)
            validator.is_valid(raise_exception=True)
            return get_field_type_serializer_class(validator.data['field_type'])

        return super(MyViewSet, self).get_serializer_class()
```

During schema generation DRF calls [view.get_serializer()](https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/inspectors.py#L318) which will call `get_serializer_class` and that will raise an `APIException` and it will be caught [here](https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/inspectors.py#L319). But Your package does not log anything and simply raises a 500 internal server error.

I have forked the project and reproduce this issue, please check this [branch](https://github.com/intellisense/drf-yasg/tree/issue-135) and then run the test project and visit `http://localhost:8000/swagger/` you will see 500 internal server error and no information regarding the error in console.

**Comment by intellisense** [comment]
@axnsan12 Thanks for looking into this, I have read the documentation and understood that I have to provide fixed serializer so that `get_serializer` is not called, I have following serializer:

```python
class FieldCreateUpdateViewSet(mixins.CreateModelMixin, mixins.UpdateModelMixin, viewsets.GenericViewSet):
    """
    A viewset that provides `create` and `update` actions for field.
    """

    queryset = Field.objects.all()
    serializer_class = BaseFieldSerializer

    @swagger_auto_schema(
        operation_description='Creates a field.',
        request_body=BaseFieldSerializer,
        responses={
            status.HTTP_201_CREATED: openapi.Response(
                'Field created successfully.',
                BaseFieldSerializer
            )
        }
    )
    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)
    
    @swagger_auto_schema(
        operation_description='Updates a field.',
        request_body=BaseFieldSerializer,
        responses={
            status.HTTP_200_OK: openapi.Response(
                'Field updated successfully.',
                BaseFieldSerializer
            )
        }
    )
    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def get_serializer_class(self):
        # There is no request when generating documentation
        if self.request:
            validator = CreateUpdateFieldValidator(data=self.request.data)
            validator.is_valid(raise_exception=True)
            field_type = validator.data['type']
        else:
            field_type = FIELD_TYPE_STRING
        return get_field_serializer(field_type)
```

But `get_serializer_class` is still being called, can you point out what I am doing wrong here? Thanks!

**Comment by intellisense** [comment]
For now I have solved the issue like this:

```
    def get_serializer_class(self):
        field_type = FIELD_TYPE_STRING

        # There is no request when generating documentation
        if self.request:
            # A request might come from swagger schema generation in that case we don't have request data
            if 'swagger' not in self.request.META['PATH_INFO']:
                validator = CreateUpdateFieldValidator(data=self.request.data)
                validator.is_valid(raise_exception=True)
                field_type = validator.data['type']

        return get_field_serializer(field_type)
```

**Comment by axnsan12** [comment]
That's strange, the call to ``get_serializer`` should indeed be skipped when you provide ``request_body`` and ``responses``...

It's only called from [``get_request_serializer`` when there is no ``request_body`` override](https://github.com/axnsan12/drf-yasg/blob/2ef7cfbfe369a55e8b68e574bf20fe32d40cac38/src/drf_yasg/inspectors/view.py#L100-L112), or from [``get_default_responses`` when there is no 2xx ``responses`` override](https://github.com/axnsan12/drf-yasg/blob/2ef7cfbfe369a55e8b68e574bf20fe32d40cac38/src/drf_yasg/inspectors/view.py#L209-L214).


I don't see why it would be called for your view.
