### ISSUE TITLE
Custom SerializerInspector is not called

### ISSUE THREAD

**Issue by intellisense** [axnsan12/drf-yasg#136]
I am using a `Serializer` for request body initially, but I also want to add couple of more parameter into it, hence I wrote custom serializer inspector:

```python
from drf_yasg.inspectors import SerializerInspector

class BaseFieldSerializerInspector(SerializerInspector):

    def get_request_parameters(self, serializer, in_):
        parameters = super().get_request_parameters(serializer, in_)
        # add extra parameters here
        return parameters
```

And used it like so:

```python
@swagger_auto_schema(
    operation_description='Updates a field.',
    manual_parameters=[FIELD_ID_PATH_PARAMETER],
    request_body=BaseFieldSerializer,
    responses={
        status.HTTP_200_OK: openapi.Response(
            'Field updated successfully.',
            BaseFieldSerializer
        )
    },
    field_inspectors=[BaseFieldSerializerInspector]
)
```

But `BaseFieldSerializerInspector` is never called. Kindly help on this please. Thanks!

**Comment by axnsan12** [comment]
``get_request_parameters`` is only called when the serializer is converted to form parameters (i.e. formdata request body). 

For convesion to schema object you have to override one of ``get_schema`` or ``add_manual_fields`` , or, alternatively, ``process_result``.

You also have the option of overriding ``field_to_swagger_object`` to catch both ``Parameter`` and ``Schema`` generation (this method is also called interally from ``get_schema`` and ``get_request_parameters``)

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject

**Comment by intellisense** [comment]
Thanks for the response, some code example would be really helpful here. `BaseFieldSerializer` (as the name suggest its a base serializer for other field types) I would like to add some other fields manually in `request_body` which are not part of `BaseFieldSerializer`. e.g. I would like to add `options` field in request body with description saying `Required if field_type is "enum"`

**Comment by intellisense** [comment]
Got it working:

```python
class BaseFieldSerializerInspector(SerializerInspector):

    def process_result(self, result, method_name, obj, **kwargs):

        if isinstance(result, openapi.Schema.OR_REF):
            # traverse any references and alter the Schema object in place
            schema = openapi.resolve_ref(result, self.components)

            if schema.type == openapi.TYPE_OBJECT:
                schema.properties['test'] = openapi.Schema(
                    title='Test',
                    description='The test.',
                    type=openapi.TYPE_STRING,
            )

            # no ``return schema`` here, because it would mean we always generate
            # an inline `object` instead of a definition reference

        # return back the same object that we got - i.e. a reference if we got a reference
        return result
```

Thanks!

**Comment by intellisense** [comment]
How to identify in `process_result ` that `openapi.TYPE_OBJECT` is of `request_body` or `responses`?

**Comment by intellisense** [comment]
@axnsan12 Thanks for the clarification, one last help I need from you I would like to add `options` property which would be an array of objects, using the above approach in `process_result`:

```
schema.properties['test'] = openapi.Schema(
    title='Test',
    description='The test.',
    type=openapi.TYPE_ARRAY,
    items=openapi.Items(
        type=openapi.TYPE_OBJECT,
    )
)
```

There is already a serializer for options `OptionsSerializer`, is it possible to somehow use that serializer here for items? if not how can I further customize `openapi.items` to also include information regarding object type?:

```
items=openapi.Items(
    type=openapi.TYPE_OBJECT,  # I want to define properties for object here
)
```

Thanks for all the help.

**Comment by axnsan12** [comment]
You can use ``probe_field_inspectors``:

```python
options_schema = self.probe_field_inspectors(OptionsSerializer(many=True), openapi.Schema, True)
```

**Comment by intellisense** [comment]
Awesome! That worked. Thanks!
