### ISSUE TITLE
label of serializer used as query_serializer of @swagger_auto_schema doesn't show on generated schema

### ISSUE THREAD

**Issue by mpwang** [axnsan12/drf-yasg#138]
I try to use query_serializer in `@swagger_auto_schema` to document my get method. The structure of QuerySerializer is show up on generated schema page , but with no label.

```python
from drf_yasg.utils import swagger_auto_schema
from rest_framework import serializers
from rest_framework.views import APIView


class QuerySerializer(serializers.Serializer):
    name_in_query = serializers.CharField(required=True, label="name of query serializer")


class ResponseSerializer(serializers.Serializer):
    name_in_response = serializers.CharField(label='name of response serializer')


class TestView(APIView):
    @swagger_auto_schema(
        query_serializer=QuerySerializer,  # no label show up
        responses={200: ResponseSerializer}
    )
    def get(self, request):
        pass
```

But i change to use `manual_parameters=[test_param]` of `@swagger_auto_schema`, the description show up correctly on the generated schema page.
```python
test_param = openapi.Parameter('test', openapi.IN_QUERY, description="test manual param", type=openapi.TYPE_STRING)

class TestView(APIView):
    @swagger_auto_schema(
        manual_parameters=[test_param],  # label show up
        responses={200: ResponseSerializer}
    )
    def get(self, request):
        pass
```

It will be nice to support label of serializer used as query_serializer of `@swagger_auto_schema`, instead of writing lots of `openapi.Parameter`

**Comment by axnsan12** [comment]
> name_in_query = serializers.CharField(required=True, **label=**"name of query serializer")
> test_param = openapi.Parameter('test', openapi.IN_QUERY, **description=**"test manual param", type=openapi.TYPE_STRING)

Label and description are not the same thing. Use the ``help_text`` attribute to set the ``description`` from a serializer. ``label`` sets the ``title`` field (which does not exist on ``Parameter``, only on ``Schema``)).

**Comment by mpwang** [comment]
Thanks, it works. I now understand difference of `label` and `help_text`.
