### ISSUE TITLE
Is there a way to get a constant/static value for a field?

### ISSUE THREAD

**Issue by beaugunderson** [axnsan12/drf-yasg#144]
Here's my use case:

I'd like to define a field on a Django model like `result_type = 'staff'`, expose it in a DRF serializer by including it in `fields = (..., 'result_type')`, and have the static value 'staff' exposed in the schema.

I want this because we use the schema to generate flowtypes for our project, and we sometimes need to do type refinements between models, and a static value would help tremendously here.

**Comment by axnsan12** [comment]
Seems to be an open issue: https://github.com/OAI/OpenAPI-Specification/issues/1313. So not currently possible, and most likely never will be possible in OpenAPI 2.

Best you could do would probably be adding a ``default`` to your serializer field:

```python
result_type = serializers.ModelField(model_field='result_type', default=ModelClass.result_type, help_text='Always "' + ModelClass.result_type + '"')
```
