### ISSUE TITLE
Add a way to specify common API path prefix

### ISSUE THREAD

**Issue by phihag** [axnsan12/drf-yasg#146]
Currently, [the documentation states](https://github.com/axnsan12/drf-yasg/blob/master/docs/openapi.rst#user-content-custom-spec-base-url) that in order to set an API prefix, one should set the [Django option `FORCE_SCRIPT_NAME`](https://docs.djangoproject.com/en/2.0/ref/settings/#force-script-name). But `FORCE_SCRIPT_NAME` has huge implications on the rest of the project and is thus not an option for larger projects. It is also a classic case of [using a global setting to fix a local problem](https://blogs.msdn.microsoft.com/oldnewthing/20081211-00/?p=19873), which should be avoided at all costs.

There should be a way to set a prefix just for one swaggerized API, and not for the whole project.

For reference, I have a project whose URL structure is like this:
```
# service/myservice/urls/api.py
urlpatterns = [
    # ...
    url(r'^v2/', include(api2.urlpatterns)),
]

# service/myservice/urls/api2.py
urlpatterns = [
    url(r'^auth/login$', api2.login, name='api2_auth_login'),
    url(r'^user$', api2.user, name='api2_user'),
    url(r'^doc(?P<format>\.json|\.yaml)$', api2.schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^doc/$', api2.schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]
```
We are using [django-hosts](https://github.com/jazzband/django-hosts) to support multiple hostnames, but the `service.myservice.urls.api` is the root url configuration for the current endpoint.

Thus, a typical URL would be `https://api.prod.example.net/v2/auth/login`. In swagger, I want to show the base URL as `https://api.prod.example.net/v2/` and the route as `/auth/login`. How do I do that with drf_yasg?

**Comment by axnsan12** [comment]
> Thus, a typical URL would be https://api.prod.example.net/v2/auth/login. In swagger, I want to show the base URL as https://api.prod.example.net/v2/ and the route as /auth/login. How do I do that with drf_yasg?

I don't understand. Doesn't that happen by default?

**Comment by phihag** [comment]
I forgot one more piece of the problem: I'm passing in
```
urlconf='service.myservice.urls.api2',
```
to `get_schema_view`. Hence, [when the path is determined](https://github.com/axnsan12/drf-yasg/blob/2ef7cfbfe369a55e8b68e574bf20fe32d40cac38/src/drf_yasg/generators.py#L87), it's just the local component after `/v2/`, e.g. just `'/auth/login'`.

But that means just modifying my urlconf so that the total route is defined in `service.myservice.urls.api2`

```
# service/myservice/urls/api.py
urlpatterns = [
    # ...
] + api2.url_patterns

# service/myservice/urls/api2.py
api2_urlpatterns = [
    url(r'^auth/login$', api2.login, name='api2_auth_login'),
    url(r'^user$', api2.user, name='api2_user'),
    url(r'^doc(?P<format>\.json|\.yaml)$', api2.schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^doc/$', api2.schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]
urlpatterns = [url(r'^v2/', include(api2_urlpatterns)]
```
solves the problem for me.

Although I think that having the ability to add a prefix - preferably simply by adding a path to the base URL - is a good idea in general, and would be necessary in a more complicated setup than mine, this is a valid workaround I can employ, and I am thus clothing this issue.

Thanks for your help!

**Comment by axnsan12** [comment]
> Although I think that having the ability to add a prefix - preferably simply by adding a path to the base URL - is a good idea in general, and would be necessary in a more complicated setup than mine

The full request path in Django is always determined by ``SCRIPT_NAME`` (external path prefix outside of Django's control, e.g. reverse proxies) plus the full Django route. This was the reasoning behind giving no such "force" mechanism in ``drf-yasg``, since there is already a "force" mechanism in Django for external paths (FORCE_SCRIPT_NAME), and full internal routes are always available to be passed into the schema view at an appropriate location.

I might reconsider this if someone provides an example of such a setup where passing full urlpatterns is not possible or desirable, but for now I would consider the implicit mechanisms sufficient.

**Comment by alissonmuller** [comment]
Alternatively, you can override [get_schema](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_schema) in a [custom generator](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#openapischemagenerator), and set the `basePath` attribute:
```python
from drf_yasg.generators import OpenAPISchemaGenerator

class CustomOpenAPISchemaGenerator(OpenAPISchemaGenerator):
    def get_schema(self, *args, **kwargs):
        schema = super().get_schema(*args, **kwargs)
        schema.basePath = '/v2' # API prefix
        return schema

schema_view = get_schema_view(
    ... other arguments ...
    generator_class=CustomOpenAPISchemaGenerator,
)
```

**Comment by kushalsht** [comment]
Thanks

**Comment by NICK-DUAN** [comment]
> Alternatively, you can override [get_schema](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_schema) in a [custom generator](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#openapischemagenerator), and set the `basePath` attribute:
> 
> ```python
> from drf_yasg.generators import OpenAPISchemaGenerator
> 
> class CustomOpenAPISchemaGenerator(OpenAPISchemaGenerator):
>     def get_schema(self, *args, **kwargs):
>         schema = super().get_schema(*args, **kwargs)
>         schema.basePath = '/v2' # API prefix
>         return schema
> 
> schema_view = get_schema_view(
>     ... other arguments ...
>     generator_class=CustomOpenAPISchemaGenerator,
> )
> ```

I did as this, testproj urls.py like this:
```python
import user_agents
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path, re_path
from rest_framework import permissions
from rest_framework.decorators import api_view

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

swagger_info = openapi.Info(
    title="Snippets API",
    default_version='v1',
    description="""This is a demo project for the [drf-yasg](https://github.com/axnsan12/drf-yasg) Django Rest Framework library.

The `swagger-ui` view can be found [here](/cached/swagger).
The `ReDoc` view can be found [here](/cached/redoc).
The swagger YAML document can be found [here](/cached/swagger.yaml).

You can log in using the pre-existing `admin` user with password `passwordadmin`.""",  # noqa
    terms_of_service="https://www.google.com/policies/terms/",
    contact=openapi.Contact(email="contact@snippets.local"),
    license=openapi.License(name="BSD License"),
)

schema_view = get_schema_view(
    validators=['ssv', 'flex'],
    public=True,
    permission_classes=[permissions.AllowAny],
)

from drf_yasg.generators import OpenAPISchemaGenerator

class CustomOpenAPISchemaGenerator(OpenAPISchemaGenerator):
    def get_schema(self, *args, **kwargs):
        schema = super().get_schema(*args, **kwargs)
        schema.basePath = '/v2' # API prefix
        return schema

schema_view = get_schema_view(
    urlconf='people.urls',
    generator_class=CustomOpenAPISchemaGenerator,
)


@api_view(['GET'])
def plain_view(request):
    pass


def root_redirect(request):
    user_agent_string = request.META.get('HTTP_USER_AGENT', '')
    user_agent = user_agents.parse(user_agent_string)

    if user_agent.is_mobile:
        schema_view = 'cschema-redoc'
    else:
        schema_view = 'cschema-swagger-ui'

    return redirect(schema_view, permanent=True)


# urlpatterns required for settings values
required_urlpatterns = [
    path('admin/', admin.site.urls),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

urlpatterns = [
    re_path(r'^swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=0),
            name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('redoc-old/', schema_view.with_ui('redoc-old', cache_timeout=0), name='schema-redoc-old'),

    re_path(r'^cached/swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=None),
            name='cschema-json'),
    path('cached/swagger/', schema_view.with_ui('swagger', cache_timeout=None), name='cschema-swagger-ui'),
    path('cached/redoc/', schema_view.with_ui('redoc', cache_timeout=None), name='cschema-redoc'),

    path('', root_redirect),

    path('snippets/', include('snippets.urls')),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
    path('todo/', include('todo.urls')),
    path('people/', include('people.urls')),
    path('plain/', plain_view),
] + required_urlpatterns
```

But when I type http://127.0.0.1:80 in my Browser's address bar, it return a 403
![image](https://user-images.githubusercontent.com/22417013/120155522-7e16cf00-c223-11eb-82e1-6d94065588a8.png)

**Comment by nseetim** [comment]
Great Job you guys are doing on this I must confess,

Assuming i have a url `api.example.com/users/login`, and the prefix _/login_ is just one of many in the _users_ app

In the root url.py file we have something like:

```
urlpatterns = [
    path('admin/', admin.site.urls),

    # urls for the user on-boarding and user related functions
    path('users/', include('users.api.urls')),
    path('podcasts/', include('podcast.api.urls')),
    path('audiostream/', include('audiostreaming.api.urls')),]
```
so each app URL is routed to it in the fashion above, when using the URL parameter in the _get_schema_view_ it doesn't display the full path with the prefix as I supply, it trims off the path component, and using the FORCE_SCRIPT_NAME solution won't work here as it would affect the whole project and changing the URL structure would cause a lot of breaking changes, so I was wondering if it would be possible to add a means of stating what URL the documentation would use based on the app just as its supplied to it

if there's a way you would recommend that won't cause breaking changes I would be very much open to it

**Comment by nseetim** [comment]
@mohitbestpeers I dont know if you have figured out how to do this yet but adapting from the answer given by @alissonmuller what I did was to create a helper function somewhere, in my case i have a utilities file,
```python
#utilities.py
from drf_yasg.generators import OpenAPISchemaGenerator

def my_custom_openapi_schema_generator(path_prefix:str):
    if not isinstance(path_prefix, str):
        raise TypeError('The supplied path_prefix must be of type str')
    class CustomOpenAPISchemaGenerator(OpenAPISchemaGenerator):
        def get_schema(self, *args, **kwargs):
            schema = super().get_schema(*args, **kwargs)
            schema.basePath = path_prefix # API prefix
            return schema
    return CustomOpenAPISchemaGenerator
```

Then you can use this as I have done in any of your urls and specify the path_prefix you want for the urls in that file or so

```python
#urls.py
from utilities import my_custom_openapi_schema_generator

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

custom_generator_class = my_custom_openapi_schema_generator(path_prefix='/user')

schema_view = get_schema_view(
   openapi.Info(
      title="Users API",
      default_version='v1',
      description='This is the official documentation for all userAPIs',
   ),
   generator_class=custom_generator_class,
   url= f'{API_BASE_URL}',
   urlconf='users.api.urls',
)

```
