### ISSUE TITLE
How to document an action that just redirects?

### ISSUE THREAD

**Issue by leiserfg** [axnsan12/drf-yasg#148]
It's a question, more than an issue :D 
There is a way of avoid the automatic addition of a 200 response to a 'get'  action? 'cause my endpoint never returns a 200, it just redirect when the action is done. (Yes I now it is not too *resty*, but is valid http and swagger supported)

**Comment by kujbol** [comment]
Hey @leiserfg 
Check out
https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#the-swagger-auto-schema-decorator

You can provide manual description for responses using `swagger_auto_schema` decorator.

redirection_response = openapi.Response('This endpoint is redirecting user to the: `http:example.com`')
@swagger_auto_schema(method='get', responses={302: redirection_response})

**Comment by axnsan12** [comment]
@kujbol is partially right, however that would still leave you with the auto-generated 200 response.

I think a good syntax for explicitly disabling it would be something along the lines of ``responses={200: None}``, however I believe that will crash as of now.

Will look into enabling that.
