### ISSUE TITLE
Support setting summary in swagger_auto_schema

### ISSUE THREAD

**Issue by phihag** [axnsan12/drf-yasg#149]
The Swagger `summary` property is a short form of the description of a route. There should be a way to set this property with `swagger_auto_schema`, in a similar way to `description`.

**Comment by Moulde** [comment]
I agree, showing the autogenerated operationId is fine, but for any endpoints that aren't crud it just confuses.

**Comment by axnsan12** [comment]
I should look into a way of allowing to de arbitrary ``Operation`` fields via the decorator. As a workaround you can override ``get_operation`` in a custom ``auto_schema``.
