### ISSUE TITLE
Bad ref_name and can't force it

### ISSUE THREAD

**Issue by Amoki** [axnsan12/drf-yasg#151]
My `User` object is named as `Creator` in the swagger.
I tried to force it with `ref_name` in the `Meta` but it is ignored. I rename many other objects without problem.

`creator` is the nested field referencing the user is many other objects.

```python
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model =User
        fields = ('id', 'email', ...)
        ref_name = 'User'

class ProjectSerializer(serializers.ModelSerializer):
    creator = UserSerializer(read_only=True)

    class Meta:
        model = Project
        fields = ('id', 'name', 'creator',)
```

**Comment by axnsan12** [comment]
What do you mean you can't force it/is ignored?

Can you provide the desired|real schema output?

You should also realise that the name of the ``creator`` field inside the ``Project`` model ( ts ``label``/``title``) is not the same as the name of the ``User`` model.

**Comment by Amoki** [comment]
Thanks for the clues!

I looked at the json and my problem seems to be cause by the `title` field:
```json
  "definitions": {
    "User": {
      "title": "Creator",
      "type": "object",
      "properties": {
        "id": {
          "title": "ID",
          "type": "integer",
          "readOnly": true
        },
        "email": {
          "title": "Email",
          "type": "string",
          "format": "email",
          "readOnly": true,
          "minLength": 1
        }
    }
}
```

My `/user` call returns a "Creator"
![screenshot from 2018-07-02 10-08-37](https://user-images.githubusercontent.com/1349751/42152290-f1cc3826-7ddf-11e8-828e-cb64e60cde6e.png)

Models section defines a "Creator" model and not a  "User" model.
![screenshot from 2018-07-02 10-09-48](https://user-images.githubusercontent.com/1349751/42152334-184dda9a-7de0-11e8-8334-c9b51a09bd9a.png)

So the `ref_name` is correct (The model is called "User" instead of my internal "ExtendedUser"), but a wild title appears. Where does it comes from ? Can I change it ?

**Comment by axnsan12** [comment]
You can probably set the ``title`` field on ``UserSerializer`` using [swagger_schema_fields](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html?highlight=swagger_schema_fields#serializer-meta-nested-class)

**Comment by Amoki** [comment]
Oh, I missed that in the doc... It fixes the problem!

Thanks!
