### ISSUE TITLE
Spec validation failed

### ISSUE THREAD

**Issue by n1b0r** [axnsan12/drf-yasg#152]
Hello,

I'm getting the `spec validation failed` error when trying to access to the redoc page.

I'm using the [django-rest-framework-bulk](https://github.com/miki725/django-rest-framework-bulk) module to be able to perform bulk actions.
Maybe this module breaks the schema validation.

I'm not familiar with openapi ecosystem.

Could someone help me figuring out what is happening ?

**Comment by axnsan12** [comment]
I can't help you without the actual error message (look into the logs or the response body of the error).

Alternatively, you can try running without ``validators`` and post the resulting schema here.

**Comment by axnsan12** [comment]
Closing this for lack of information. Feel free to reopen with more details.
