### ISSUE TITLE
No way to provide a fixed serializer for `GET` method

### ISSUE THREAD

**Issue by linevych** [axnsan12/drf-yasg#154]
I have API ViewSet that calls `get_objects_method` in `get_serializer_class`.

```python
from rest_framework import mixins
from rest_framework.viewsets import GenericViewSet


class MyViewSet(mixins.CreateModelMixin,
                mixins.RetrieveModelMixin,
                mixins.UpdateModelMixin,
                mixins.DestroyModelMixin,
                GenericViewSet):
    def get_serializer_class(self):
        obj = self.get_object()

        # custom logic here
```

It throws an excpetion:

```
AssertionError: Expected view MyViewSet to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.
```

According to [documentation](https://drf-yasg.readthedocs.io/en/stable/openapi.html#a-note-on-limitations) there are two ways to fix it:

1. Provide a fixed serializer for request and response body introspection using `@swagger_auto_schema`, to prevent `get_serializer` from being called on the view.
2. Exclude your endpoint from introspection.

But in my case first one is not possible to do because it will throw an error if I decorate `retrieve` method:

```
drf_yasg.errors.SwaggerGenerationError: request_body can only be applied to (PUT,PATCH,POST,DELETE); are you looking for query_serializer or manual_parameters?
```

Any ideas how to fix this or exclude viewset from schema generation is the only way?

## Breadcrumbs

1. `inspectors.view.SwaggerAutoSchema.get_default_responses`
2. `drf_yasg.inspectors.view.SwaggerAutoSchema.get_request_serializer`

**Comment by linevych** [comment]
This doesn't do anything, `get_serializer_class` will be called anyway.

```
class MyViewSet(mixins.CreateModelMixin,
                mixins.RetrieveModelMixin,
                mixins.UpdateModelMixin,
                mixins.DestroyModelMixin,
                GenericViewSet):
    def get_serializer_class(self):
        obj = self.get_object()

    @swagger_auto_schema(repsonses={status.HTTP_200_OK: openapi.Response(__doc__, serializer_class)})
    def retrieve(self, request, *args, **kwargs):
        return super().update(request, *args, **kwargs)
```

**Comment by axnsan12** [comment]
Hmm, ok, that might be a problem.

**Comment by linevych** [comment]
Also, there is an issue with `update()` method because even if I provide `request_body` and response to this method I still get the same exception. `create` and `destroy` methods works fine.

```
@swagger_auto_schema(request_body=serializer_class, repsonses={status.HTTP_204_NO_CONTENT: openapi.Response(__doc__, serializer_class)})
def update(self, request, *args, **kwargs):
    return super().update(request, *args, **kwargs)
```

**Comment by axnsan12** [comment]
Make sure you that also override ``partial_update``.
