### ISSUE TITLE
Make excluded "produces" media types customizable

### ISSUE THREAD

**Issue by estin** [axnsan12/drf-yasg#158]
Hello!

In `utils.py` at  https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/utils.py#L278
Excludes html media type? It is some OpenAPI restriction?

```python
def get_produces(renderer_classes):
    """Extract ``produces`` MIME types from a list of renderer classes.
    :param list renderer_classes: renderer classes
    :return: MIME types for ``produces``
    :rtype: list[str]
    """
    media_types = [renderer.media_type for renderer in renderer_classes or []]
    media_types = [encoding for encoding in media_types if 'html' not in encoding]
    return media_types
```

Sorry about my poor English.

**Comment by axnsan12** [comment]
I don't know if it's an OpenAPI restriction. I excluded ``html`` because it seemed to me that endpoints returning html are not really considered "API" and are out of the scope of swagger documentation.

**Comment by estin** [comment]
for me html response is fine for api endpoint `GET /v1/weapp/?token=`, where resulting HTML embedded to iframe/webview on a client side.

Can I make PR where introduce new settings for excluding media_types?
By default `html` would be in this settings  for backward  compatibility

**Comment by axnsan12** [comment]
Yeah, seems fair to have a way of changing that.

**Comment by estin** [comment]
Thanks a lot!
I was not have time to fix it by myself, sorry.
