### ISSUE TITLE
YAML schema fails because descriptions contains django.utils.safestring.SafeText

### ISSUE THREAD

**Issue by toabi** [axnsan12/drf-yasg#159]
We use `mark_safe` in some model fields `help_text`. It's the easiest way to have HTML-formatting in them.

`node_value = dump.represent_data(item_value)` in `drf_yasg/codecs.py:144 (in represent_odict)`.

That calls `ruamel/yaml/representer.py:represent_data` and that fails because it doesn't know how to represent `django.utils.safestring.SafeText`.

Maybe drf-yasg should convert safe-text to normal unicode before handing it over?

**Comment by axnsan12** [comment]
Yeah, this could probably be fixed.

**Comment by makarchuk** [comment]
In which layer this should be handled? I assume there's several layers on which this bug can be fixed.

**Comment by axnsan12** [comment]
I would image it's possible to add a representer for ``django.utils.safestring.SafeText`` to [SaneYamlDumper](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/codecs.py#L110) akin to the one for OrderedDict.
