### ISSUE TITLE
Redoc Route naming in search panel

### ISSUE THREAD

**Issue by jamesloewen** [axnsan12/drf-yasg#163]
I have a reasonably large API where there tends to be 3 `/` in the route quite easily. In the default view on the search, these are converted to `_` which is a frustrating default, especially when it post fixes with the action even though there is an icon already indicating the verb.

I would like to have routes be specified as
VERB my/tag/subpath/

where my/tag/subpath/ removes the prefix for the path since it is identical to the tag. Even just replacing the operationId with full route would be a sufficient minimal change.

After looking through the docs, I haven't been able to find a way to specify this.

Example currently
`POST accounts_auth_login_create`
Should become
`POST /auth/login/`
Or even
`POST /accounts/auth/login/` if above isn't possible (just much more redundancy)

**Comment by axnsan12** [comment]
You should override https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html?highlight=get_operation_id#drf_yasg.inspectors.SwaggerAutoSchema.get_operation_id.

Technically the [operation ID](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object) is supposed to be a programmatic name but you might be able to get away with using spaces and slashes.

**Comment by jamesloewen** [comment]
Thanks! Works like a charm
