### ISSUE TITLE
Serializer Meta class options do not apply to serializer Fields

### ISSUE THREAD

**Issue by bloodb4th** [axnsan12/drf-yasg#167]
Hello, i want to implement Unix Timestamp Datetime Field in DRF and serve the documentation using this library. But i have some issues with how to custom the field that serve in swagger ui.
First issue is i cant change the format, title, and description in certain fields even after i follow this library documentation in readthedocs. Here is my snippets of code:

```
class UnixTimeSerializer(serializers.DateTimeField):
    def to_representation(self, value):
        """ Return epoch time for a datetime object or ``None``"""
        from django.utils.dateformat import format
        try:
            return int(format(value, 'U'))
        except (AttributeError, TypeError):
            return None

    def to_internal_value(self, value):
        import datetime
        return datetime.datetime.fromtimestamp(int(value))

    class Meta:
         #  i follow this snippet from readthedocs to customize individual serializer 
         swagger_schema_fields = {
            'format': 'integer',
            'title': 'Client date time suu',
            'description': 'Date time in unix timestamp format',
        }

..........some code here

#  Serializer below is the one that used in the viewsets
class TransactionSerializer(serializers.ModelSerializer):
    transaction_details = TransactionDetailSerializer(many=True)
    client_date_time = UnixTimeSerializer()

.......... some code here
```

and the second issue is how can i change the example when i click try it out in swagger ui, it is still  showing the django native date time format.
Thank you for your attention.

**Comment by bloodb4th** [comment]
@axnsan12 is there a hack or something to make it work? i already dive into the source code but i cant seem to find a solution to change the field documentation.

**Comment by bubanoid** [comment]
Hello. I am trying to apply `swagger_schema_fields` Meta class option to a Serializer field. However, it isn't clear how to use this feature. I am doing the following:

    class TimestampField(serializers.Field):
    """
    Converts date/datetime objects to timestamp
    """
    def to_representation(self, value):
        return int(time.mktime(value.timetuple()))

    swagger_schema_fields = {
        "type": "integer",
    }

It doesn't work as `swagger_schema_fields` is not defined properly. How to define it for the field classes?

**Comment by axnsan12** [comment]
You didn't define it inside a ``Meta`` nested class.

**Comment by bubanoid** [comment]
Oops... Thank you!
