### ISSUE TITLE
How to fix redoc naming convention when using url arguments right after prefix, followed by model name

### ISSUE THREAD

**Issue by ggjersund** [axnsan12/drf-yasg#174]
So I'm trying to make redoc name the dropdown menus correctly, by that I mean, I want it to use the model name, in this case Customers. However, because I use an argument (<slug:company>) before the /customers/ endpoint, it acts as if /api/ is model. How can I fix this?

Example of what it looks like and what my URLs look like:
![skjermbilde 2018-08-01 kl 14 12 39](https://user-images.githubusercontent.com/26675510/43521034-29b86a9e-9595-11e8-83cb-d1bff7900d85.png)
![skjermbilde 2018-08-01 kl 14 14 15](https://user-images.githubusercontent.com/26675510/43521051-311cfdcc-9595-11e8-971e-34539e822d99.png)

**Comment by axnsan12** [comment]
The ``/api/`` prefix will be elided into ``basePath`` iff all paths start with ``/api/``. Other than that I'm not sure what you mean.

**Comment by ggjersund** [comment]
**For this code in my main urls.py file:**

```
api_urlpatterns = [
    path('<slug:company>/customers/', include('customers.urls')),
]
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    # API URLs
    path('api/', include(api_urlpatterns)),
    path('docs/', schema_view.with_ui('redoc', cache_timeout=None), name='schema-redoc'),
]
```

**and this in my customers/urls.py file:**
```
urlpatterns = [
    path('', CustomerList.as_view()),
    path('<int:number>/', CustomerDetail.as_view()),
]
```

I get the naming convention as provided in the images. Instead I want the naming to be Customers, instead of API, and customers_list instead of api_customers_list.

**Comment by ggjersund** [comment]
It seems to believe that since I use a lookup field `<slug:company>` in the url right after `/api/` that `api` is actually the model name.

**Comment by axnsan12** [comment]
Yes, that is intended behaviour. For your case you should override [determine_path_prefix](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html?highlight=determine_path_prefix#drf_yasg.generators.OpenAPISchemaGenerator.determine_path_prefix) in a custom generator class.
