### ISSUE TITLE
tox + setup.py failing with "The version specified ('0.0.0.dummy+0000016513faf897') is an invalid version"

### ISSUE THREAD

**Issue by therefromhere** [axnsan12/drf-yasg#181]
tox and setup.py are failing for me currently on master (at  16b6ed7fd64d36f8a7ac5368a00a19da1e115c17) with this error:

```
$ /usr/bin/python setup.py 
/usr/local/lib/python2.7/dist-packages/setuptools/dist.py:407: UserWarning: The version specified ('0.0.0.dummy+0000016513faf897') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```
This is with Python 2.7.12 on Ubuntu 16.04 (but same error with Python 3.6 via pyenv)

These 2 line https://github.com/axnsan12/drf-yasg/blob/master/setup.py#L33 seems to be the culprit - if I comment out it works fine.

```
    if any(any(dist in arg for dist in ['sdist', 'bdist']) for arg in sys.argv):
        raise
```

**Comment by axnsan12** [comment]
The dummy version string is generated only if you try to build the package outside of a git repository (because the release version is derived from the latest git tag via setuptools-scm).

Making the dummy version string comply to pep 440 shouldn't be too hard.

**Comment by axnsan12** [comment]
This could also be caused by not having setuptools-scm installed before trying to ``setup.py sdist``.
