### ISSUE TITLE
Failed to load api definition

### ISSUE THREAD

**Issue by bobozar** [axnsan12/drf-yasg#183]
After installation and when I visit the url example.com/swagger I got 

```
Errors
Fetch error
Internal Server Error http://example.com/swagger/?format=openapi
```

**Comment by bobozar** [comment]
```
raise SwaggerValidationError("spec validation failed", errors, spec, self)
drf_yasg.errors.SwaggerValidationError: spec validation failed
```

Like I need to import a function?

**Comment by chopanpma** [comment]
Hi @axnsan12 , did you got this solved?

**Comment by salisu14** [comment]
Failed to load API definition.
 
Fetch errorInternal Server Error http://127.0.0.1:8000/api/v1/swagger/?format=openapi

**Comment by progdad** [comment]
Have the same issue, has someone solved this ?
I'm getting this error when I'm trying to get any endpoint through navigation bar search field.

**Comment by dannycrief** [comment]
> Have the same issue, has someone solved this ? I'm getting this error when I'm trying to get any endpoint through navigation bar search field.

Have the same issue on deploying docker container

**Comment by rovsen762** [comment]
I got this error(
![image](https://github.com/axnsan12/drf-yasg/assets/63507773/d05d5294-7532-4624-8b3e-dd89e37b5f3d)
