### ISSUE TITLE
Remove Lazy Rendering Option for Redoc

### ISSUE THREAD

**Issue by sultansgillani** [axnsan12/drf-yasg#184]
Either remove the default app setting of True, https://github.com/axnsan12/drf-yasg/blob/9b56e1a4c839906d92e0568904731855bdce51a1/src/drf_yasg/app_settings.py#L70 or remove it completely.

See here: https://github.com/Rebilly/ReDoc#redoc-options-object

><del> lazyRendering - Not implemented yet if set, enables lazy rendering mode in ReDoc. This mode is useful for APIs with big number of operations (e.g. > 50). In this mode ReDoc shows initial screen ASAP and then renders the rest operations asynchronously while showing progress bar on the top. Check out the demo for the example.</del>

And here:
https://github.com/Rebilly/ReDoc/issues/475

**Comment by axnsan12** [comment]
Thanks for the heads-up, I changed the default to false for now. Will wait to see the conclusion of the issue you linked before more drastic measures (deprecation, removal, etc).
