### ISSUE TITLE
Modifying Menu Item Appearance

### ISSUE THREAD

**Issue by ozgurakcali** [axnsan12/drf-yasg#185]
I want to modify the appearances of left menu items. As far as I can see, they are generated from application urls, turning them to all uppercase letters. For instance, if I have a url entry like app-versions, on the left menu it is displayed as 

> APP-VERSIONS

I want to display it as 

> App Versions

Any way I can do that?

**Comment by ozgurakcali** [comment]
I do not want to change urls, I only want to change appearance of menu items. 

![doc](https://user-images.githubusercontent.com/961118/44036488-9092e5d0-9f1a-11e8-9bc8-cd556526cb01.png)

Here for instance, I want to display "Address Data" insted of "ADDRESS-DATA" (image shows the top left corner of redoc page)

**Comment by axnsan12** [comment]
Those are tags, I believe. Same process to override them.

As for the css, this is a pending issue: https://github.com/axnsan12/drf-yasg/issues/178; no ETA for now. You'll have to either provide your own ReDoc template or wait for that to be implemented.

**Comment by axnsan12** [comment]
I'm closing this as answered. Feel free to reopen if you still have issues.
