### ISSUE TITLE
Default value - swagger

### ISSUE THREAD

**Issue by tboulogne** [axnsan12/drf-yasg#189]
Hello,

I use a serializer to generate custom examples. Into swagger, examples default values are not shown. Get "string".

![json](https://user-images.githubusercontent.com/6205275/44256619-fdb98780-a209-11e8-9e46-c26f19cf698f.png)
Works well into xml example :
![xml](https://user-images.githubusercontent.com/6205275/44256620-fdb98780-a209-11e8-8e7f-3ed885368a43.png)

If i look into redoc, i got this for examples :
![redoc_xml](https://user-images.githubusercontent.com/6205275/44256875-bda6d480-a20a-11e8-9323-eaf2958d37bd.png)

Could you help me to make this work please ?

Thanks for all.

Regards

**Comment by axnsan12** [comment]
You probably have to set the example field of the [Schema object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object).

The UI particulars are in the court of ``swagger-ui``/``ReDoc``, not this library.
