### ISSUE TITLE
Filter is not propagated to swagger

### ISSUE THREAD

**Issue by NN---** [axnsan12/drf-yasg#192]
Schema generated by Django: http://www.django-rest-framework.org/topics/3.5-announcement/
produces correctly a REST method with filter.
Swagger created using this library doesn't do this.

Field 'abc' is appeared in both , but 'id' doesn't appear in swagger openapi.

```py
class SomeFilterWithId(django_filters.FilterSet):
    class Meta:
        model = SomeModel
        fields = ["abc","id"]
```

**Comment by axnsan12** [comment]
This will need a more complete explanation/reproduction. Generally, filters should work the same between the two generators because the related code of ``django-rest-framework`` is reused by ``drf-yasg``.

**Comment by axnsan12** [comment]
I'm closing this for lack of information. Please reopen if you have anything to add.
