### ISSUE TITLE
Parameter descriptions on ViewSets that do not have a Model

### ISSUE THREAD

**Issue by PaulWay** [axnsan12/drf-yasg#201]
In ModelViewSets, the parameter in the path for the `retrieve` view is described using the `get_pk_description` function from `rest_framework.schemas.inspectors`.  This is used in the OpenAPISchemaGenerator's `get_path_parameters` method to describe the parameter based on the model's field information.

In some cases (e.g. when integrating with a service that doesn't provide results as a Django model) it's necessary to write a ViewSet that acts like a ModelViewSet.  In this situation, the ViewSet's `retrieve` view parameter is not described, and there is no way to describe it.  Using a `ManualSchema` object in the ViewSet's `schema` property does not get picked up.

I've got this PR for a solution to this issue:

https://github.com/axnsan12/drf-yasg/pull/200

But maybe there's a better or another way?

**Comment by axnsan12** [comment]
This should be covered by [manual_parameters](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.utils.swagger_auto_schema). 

The ability to describe elements using docstrings is better encompassed by https://github.com/axnsan12/drf-yasg/issues/41, which is a nice-to-have but not currently being worked on.

**Comment by PaulWay** [comment]
I'm already using a manual parameter and it doesn't get picked up.
```python
system_uuid_param = openapi.Parameter(
    'uuid',
    openapi.IN_PATH,
    description="UUID of system",
    required=True,
    type=openapi.TYPE_STRING,
)
...
class SystemViewSet(viewsets.GenericViewSet):
    ...

    @swagger_auto_schema(manual_parameters=[system_uuid_param])
    def retrieve(self, request, uuid, format=None):
```
It *does not* get picked up.

**Comment by axnsan12** [comment]
> The parameter gets recognised, but the description does not get put in the schema.

What does that mean? Does it not appear in the final JSON?

**Comment by PaulWay** [comment]
Correct.

**Comment by PaulWay** [comment]
The JSON for that parameter (abridged) is:
```json
    "/system/{uuid}/": {
      "get": {
        "operationId": "system_read",
        "description": "Retrieve a system",
        "parameters": [
          {
            "name": "uuid",
            "in": "path",
            "description": "UUID of system",
            "required": true,
            "type": "string",
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/System"
            }
          }
        },
        "tags": [
          "system"
        ]
      },
      "parameters": [
        {
          "name": "uuid",
          "in": "path",
          "required": true,
          "type": "string"
        }
      ]
    },
```

Note that the `GET` parameter *does* have a description, but the URL's path parameter doesn't.

**Comment by PaulWay** [comment]
Our secondary schema testing tool complains that the parameter for the view is not described.

**Comment by axnsan12** [comment]
Which is correct and [according to spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object).

**Comment by axnsan12** [comment]
You could use a custom ``get_path_item`` implementation to work around non-compliant tooling

```python
class CustomSwaggerSchemaGenerator(OpenAPISchemaGenerator):
    def get_path_item(self, path, view_cls, operations):
        # move path Parameters to Operation level (down from PathItem level)
        # ng-swagger-gen is dumb
        path_item = super().get_path_item(path, view_cls, operations)
        for method, op in operations.items():
            op_params = op.parameters or []
            op.parameters = path_item.parameters + op_params

        del path_item.parameters
        return path_item
```

**Comment by PaulWay** [comment]
OK, thanks for that - will look into that.  I really appreciate your help, you know the project and the OpenAPI schema much better than I do!  Thanks once again.

**Comment by PaulWay** [comment]
That code you posted is for the reverse problem - where the operation's parameters need to be filled in by the path parameters.  Was that intentional?

It's just a question of how much effort I go to in order to fool `oatts` and `mocha` :-)

**Comment by axnsan12** [comment]
The problem is, most likely, that your tool assumes parameters are only present on Operation objects. The code I posted is for moving parameters declared on PathItem objects into all the Operation objects they apply to.

The order here

```python
            operation_params = OrderedDict(path_item_params)
            operation_params.update(param_list_to_odict(operation.get('parameters', [])))
```

is reversed because parameters declared on Operation overrule those declared on PathItem.
