### ISSUE TITLE
Use the first line of the docstring as `summary`

### ISSUE THREAD

**Issue by karimone** [axnsan12/drf-yasg#205]
Hello, I overrided the `SwaggerAutoSchema` to generate the summary from the first line of the docstring of the module. Here the code I used:

```
class ECSwaggerAutoSchema(SwaggerAutoSchema):
    """EC modified Swagger schema used in settings"""

    def __init__(self, view, path, method, components, request, overrides):
        super(ECSwaggerAutoSchema, self).__init__(view, path, method, components, request, overrides)
        self._method = method.lower()

    def get_view_method_doc(self):
        """Returns the doc in view method if is available else None"""
        try:
            doc = getattr(self._sch.view, self._method).__doc__  # type: str or None
            return doc if isinstance(doc, str) else None
        except AttributeError:
            return None

    def get_summary(self):
        """Return a summary description for this operation.

        If `operation_summary` is available will override the first line of the docstring.

        :return: the summary
        :rtype: str or None
        """
        doc = self.get_view_method_doc()
        first_string_line = doc.split(sep='\n')[0] if doc else None
        operation_summary = self.overrides.get('operation_summary', None)

        return operation_summary if operation_summary else first_string_line
```

Maybe is something useful to put in the original class?

**Comment by axnsan12** [comment]
This is simple enough to implement that I'm happy having it remain optional. Not everyone might agree with your definition of summary.

There's also no need to ``save ._method`` in __init__, you can always access ``self.method``. ``get_view_method_doc`` could also be replaced by ``self.get_description()``.

**Comment by axnsan12** [comment]
Hmm, ok, fair enough. I'll look into it.

**Comment by gustabot42** [comment]
This is a good idea, but is break a lot of documentation allready in production, maybe is better usign metadata annotation http://fletcher.github.io/MultiMarkdown-5/metadata.html

**Comment by axnsan12** [comment]
Why do you say 'break'? The first line should only be used if it's short enough so it should look good in most cases.

**Comment by gustabot42** [comment]
My docstring have a short description, enought to the code to display it as summary, i have to add spaces to avoid it. But the idea to have data for the documentation in the docstring look great for me, I just implement Markdown Metadata in this commit:
https://github.com/gustabot42/drf-yasg/commit/598d3aa202e83d85d251d8b4c8ddb4fec3139a01

**Comment by axnsan12** [comment]
What you're saying shouldn't be happening, at least not intentionally. The full description should never be interpreted as a summary if that would leave the description field blank.

Spaces (leading and trailing) should also have no effect on length considerations.

Would you mind providing an example docstring with problems?

**Comment by byrman** [comment]
If I write a multi-line docstring, the summary line shows up as operation_summary, the rest as operation_description:

![screenshot from 2019-01-15 10-36-30](https://user-images.githubusercontent.com/1039433/51171641-b49d5a80-18b1-11e9-864f-7f9e092f4ced.png)

If I write a one-line docstring, however, it is displayed as operation_description:

![screenshot from 2019-01-15 10-41-21](https://user-images.githubusercontent.com/1039433/51171803-1f4e9600-18b2-11e9-96fc-da5eab4b933d.png)

Wouldn't it be more logical to handle the first line as operation_summary in both cases, so users don't have to expand operations by clicking on them to read one-line docstrings?

**Comment by axnsan12** [comment]
This behaviour is there to prevent awkward summaries - if there is no explicit separation we err on the safe side and assume it doesn't fit as a summary.

You can customize it with the new ``split_summary_from_description`` method in 1.12.

**Comment by byrman** [comment]
Thanks for your swift reply! I don't really understand how/why one-liners may result in awkward summaries, but I'm happy with the flexibility.

**Comment by axnsan12** [comment]
See https://github.com/axnsan12/drf-yasg/issues/265

**Comment by byrman** [comment]
Ah, I see. I guess all cases would be handled correctly if this trim function is applied to the description: https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation. This algorithm is in the standard library: https://docs.python.org/3/library/inspect.html#inspect.cleandoc. But again, I happy that it can be easily customized.
