### ISSUE TITLE
Remove the `.idea` folder from the repository

### ISSUE THREAD

**Issue by karimone** [axnsan12/drf-yasg#207]
Is the pycharm configuration, it simply should be not there.

**Comment by axnsan12** [comment]
It is (mostly) non-user-specific PyCharm configuration, such as inspection settings, ignored directories, etc; it's helpful to have this data shared between everyone that uses PyCharm.

**Comment by varnion** [comment]
I opened #237 before viewing this. I had a bad experience some yrs ago opening [a project](https://github.com/varnion/FastaDB) with these configs present. Maybe pinpointing which files are exclusive for user-specific configs and only ignoring them could help.

**Comment by axnsan12** [comment]
> Maybe pinpointing which files are exclusive for user-specific configs and only ignoring them could help.

It's already like that, most user files should be ignored. Did you have any problems when opening the project?
