### ISSUE TITLE
coreschema to OpenAPI conversion does not use all available information

### ISSUE THREAD

**Issue by danizen** [axnsan12/drf-yasg#212]
I'm buliding an architecture that combines the following packages:

- django rest framework (==3.8.2)
- django-filter (==1.1.0)
- drf_yasg (==1.10.2)

One thing that eludes me is how to provide the format and/or pattern for string fields in path or query (filter).   I enhanced DjangoFilterBackends as follows:

```python
class CustomFilterBackend(filters.DjangoFilterBackend):
    """
    Enhance DjangoFilterBackend to allow providing the format and the pattern to the schema,
    Note that this breask the ability to instantiate the filter in the Browseable API.
    """
    def get_coreschema_field(self, field):
        schema = super().get_coreschema_field(field)
        schema.format = field.extra.get('format', None)
        schema.pattern = field.extra.get('pattern', None)
        return schema
```

Then, when I create a `FilterSet` using django-filter, I can provide the format and pattern:

```python
    start_date = filters.DateTimeFilter('updated_timestamp', lookup_expr='gte', required=True,
                                        help_text='Updated timestamp greather than or equal to',
                                        format='date', pattern=r'^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
```

A view using this filterset class does indeed return filter fields having a coreschema.schema class with format and pattern, but drf_yasg doesn't render it into the swagger schema

```python
In [12]: NCBIChangesCBV().schema.get_filter_fields('/', 'GET')
Out[12]:
[Field(name='start_date', required=True, location='query', schema=<coreschema.schemas.String object at 0x000001675C2B3710>, description=None, type=None, example=None),
 Field(name='end_date', required=False, location='query', schema=<coreschema.schemas.String object at 0x000001675C2B3550>, description=None, type=None, example=None)]

In [13]: NCBIChangesCBV().schema.get_filter_fields('/', 'GET')[0]
Out[13]: Field(name='start_date', required=True, location='query', schema=<coreschema.schemas.String object at 0x000001675C2B3B38>, description=None, type=None, example=None)

In [14]: NCBIChangesCBV().schema.get_filter_fields('/', 'GET')[0].schema.format
Out[14]: 'date'

In [15]: NCBIChangesCBV().schema.get_filter_fields('/', 'GET')[0].schema.pattern
Out[15]: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
```

Can you either enhance it to do so or point me towards a work-around?  

Thanks.

**Comment by axnsan12** [comment]
You should avoid the ``get_coreschema_field`` method since it operates using [CoreAPI](http://www.coreapi.org/), which lacks most features of Swagger/OpenAPI.

``drf-yasg`` uses this information converted to OpenAPI as a compatibility fallback, but the conversion is very rudimentary: https://github.com/axnsan12/drf-yasg/blob/20786e53c3949d14c00d70d112f4452ec850ba5f/src/drf_yasg/inspectors/query.py#L29-L53

You should instead implement a custom [FieldInspector](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#inspector-classes) to cut out the middleman.

**Comment by axnsan12** [comment]
However the compatibility adapter should also probably be updated to use all available ``coreschema`` information.

**Comment by danizen** [comment]
@axnsan12, thanks for your quick reply.  `coreschema.schemas.String` now contains "format" and "pattern" attributes.   I understand that your code may not be able to use these directly for compatibility reasons - there are probably versions of coreapi out there so old that field.schema does not exist.

Would something like this work?

```python
    def coreapi_field_to_parameter(self, field):
        """Convert an instance of `coreapi.Field` to a swagger :class:`.Parameter` object.

        :param coreapi.Field field:
        :rtype: openapi.Parameter
        """
        location_to_in = {
            'query': openapi.IN_QUERY,
            'path': openapi.IN_PATH,
            'form': openapi.IN_FORM,
            'body': openapi.IN_FORM,
        }
        coreapi_types = {
            coreschema.Integer: openapi.TYPE_INTEGER,
            coreschema.Number: openapi.TYPE_NUMBER,
            coreschema.String: openapi.TYPE_STRING,
            coreschema.Boolean: openapi.TYPE_BOOLEAN,
        }
        return openapi.Parameter(
            name=field.name,
            in_=location_to_in[field.location],
            type=coreapi_types.get(type(field.schema), openapi.TYPE_STRING),
            format=getattr(field.schema, 'format', None),
            pattern=getattr(field.schema, 'pattern', None),
            required=field.required,
            description=force_real_str(field.schema.description) if field.schema else None,
        )
```

**Comment by danizen** [comment]
Actually, let me back-up and try to make my code work correctly before enhancing someone else's.  I'll review the settings documentation and see how I can bypass CoreAPICompatInspector to implement a custom FieldInspector.

**Comment by danizen** [comment]
Easy - https://drf-yasg.readthedocs.io/en/stable/settings.html#default-filter-inspectors.

```python
class EnhancedCoreAPICompatInspector(CoreAPICompatInspector):

    def coreapi_field_to_parameter(self, field):
        """Enhance default implementation to handle format and pattern if present

        :param coreapi.Field field:
        :rtype: openapi.Parameter
        """
        param = super().coreapi_field_to_parameter(field)
        if isinstance(field, schemas.String):
            param.format = field.schema.format
            param.pattern = field.schema.pattern
```

I'll open another issue for enhancement to support `coreschema.schemas.String.format` and `coreschema.schemas.String.pattern`, and track down versions where these appear.
