### ISSUE TITLE
What is the best way to provide example responses

### ISSUE THREAD

**Issue by danizen** [axnsan12/drf-yasg#214]
I have implemented a legacy API requiring custom renderers.   What they render bears little resemblance to the serializer.   However, the auto schema generated for the JSON response is quite useful.  What is the best way to add additional responses?

Self-describing APIs is hard ;)

**Comment by danizen** [comment]
So, I think the best *generic* way is to implement filed inspectors that teach the `SwaggerAutoSchema` how to derive schema examples from some meta-data on the serializer class.

However, it seems questionable whether this is best practice - the main use-case for this is idiosyncratic responses as the defaults are actually reasonable.   So, it may be best to simply pass an openapi.Response as a manual response to the thing.

Another way to do this might be to implement a sub-class of `SwaggerAutoSchema` that can accept a django lazy object in the [manual responses](https://github.com/axnsan12/drf-yasg/blob/20786e53c3949d14c00d70d112f4452ec850ba5f/src/drf_yasg/inspectors/view.py#L236
).   As it stands, you must instantiate the entire thing in the swagger_auto_schema decorator itself, rather than pass something lazy.

**Comment by danizen** [comment]
OK, I think I have a game plan to make this work, at least for me - the goal will be to sub-class `drf_yasg.Response`, `drf_yasg.Schema`, and `drf_yasg.Responses` to produce a sort of "lazy" version of these dictionaries.  They will load their data from a JSON or YAML file into the swagger dict, with a white list for which keys may be present in the file.   Then, these lazy openapi objects can be used in place of the actual ones.

**Comment by danizen** [comment]
I think generalizing this pattern is not worth it, and therefore someone else's github issues is not the right place to discuss it.   This would make an interesting long-form blog post, but it isn't a github issue with drf-yasg.

**Comment by axnsan12** [comment]
Hey, sorry for letting you monologue like this 😄 Glad you figured it out (for both issues).

**Comment by jerinpetergeorge** [comment]
For latecomers, this StackOverflow post probably will help you to customize the response and the response example.

[**Add example response using `drf-yasg`**](https://stackoverflow.com/questions/64109297/drf-yasg-how-to-show-sample-response-with-with-api)
