### ISSUE TITLE
Custom 'x-my-keys' in operations

### ISSUE THREAD

**Issue by mbarchein** [axnsan12/drf-yasg#215]
In my project, I need to add custom 'x-some-keys' to the different paths of the generated json. Is this possible somehow using @swagger_auto_schema decorator?

Thanks.

**Comment by axnsan12** [comment]
``swagger_auto_schema`` can only help you up to ``Operation`` level. For ``PathItem`` or ``Paths`` you're looking for [OpenAPISchemaGenerator.get_path_item](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_path_item) or [OpenAPISchemaGenerator.get_paths](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_paths).

**Comment by jcctudela** [comment]
So, if in the `swagger_auto_schema` we add any parameter to the extra_overrides, it should appear in the YAML file inside the operation structure?

Thanks!

**Comment by mbarchein** [comment]
Thanks for your answer, but I think my question was wrong. I needed it in the operation level. What I want to add to the JSON output is this:

```
 ...
 "paths": {
    "/modelname/": {
      "get": {
        "x-my-key": {"k1": v1, "k2", v2},
        ...
      },
      ...
   },
   ...
```

I tried with 

```
    @swagger_auto_schema(
        responses={ ... },
        x_my_key = {'k1':'v1', 'k2':'v2'}
    )
    def retrieve(self, request, *args, **kwargs):
        ...
```
but that didn't make any result in the json output.

**Comment by axnsan12** [comment]
``extra_overrides`` does not do anything by itself, you have to use it in a custom ``SwaggerAutoSchema``; you can get the values you pass in from ``self.overrides``.

If you want to set them on ``Operation`` you should probably override [get_operation](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_operation).

**Comment by mbarchein** [comment]
Thanks for your help! This is my working solution, as a reference:

```
from drf_yasg.inspectors import SwaggerAutoSchema

class MyCustomSwaggerAutoSchema(SwaggerAutoSchema):
    def get_operation(self, operation_keys):
        """
        Adds '"x-my-tag":value' to operation dictionary with all overrides "x_whatever"
        The override key must begin with "x_"

        Example:

            @swagger_auto_schema(
                responses={
                    status.HTTP_200_OK: AttributeCategorySerializer,
                    status.HTTP_404_NOT_FOUND: 'Not found'
                },
                x_app_roles = {
                    'customer': 'customer allows getting own information'
                }
            )
            def retrieve(self, request, *args, **kwargs):
                ...

        :param operation_keys:
        :return: openapi.Operation
        """
        operation = super(IMISwaggerAutoSchema, self).get_operation(operation_keys)

        for k in self.overrides:
            if k.startswith("x_"):
                setattr(operation, k.replace('_','-'), self.overrides[k])

        return operation
```

and in settings.py

```
...
SWAGGER_SETTINGS = {
    'DEFAULT_AUTO_SCHEMA_CLASS': 'config.swagger.MyCustomSwaggerAutoSchema',
}
...
```
