### ISSUE TITLE
Merge Serializers - Help Needed

### ISSUE THREAD

**Issue by intellisense** [axnsan12/drf-yasg#216]
Hi,

Consider following models:

```python
class FieldVersion(models.Model):
    field = models.ForeignKey('myapp.Field')
    # other fields

class Field(models.Model):
    name = models.CharField(max_length=50)
    # other fields
```

For above models we have these serializers:

```python
class FieldSerializer(serializer.ModelSerializer):
    class Meta:
        fields = '__all__'
        model = Field

class FieldVersionSerializer(VersionModelSerializer):
    class Meta:
        model = FieldVersion
        fields = '__all__'
        related_model_serializer_class = FieldSerializer
```

`VersionModelSerializer` is a custom model serializer which automagically handles the creation of `Field` when `FieldVersion` is created, it also overrides the `to_representation` method to inject serialization data from `FieldSerializer` into `FieldVersionSerializer`.

Now obviously swagger schema does not know about this, so I was thinking to override `SerializerInspector` (not sure which method specifically, perhaps `field_to_swagger_object`) and check if serializer has `related_model_serializer_class` in meta then merge its schema into the the schema of `FieldVersionSerializer`. Any ideas?

Thanks!

**Comment by axnsan12** [comment]
Yeah - your idea sounds good, ``field_to_swagger_object`` would be the best place to handle this. Sorry for the late reply.
