### ISSUE TITLE
URLPathVersioning mixed different version schema 

### ISSUE THREAD

**Issue by GeniusWiki** [axnsan12/drf-yasg#221]
I am using URLPathVersioning in DRF. My API has both older version "v3" and new one "v[4-9]".  yasg doesn't process the version properly that the schema view always mixed v3 and v4.   My URL conf:
```
    url(r'^api/(?P<version>v[4-9]+)/', include(api_router_urls),
    url(r'^api/(?P<version>v3)/', include(api_v3_router_urls)),

url(r'^api/(?P<version>v[3-9]+)/swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
```

I roughly checked the source,  it looks yasg replace all api URL by a string {version} first, then replace that {version} by schema request URL version. For example, if I open schema by /api/v4/swagger/.  and if a v3  only URL is /v3/some_api;  yasg replace it to /{version}/some_api first, then replace to /v4/some_api - even this URL does not exist in v4.

**Comment by axnsan12** [comment]
You are right about how it is currently handled. This covers the general case where all routes exist in all versions.

When you have differing routes per version - as you do - the ``patterns`` argument of ``get_schema_view`` should serve you well. Something like:

```python
schema_view_v4_plus = get_schema_view(patterns=api_router_urls, ...whatever)
schema_view_v3 = get_schema_view(patterns=api_v3_router_urls, ...whatever)

url(r'^api/(?P<version>v[4-9]+)/swagger(?P<format>\.json|\.yaml)$', schema_view_v4_plus .without_ui()),
url(r'^api/(?P<version>v3)/swagger(?P<format>\.json|\.yaml)$', schema_view_v3.without_ui()),
```

Another option would be to switch to ``NamespaceVersioning`` which can handle this transparently.
