### ISSUE TITLE
inspect.signature() not available in python 2.7

### ISSUE THREAD

**Issue by lindsayemarc** [axnsan12/drf-yasg#222]
![image](https://user-images.githubusercontent.com/1686651/46091544-114cfc00-c181-11e8-9b05-dbf9b54fd795.png)

inspect.signature() is used in inspectors/field.py 

This completely breaks python 2.7 compatibility. 

here is a fix that was made in another open source project that ran into the same problem 
https://github.com/NiklasRosenstein/pydoc-markdown/commit/77c37a78e48e4416ef9eabaa06bef7417f376fb3

**Comment by axnsan12** [comment]
The mentioned code is only called if ``typing`` can be imported, which should not be the case on python <3.5. How exactly does it break compatibility for you?

https://github.com/axnsan12/drf-yasg/blob/20786e53c3949d14c00d70d112f4452ec850ba5f/src/drf_yasg/inspectors/field.py#L547-L549

**Comment by lindsayemarc** [comment]
I am able to import typing successfully in python 2.7.10
![image](https://user-images.githubusercontent.com/1686651/46095722-3181b880-c18b-11e8-9e6c-e968a842a4b3.png)

I will do some digging to see why that is the case

**Comment by axnsan12** [comment]
Apparently my assumption was wrong and there exists a backport of the ``typing`` module: https://pypi.org/project/typing/

I'll add a check specifically for python 2. Tests are currently passing because the backport is not installed by any test dependency...

**Comment by lindsayemarc** [comment]
awesome! I appreciate you looking into this
