### ISSUE TITLE
Description for a body parameter based on a schema

### ISSUE THREAD

**Issue by PaulWay** [axnsan12/drf-yasg#223]
In a method decorated with:
```python
@swagger_auto_schema(request_body=InputSerializer)
```
How do we set a description for the 'data' parameter in the body?  If I try to set a custom manual parameter with a description, `add_manual_parameter` complains that it can't add an `openapi.IN_BODY` parameter.  But there doesn't seem to be a way of picking up a description of the serializer as a parameter.

**Comment by axnsan12** [comment]
Indeed the body parameters is mostly hardcoded. You can modify it by overriding [SwaggerAutoSchema#make_body_parameter](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.inspectors.SwaggerAutoSchema.make_body_parameter).

**Comment by axnsan12** [comment]
Implement this as:

```python
class BodyDescriptionAutoSchema(SwaggerAutoSchema):
    def make_body_parameter(self, schema):
        body_param = super().make_body_parameter(schema)
        body_param.setdefault('description', getattr(schema, 'description', None))
```

Since request and response schemas are frequently shared, I don't believe this makes sense in the general case.
