### ISSUE TITLE
Validator authentication

### ISSUE THREAD

**Issue by nicholasgcoles** [axnsan12/drf-yasg#225]
Hello I have a question,

I have session authentication with my Django project. When I go to the swagger url it generates the docs perfectly except it always throws an error:
![image](https://user-images.githubusercontent.com/1975028/46241934-49428200-c3c1-11e8-9485-697d8959e169.png)

With error message being:
`{"schemaValidationMessages":[{"level":"error","message":"Can't read from file https://my-example-url.com/swagger/?format=openapi"}]}`

When I visit the above url (https://my-example-url.com/swagger/?format=openapi) directly it works perfectly in the sense that it returns the json data but when I try view it in an incognito window it throws the same error. `TypeError: Expected a `openapi.Swagger` instance`

It seems that the validator is not authenticated to view my swagger-json and therefore says there is an error? Is there a way around this? Perhaps I have set it up incorrectly.

Thanks so much!

**Comment by GmAccount** [comment]
Hi

If you want hide this error :

can you set  VALIDATOR_URL to  None in your setting
like :
SWAGGER_SETTINGS = {
   'VALIDATOR_URL' : None,
....

**Comment by axnsan12** [comment]
Since swagger-ui has no support for directly POSTing the schema document to the validator, there's no way around this. The validator will always make an unauthenticated request to the url provided.

Hiding the badge seems to be your best bet.
