### ISSUE TITLE
Allow schema type array to have File items

### ISSUE THREAD

**Issue by finkedave** [axnsan12/drf-yasg#226]
Allowing parameters to be arrays of integers works, strings works as well. Code is like so
```
openapi.Parameter(
                name='sequence_files',
                in_=openapi.IN_FORM,
                type=openapi.TYPE_FILE,
                items=openapi.Schema(type=openapi.TYPE_INTEGER),
                description="Sequence files to use for analysis",
                required=True),
```
But changing the items to a list of files does not
```
openapi.Parameter(
                name='sequence_files',
                in_=openapi.IN_FORM,
                type=openapi.TYPE_ARRAY,
                items=openapi.Schema(type=openapi.TYPE_FILE),
                description="Sequence files to use for analysis",
                required=True),
```
gives 
(\\'items\\', OrderedDict([(\\'type\\', \\'file\\')]))]) is not valid under any of the given schemas">)'}

Is this something that can be and should be added?

**Comment by axnsan12** [comment]
OpenAPI 2 does not support this: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#items-object

> Field Name | Type | Description
> -- | -- | --
> type | string | Required. The internal type of the array. The value MUST be one of "string", "number", "integer", "boolean", or "array". _**Files and models are not allowed.**_
