### ISSUE TITLE
Adding x-code-samples to operations

### ISSUE THREAD

**Issue by Maronato** [axnsan12/drf-yasg#231]
I'm trying to add [x-code-samples](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#x-code-samples) from ReDoc to my project and I got to the point where I have overridden SwaggerAutoSchema's get_operation method to include the `x-code-samples` attribute to the Operation.

The problem I'm facing is how to cleanly generate the example data to populate the code samples.
I could manually generate examples from the parameters' types, but I feel that it'd be much easier to just use whatever method is already used to populate the default request and response samples.

Could you shed some light on how the example data from the request and response samples are currently generated?

**Comment by Maronato** [comment]
Thanks! I ended up manually handling the sample creation.

**Comment by jangia** [comment]
I've done it by overriding **get_operation** method using self.overrides. Maybe it could be somehow added to the package?

**Comment by rmccullin** [comment]
Any possibility of showing the code on how you did this?  I am trying to do the same thing and haven't figured it out.
