### ISSUE TITLE
How to add query parameters to endpoint

### ISSUE THREAD

**Issue by leonardoarruda** [axnsan12/drf-yasg#232]
Hello.

I need your help to understand one thing. Should be simple. I am trying add some endpoints from DRF project to Swagger. So I am using patterns like this:

```
schema_view = get_schema_view(
    openapi.Info(
        title="Test API",
        default_version='v1',
        description="Hello.",
    ),
    validators=None,
    public=True,
    permission_classes=(AllowAny,),
    patterns=[
        url(r'^test_endpoint/$', TestEndpointView.as_view({
            'get': 'test_endpoint'
        })),
    ]
)

urlpatterns = [
    url(r'^doc/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]
```

It works. The problem is that I want to call the url like 'http://localhost:8000/?param=param-information' and I have no idea how to add query parameters to swagger.json using Yasg.

Can you help me?

Sorry for bad English and thank you! :)

**Comment by leonardoarruda** [comment]
Just found out that if I use swagger_auto_schema with manual_parameters as decorator at View, it works. But, if I use the same decorator with 'as_view', it doesn't work.

**Comment by leonardoarruda** [comment]
I fixed using custom swagger-ui.html and CSS display:none. Not the most wonderful thing, but life is life. Thanks and see you later! :)

**Comment by axnsan12** [comment]
Glad you worked it out!

**Comment by mke21** [comment]
Can someone explain how this works? The documentation is not very clear and I can't get it to work.
