### ISSUE TITLE
django-oauth-toolkit - Is there any way to add /o/token/ endpoint into swagger?

### ISSUE THREAD

**Issue by unixconky** [axnsan12/drf-yasg#234]
Is there any way to add `/o/token/` endpoint into swagger?

https://django-oauth-toolkit.readthedocs.io/en/latest/rest-framework/getting_started.html#step-4-get-your-token-and-use-your-api

**Comment by axnsan12** [comment]
Not currently supported because the view [is not a REST Framework](https://github.com/jazzband/django-oauth-toolkit/blob/4a8e1c5ff3d680044ffc545dba2f782199a7fb56/oauth2_provider/views/base.py#L190) view.

**Comment by huutinh2712** [comment]
Hi @axnsan12, i'm currently working with django-oauth-tookit with drf-yasg. Just wondering It support to add these enpoint into swagger?
