### ISSUE TITLE
Swagger not fetching details from swagger_auto_schema

### ISSUE THREAD

**Issue by deepakzipgo** [axnsan12/drf-yasg#235]
I am using **swagger_auto_schema** in **function based views** like below. It seems like **Swagger** is not using the **annotations** at all. What am I doing wrong?

urls.py
```
from django.conf.urls import url
from .views import check_phone
urlpatterns = [
	url(r'^check_phone/?', check_phone),
]
```

views.py
```
class CheckPhoneSerializer(serializers.Serializer):
	phone = serializers.CharField(max_length=20)
	exist = serializers.BooleanField()

phone_param = Parameter('phone', IN_QUERY, description="user phone number", type=TYPE_STRING)
check_phone_response = Response('Response contains phone exists or not', CheckPhoneSerializer)

@csrf_exempt
@api_view(["GET"])
@swagger_auto_schema(operation_description="Checks whether phone number already exists", operation_id='agent_auth_check_phone', manual_parameters=[phone_param], responses={200: check_phone_response})
@permission_classes((IsAuthenticated,))
@require_http_methods(["GET", "POST"])
@renderer_classes([renderers.OpenAPIRenderer, renderers.SwaggerUIRenderer])
def check_phone(request):
	phone = request.GET.get("phone") if request.method == 'GET' else request.POST.get("phone")
	data = {"phone": phone, "exist": True}
	return JsonResponse(data)
```

**Comment by axnsan12** [comment]
Order of decorator matters. Your function is only a view after the ``api_view`` decorator is applied. Move ``swagger_auto_schema`` _above_ it.

**Comment by deepakzipgo** [comment]
> Order of decorators matters. Your function is only a view after the `api_view` decorator is applied. Move `swagger_auto_schema` _above_ it.

On moving it I am getting this error.
`AssertionError: on multi-method api_view, action, detail_route or list_route, you must specify swagger_auto_schema on a per-method basis using one of the `method` or `methods` arguments`

On putting method='get' in swagger_auto_schema, the browser shows.
AssertionError at /swagger.json
duplicate Parameters found

**Comment by deepakzipgo** [comment]
@axnsan12 , can you please let me know what changes I have to make to get the annotation working?

**Comment by deepakzipgo** [comment]
I put the project in INSTALLED_APPS and it worked.

**Comment by deepakzipgo** [comment]
I put in the project INSTALLED_APPS and it worked.
