### ISSUE TITLE
Two serializers with the same name causes swagger object error. 

### ISSUE THREAD

**Issue by cbhrocks** [axnsan12/drf-yasg#240]
The following example causes the error:

folder structure:

 app
__ serializers
____ \_\_init__.py
____ user.py
____ comment.py

**__init__.py**

```
import CommentSerializer from  app.serializers.comment
import UserSerializer from app.serializers.user
```

**user.py**
```
class UserSerializer(ModelSerializer):
    class Meta:
        fields = (
            "id",
            "username",
            "full_name"
        )
```

**comment.py**
```
class UserSerializer(ModelSerializer):
    class Meta:
        fields = (
            "full_name"
        )

class CommentSerializer(ModelSerializer):
    created_by = UserSerializer(many=False, read_only=True)
    class Meta:
        fields = (
            "id",
            "body"
            "created_by",
        )
```

because CommentSerializer contains its own version of UserSerializer it can cause the swagger auto generator to use the wrong serializer for representing user objects in requests. The user object created will be titled `Created By`, and only contain the field full_name

**Comment by axnsan12** [comment]
Indeed, your observations are correct, and intended behaviour. You [should also have seen a warning logged to the console](https://github.com/axnsan12/drf-yasg/blob/c5f6a79cc89a716d121c09953c5f8a23a5f33d38/src/drf_yasg/inspectors/field.py#L130).

The solution is to set different names using ``ref_name``: https://drf-yasg.readthedocs.io/en/stable/custom_spec.html
