### ISSUE TITLE
Invalid curl parameters

### ISSUE THREAD

**Issue by gd-gl** [axnsan12/drf-yasg#241]
I'm using the built-in session-based authentication, and the login endpoint (`http://localhost:8000/api/auth/login`) is working fine. Here is a snippet from the google chrome console showing the all the required cookies are set:

![screenshot from 2018-10-27 20-27-48](https://user-images.githubusercontent.com/41420646/47607323-06f37b80-da27-11e8-904a-eaae602401fc.png)

Afther succesfull authentication, I can see the rest of my endpoints, but I cannot call any POST method, because it looks like there is no `X-CSRFToken` in `curl` parameters. Here I'm trying to create a new dummy user:

![screenshot from 2018-10-27 20-32-37](https://user-images.githubusercontent.com/41420646/47607357-88e3a480-da27-11e8-8a62-21bbc644f9e9.png)

I've also tried the `django-rest-swagger` library, and it doesn't have this problem, but really don't want to use it due to the lack of functionality (also it seems that it's not supported anymore).

UPDATE 1: my library versions
```
Django==2.1.2
djangorestframework==3.8.2
drf-yasg==1.11.0
```

UPDATE 2: my swagger usage
```python
    schema_view = get_schema_view(
        info=openapi.Info(
            title='My API',
            default_version='alpha',
        ),
        public=False,
        permission_classes=[permissions.AllowAny],
    )

    urlpatterns.append(
        re_path(r'^swagger/$', schema_view.with_ui(renderer='swagger'))
    )
```

**Comment by axnsan12** [comment]
The csrf token is not sent if you disable session auth. (USE_SESSION_AUTH setiing).

**Comment by gd-gl** [comment]
Thank you very much! I explicitly disabled USE_SESSION_AUTH because I use my custom login/logout views, so the default ones aren't appropriate for me.

**Comment by axnsan12** [comment]
You can change the links using LOGIN_URL and LOGOUT_URL ( they also fallback to the global ones).

**Comment by gd-gl** [comment]
It's not a good idea, because it looks like LOGIN_URL assumes, that it simply has to redirects the user to the login page with some login form.
Here is an example of setting LOGIN_URL to my custom `/api/auth/login/` (which expects POST requests with email/password specified). After clicking the button
![screenshot from 2018-10-27 20-58-13](https://user-images.githubusercontent.com/41420646/47607642-28eefd00-da2b-11e8-9ec1-ee08457d5db3.png)
I get
![screenshot from 2018-10-27 20-58-20](https://user-images.githubusercontent.com/41420646/47607643-2f7d7480-da2b-11e8-9345-6bbc476a650d.png)

**Comment by gd-gl** [comment]
Anyway, my problem is solved, so the issue can be closed. Thank you again.

**Comment by axnsan12** [comment]
Well, the link is intended to point to a frontend page which calls the appropriate APIs, for convenience.

Glad you worked it out!
