### ISSUE TITLE
get `class_name` or arguments of a function in swagger_auto_schema

### ISSUE THREAD

**Issue by prafulbagai** [axnsan12/drf-yasg#243]
I've view where I decorate the get/post methods using `swagger_auto_schema`.

```
class ABCView(generics.CreateAPIView):

    queryset = Loan.objects.all()
    permission_classes = [JWTHasResourceScopeForMethod]

    @swagger_auto_schema()
    def post(self, *args, **kwargs):
        return super(LoanView, self).post(*args, **kwargs)

```

I want to over-ride the decorator and get either class_name or list of arguments passed to the function inside [swagger_auto_schema](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/utils.py#L103). How can I fetch it?

**Comment by prafulbagai** [comment]
Why i want to do this is because of the following reason:-

`swagger_auto_schema` accepts `responses` as an argument. However

**Comment by axnsan12** [comment]
Which class name? What arguments? You can't acces the function arguments since the schema must be generated without calling the function...

**Comment by prafulbagai** [comment]
Here's the use-case:-

I've a view as below:-

```
class XYZView(generics.CreateAPIView):

    queryset = XYZ.objects.all()
    serializer_class = XYZSerializer

```

I want to add a `query_serializer`, and `default` and `400` response (for all my endpoints)  in `swagger_auto_schema`.

There are 2 ways of doing this:-

1) I over-ride my post method in the view as follow:-

```
class XYZView(generics.CreateAPIView):

    queryset = XYZ.objects.all()
    serializer_class = XYZSerializer

   @swagger_auto_schema(responses={
                         400: ErrorSerializer,
                         200: XYZSerializer},
                         query_serializer=QuerySerializer)
    def post(self, request, *args, **kwargs):
        return super(XYZView, self).post(request, *args, **kwargs)
```

In this case, I would have to over-ride all HTTP endpoints of my applications (even though I'm using `generics` class of DRF). Doing this would make my code unclean.

2) Over-ride `generics` class of rest framework, apply `swagger_auto_schema` on top of it and then inherit the custom generics class in my `views`. Consider the below example.

**Over-riding generics**

```
from rest_framework import generics

class CreateAPIView(generics.CreateAPIView):
    """Over-riding View to handle exceptions and generate docs."""

    @swagger_auto_schema
    def post(self, request, *args, **kwargs):
        return super(CreateAPIView, self).post(request, *args, **kwargs)

```

**My View:-**

```
class XYZView(generics.CreateAPIView):

    queryset = XYZ.objects.all()
    serializer_class = XYZSerializer
    query_serializer = QuerySerializer
    responses = {
         400: ErrorSerializer,
         200: XYZSerializer
    }
```

Now, I'll use the above `query_serializer` and `responses` in `swagger_auto_schema`. Sample code of `swagger_auto_schema` will be:-
```

def swagger_auto_schema(method=None, methods=None, auto_schema=unset, request_body=None, query_serializer=None, manual_parameters=None, operation_id=None, operation_description=None, operation_summary=None, security=None, deprecated=None, responses=None, field_inspectors=None, filter_inspectors=None, paginator_inspectors=None, **extra_overrides):
    def decorator(view_method):

        query_serializer = query_serializer or VIEWCLASS.query_serializer  // fetching from the class variables.
        responses = responses or VIEWCLASS.responses

        .... and so on
```

The second method would be much **cleaner** and would respect the DRF generics principles too.

Let me know, if I'm clear.

**Comment by axnsan12** [comment]
Well then this is really just a python question, not one about this library. A quick Google tells me ``view_method.im_class`` should work.

**Comment by prafulbagai** [comment]
No, it does not works. I've already tried that:-

`AttributeError: 'function' object has no attribute 'im_class'`

**Comment by axnsan12** [comment]
Right, because the function is not yet bound as a method during the time it is being defined (and decorated).

You could decorate the class itself and populate the necessary method attributes, or you could use a ``SwaggerAutoSchema`` subclass to automatically extract them.

**Comment by prafulbagai** [comment]
This is so great.
One quick question, when using `SwaggerAutoSchema`, how can I define different `responses` for different methods? for eg:-

GET responses:
```
responses={
    400: ErrorSerializer,
    200: response.GETResponseSerializer,
    'default': GETErrors
},
```

POST response can be:
```
responses={
    400: POSTErrorSerializer,
    200: POSTResponseSerializer,
},
```

**Comment by axnsan12** [comment]
All the information you need is available as attributes on self. Look to the source code for examples.

**Comment by prafulbagai** [comment]
Perfect. Got it. 

Listing the solution for other people to refer (just in case).

```
class AutoSchema(SwaggerAutoSchema):
    def get_responses(self):
        # over-riding get_responses
        responses = {
            400: self.view.error_serializer,
            200: self.view.response_serializer,
            'default': self.view.default_serializer
        }
        return openapi.Responses(
            responses=self.get_response_schemas(responses)
        )
```

Now, refer the above class in your view as `swagger_schema = CamelCaseOperationIDAutoSchema`

Thanks @axnsan12  for the help.
