### ISSUE TITLE
Make possible to specify response as Json

### ISSUE THREAD

**Issue by Antyk1** [axnsan12/drf-yasg#244]
Sometimes it's necessary to specify several responses.Now It's possible to specify response like:
`222: '{"detail": "Error..."},`
But if there are several possible errors in business logic with the same status, then it becomes too difficult to visualize them with indents.
It's my current solution, but it looks awful: 
`222: '{"detail": "Error1..."}   OR   {"detail": "Error2..."}`

**Comment by axnsan12** [comment]
You can't have multiple responses per status code. It's an openapi limitation. In openapi 3 you could use schema with oneOf, but for 2 I have no idea.
