### ISSUE TITLE
Inline css and javascript for swaggerUI and redoc

### ISSUE THREAD

**Issue by lockwooddev** [axnsan12/drf-yasg#247]
What do you think about having the css and javascript rendered inline in the swagger-ui and redoc views?

I currently have a use case where I use yasg on a micro service on kubernetes, but I don't want to add nginx or cloudfront to serve the staticfiles.

**Comment by axnsan12** [comment]
I don't think this falls into the scope of this project. Packaging and serving assets is a whole other problem, and you could always host your own bundling of a swagger frontend of your choice. 

The main feature of this library is the backend for generating the spec itself.

And the lack of inline scripts and styles is deliberate, to allow use of restrictive CSP headers for those who want to do that.
