### ISSUE TITLE
documentation update for urlpatterns

### ISSUE THREAD

**Issue by waspinator** [axnsan12/drf-yasg#250]
django has recently changed the way `urlpatterns` are written to use `path()`s instead of `url()`s.  Is there separate documentation for getting started with the 2.x series of django?

https://drf-yasg.readthedocs.io/en/stable/readme.html#quickstart

**Comment by axnsan12** [comment]
Replace ``url`` with ``path`` where there are no capture groups and ``re_path`` where there are.

**Comment by axnsan12** [comment]
The ``url`` example, which works with both Django 1 and 2, will stay until Django 1.11 support is dropped.
