### ISSUE TITLE
Parameters to provide a `validate` method

### ISSUE THREAD

**Issue by PaulWay** [axnsan12/drf-yasg#251]
Hi there!

I'm thinking of adding a 'validate' method to the Parameter class in the OpenAPI module.  This would check the given value (e.g. in a query) actually matched the type (and format, if set) of the parameter.

A further possibility would be to provide a `from_request` method which searched for the value in the request structure according to where it would be found (header, query, path, etc), and returned the value - or the parameter's default if the parameter was not found in the request.

What do you think?  Do you want me to write that?

Have fun,

Paul

**Comment by axnsan12** [comment]
This is out of the scope of this library, REST Framework serializers are just the tool for that.
