### ISSUE TITLE
Use CamelCase for FilterSets

### ISSUE THREAD

**Issue by Uxio0** [axnsan12/drf-yasg#253]
I would like to have camelcase conversion when using filtersets, but it's not working.

I have a Django Rest framework project with the CamelCase Json renderer and parser. If I define a filterset:

```python
class PersonFilter(filters.FilterSet):
    class Meta:
        fields = ('eye_color',)
```

I can query using `http://myurl/people?eyeColor=green`, but when I go to swagger I see `eye_color` as a query parameter.

I tried to set `DEFAULT_FILTER_INSPECTORS` to add `drf_yasg.inspectors.CamelCaseJSONFilter` but it seems not to be compatible with `drf_yasg.inspectors.CoreAPICompatInspector`. Is there any way I can use that? I don't mind to write a PR if it's not implemented

**Comment by axnsan12** [comment]
I don't think FilterSet parsing is affected by the JSON parser.  You can achieve what you want by overriding [get_filter_parameters](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/inspectors/query.py#L23) in your own inpsector.

**Comment by Uxio0** [comment]
I understand, but I understand it should be a desired behaviour, right? I mean, for serializers parsing CamelCase Json parsing for swagger is working flawlessly

**Comment by axnsan12** [comment]
I'm not sure *how* it works for you, but I don't think it's default behaviour and I don't think it's related to djangorestframework-camel-case

**Comment by Uxio0** [comment]
Humm, I think maybe I'm not explaining well, sorry. So for `serializers` the conversion of attributes from python style to camelcase is desired when showing models on swagger, but for `filters` is not?

**Comment by axnsan12** [comment]
No, what I'm saying is that functionally, ``django-filter`` has no code for making camelCase query parameters happen, and neither does ``djangorestframework-camel-case``, so I'm not sure how you're seeing that behaviour (i.e. the filter working with the camelCase parameter).

``drf-yasg`` tries to model t he real behaviour of the app as much as possible, so conversion to camelCase is desired only in the cases when the API will actually work with camelCase.

**Comment by Uxio0** [comment]
You are absolutely right, sorry and thank you very much. I was getting a cached result and thought that is was working
