### ISSUE TITLE
[UI] Swagger search and url fragment

### ISSUE THREAD

**Issue by Woile** [axnsan12/drf-yasg#254]
**URL Fragment**
Hello, I was wondering if it's possible to add a fragment (permalink) to the endpoints. This would be a really cool feature, allowing users to share specific endpoints.

For example, something like `localhost:8000/docs/#api-v1-users-detail`

**Search**
I'm having a weird behavior when I search. I don't know if I'm doing something wrong or it's a bug.
For example, let's suppose this endpoint:
`/v1/users/{id}/animals/{id}`
If I search by `v1` works ok, listing all the `v1` endpoints.
Searching by `users`, `id` or `animals` simply returns nothing.

I was wondering if a fuzzy search could be implemented instead.

Thanks a lot!

**Comment by axnsan12** [comment]
Frontend code is out of the scope of this library, the bundled UI clients are there just for conenience. You should take it up in the appropriate repository (https://github.com/swagger-api/swagger-ui or https://github.com/Rebilly/ReDoc).

For ``swagger-ui`` you should be able to use the ``DEEP_LINKING`` setting to enable the endpoint anchors feature.
