### ISSUE TITLE
Duplicated model-names results in duplication of api-documentation

### ISSUE THREAD

**Issue by tobiasgardner** [axnsan12/drf-yasg#255]
I have a django project which includes multiple applications and in some of those, there are models which have the same name as in other applications, e.g.
- /catalog/**product** and /procurement/**product** 
- /catalog/**category** and /procurement/**category**

When accessing the API end-points directly, I do get a correct documentation of it from the django frame-work. But when accessing the swagger and redoc documentation, it seems like the "first" one is replicated, i.e.
- the documentation for /catalog/product is used also for /procurement/product and
- the documentation for /catalog/category is used also for /procurement/catalog
but in fact, the models are not the same.

![image](https://user-images.githubusercontent.com/7185907/48898466-25456f00-ee4d-11e8-8eb6-74a11a25dfd6.png)
which matches with
![image](https://user-images.githubusercontent.com/7185907/48898639-8ec57d80-ee4d-11e8-8cd5-beff11d06715.png)

but looking at this, it matches with the first screenshot above
![image](https://user-images.githubusercontent.com/7185907/48898547-51f98680-ee4d-11e8-80c2-8e26a6bb26d8.png)
but not with this
![image](https://user-images.githubusercontent.com/7185907/48898733-d0562880-ee4d-11e8-911a-69a77af2b266.png)

**Comment by axnsan12** [comment]
This is working as intended, rename your serializer using ref_name (search the docs for that).

**Comment by tobiasgardner** [comment]
Thanks for the clarification!
