### ISSUE TITLE
collectionFormat=multi is missing for MultiChoiceFields

### ISSUE THREAD

**Issue by oselz** [axnsan12/drf-yasg#257]
drf uses multiple parameter instances for passing multiple fields on query parameters (of the form ?param=one&param=two); however the swagger spec defaults to csv for multiple parameters (https://swagger.io/docs/specification/2-0/describing-parameters/#array).

drf-yasg needs to insert 'collectionFormat=multi' onto the parameter schema to correctly describe the format. eg.
```
"parameters": [{
  "name": "myparam",
  "in": "query",
  "type": "array",
  "collectionFormat": "multi",
  "items": {
    "type": "string",
    "enum": [
      "item1",
      "item2"
    ]
  },
},]
```
At present this means that selecting multiple values in swagger-ui for a field defined as a MultipleChoiceField doesn't work as the ui generates csv queries, which don't work in drf.

I'm not exactly sure how to fix this correctly in drf-yasg as it is dependent on parameter type (formData and query only).  I brute forced it for now which solved my problem, but it's not ideal.  Suggestions?

**Comment by oselz** [comment]
Impressive turnaround, thank you.

**Comment by axnsan12** [comment]
Looking at past issues, you would likely notice that this is more of an exception rather than a rule 😄
