### ISSUE TITLE
Detect ChoiceField type based on choices

### ISSUE THREAD

**Issue by mofr** [axnsan12/drf-yasg#260]
### Background
According to DRF documentation and source code, `ChoiceField` class supports different values types.
`ChoiceFieldInspector` considers ChoiceField to be of string type in all cases (except ModelSerializer case).

### Goal
Detect field type based on provided choices types.
When all choices are integers, set swagger type to "integer", otherwise use "string".

### Open questions

1. Are there any other types which can be automatically inferred?

**Comment by axnsan12** [comment]
> Are there any other types which can be automatically inferred?

Currently the type is inferred from the type of the associated model field, if any.

You suggestion could also work, but, being based on a heuristic, should be imolemented to err on the side of caution against false positives.

**Comment by mofr** [comment]
I also want to improve the function to work with nested types, like `List[str]`. What is better works for you - two separate pull requests or a single one?

**Comment by axnsan12** [comment]
Whatever works for you :smile:
