### ISSUE TITLE
Nullable previous and next fields in responses

### ISSUE THREAD

**Issue by danizen** [axnsan12/drf-yasg#263]
I have a ModelViewSet with a list operation, accordingly, the generated schema is helpful, but doesn't allow None for next and previous.   However, that is exactly what is produced for a short list.

So, my unit tests fail for schema validation with the jsonschema package.    It seems like a high bar, but I wanted to capture it.   I'll try moving to swagger-parser which lies on top of jsonschema, and see if it validates any better.

```json
{ "responses": {
    "200": {
      "description": "",
      "schema": {
        "type": "object",
        "properties": {
          "next": {
            "type": "string",
            "format": "uri"
          },
          "results": {
            "type": "array",
            "items": {
              "$ref": "#/definitions/SerialUI"
            }
          },
          "count": {
            "type": "integer"
          },
          "previous": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "count",
          "results"
        ]
      }
    }
  }
}
```

**Comment by danizen** [comment]
Related google groups post illustrating that the issue is pretty sticky:

[https://groups.google.com/forum/#!msg/jsonschema/mD6GDca4zN8/xy6v6sJoDAAJ](https://groups.google.com/forum/#!msg/jsonschema/mD6GDca4zN8/xy6v6sJoDAAJ)

**Comment by danizen** [comment]
So, swagger-parser doesn't validate request responses like this well.   You can ask it to validate a definition, such as a reference to "SerialUI", but not a schema that includes a reference.   Ah, well.   Back to jsonschema.

**Comment by axnsan12** [comment]
How would your target OpenAPI document look? As far as I know null is not supported by the 2.0 version of the spec, and neither is oneOf.

**Comment by danizen** [comment]
@axnsan12, good point.

I think keeping Swagger UI and ReDoc happy is more important than supporting test validation.   This is just Postel's Law.

At the least, keep this issue in mind if/when you move to OpenAPI 3.0

Before thinking about the renderers, and the fact that you are also thinking about API Gateways/Managers and so on, I would have thought one of the following would work:


```javascript
"previous": {
   "type": [ "string", "null" ],
   "format": "uri"
}
```

Or:

```javascript
"previous": {
   "oneOf": [{ "type": "string", "format": "uri"}, {"type": "null"}]
}
```

It depends how strict they are.

**Comment by danizen** [comment]
Anyway, doing the schema validation at all was a good exercise - I have a 16 year old database, and some fields I modeled as SlugField can contain arbitrary character data.  Since my API is a read-only API, I have no reason not to simply change to CharField on the Django level.

**Comment by danizen** [comment]
OK - there is a work-around using jsonschema that isn't too bad, but the documentation doesn't make it clear that this will work:

```python
validator = Draft3Validator(swagger_spec, types={'string': (str, type(None))})
validator.validate(response_json, schema_from_spec)
```

**Comment by danizen** [comment]
Here's what I envision with the present version of the software, now that I've updated to drf-yasg 1.11.1 for another issue:

```javascript
{"previous": {
   "type": "string",
   "format": "uri",
   "x-nullable": true
}}
```

**Comment by danizen** [comment]
Also, I did manage to customize jsonschema so that I can validate my responses.
