### ISSUE TITLE
Title now being the first paragraph of the docstring of a view creates issues with existing packages

### ISSUE THREAD

**Issue by chpmrc** [axnsan12/drf-yasg#265]
For example rest_auth provides a series of endpoints for authentication (login, signup, password reset etc.). Unfortunately the first paragraph of most of their docstrings are not what you'd use as a title, for example: https://github.com/Tivix/django-rest-auth/blob/master/rest_auth/views.py#L157 .

This creates some problems as you can see here: 

![](https://cl.ly/be9cd4f15089/Image%202018-12-04%20at%209.49.32%20PM.png)

Is there a way to tell drf-yasg to skip certain namespaces/routes when it comes to generating the title for the views?

Alternatively if you could point me in the right direction I could work on a patch. Thanks!

**Comment by axnsan12** [comment]
I'd say this could be treated as a bug, since we should probably never emit a summary with an empty description. I'll try to make it more robust.

**Comment by axnsan12** [comment]
Hello again,

Having though more about this I would say the behaviour here is correct. The first paragraph is not presented as a "title", but as a summary, and it is the ReDoc client that uses this summary field in a label capacity. I opened a relevant issue there: https://github.com/Rebilly/ReDoc/issues/753

The next version will also have a simple way to turn off the summary behaviour (eeb1bba9e797adb3ef15e15463e5d79caa86194f).

**Comment by chpmrc** [comment]
Yeah I think having the ability to just turn it off should be more than enough. Not really a bug per se, just something that should be optional. Thanks!

**Comment by axnsan12** [comment]
With the (upcoming) 1.12 version, you can easily turn this off via:

```python
class MySwaggerSchema(SwaggerAutoSchema):
    def split_summary_from_description(self, description):
        return None, description
```

If the ReDoc issue goes anywhere, it may become possible to turn it of from that side, too.
