### ISSUE TITLE
Post not correctly curled.

### ISSUE THREAD

**Issue by proy87** [axnsan12/drf-yasg#270]
When clicking "try it out!" in one of my GET Endpoints the curl says:
`curl -X POST "http://localhost:8000/users/login/" -H "accept: application/json" -H "Content-Type: application/json" -H "X-CSRFToken: HXLh7fq5OveeAZJdUJHm6fXYoMbtgcoI0PnwY3AZBuyye5yWMqPG9fr9AQvwBshD" -d "username=a&password=v"`

This is not correct, since `username=a&password=v` is not a json format.

@method_decorator(name='post',
                  decorator=swagger_auto_schema(operation_description="Logins a user and returns a token",
                                                manual_parameters=[
                                                    openapi.Parameter(
                                                        "username",
                                                        openapi.IN_FORM,
                                                        required=True,
                                                        type=openapi.TYPE_STRING,
                                                        description="Valid username or email for authentication"
                                                    ),
                                                    openapi.Parameter(
                                                        "password",
                                                        openapi.IN_FORM,
                                                        required=True,
                                                        type=openapi.TYPE_STRING,
                                                        description="Valid password for authentication",
                                                    ),
                                                ])

**Comment by axnsan12** [comment]
Why would you expect form parameters to be sent as JSON?

**Comment by proy87** [comment]
@axnsan12 "Content-Type: application/json".
And `curl -X POST "http://localhost:8000/users/login/" -H "accept: application/json" -H "Content-Type: application/json" -H "X-CSRFToken: HXLh7fq5OveeAZJdUJHm6fXYoMbtgcoI0PnwY3AZBuyye5yWMqPG9fr9AQvwBshD" -d "username=a&password=v"` raises 400 error.

**Comment by axnsan12** [comment]
Oh, I see now. Well, this is odd, the combination of form parameters with json ``consumes`` should not happen normally.

Would you be able to share a complete view declaration which manifests this?

**Comment by proy87** [comment]
class CustomObtainAuthToken(ObtainAuthToken):
    throttle_classes = api_settings.DEFAULT_THROTTLE_CLASSES

**Comment by axnsan12** [comment]
I'm sorry but that is not complete, I need something I can run to debug the problem.

**Comment by proy87** [comment]
Why is it not complete?
from rest_framework.settings import api_settings
from rest_framework.authtoken.views import ObtainAuthToken

**Comment by proy87** [comment]
drf_yasg.errors.SwaggerGenerationError: cannot add form parameters when the request has a request body; did you forget to set an appropriate parser class on the view?

What class should I add to make this working?

**Comment by axnsan12** [comment]
You should either set ``parser_classes = (MultiPartParser,)`` to make the request accept only form parameters, or add your custom parameters as an ``openapi.Schema`` object in ``request_body``.

**Comment by proy87** [comment]
"Add your custom parameters as an openapi.Schema object in request_body." Can you show a minimal example?
