### ISSUE TITLE
Provide a way to statically add references to manually declared objects

### ISSUE THREAD

**Issue by mpwang** [axnsan12/drf-yasg#271]
I try to document an api, it's response has a $ref as schema, also has headers.

sth. like below. 

```
200:
  description: Success
  headers:
    X-RateLimit-Limit:
      type: integer
      description: Request limit per hour.
  schema:
    $ref: "#/definitions/User"
```

I know how to construct `openapi.Response(schema=SomeSchema, headers={...})`, but it seems there is no way to specify a SchemaRef response with headers currently.

Inside openapi._Ref 
```python
def __setitem__(self, key, value):
    if key == "$ref":
        return super(_Ref, self).__setitem__(key, value)
    raise NotImplementedError("Only $ref can be set on Reference objects (not %s)" % key)
```

Is there any workaround ? or should we  loosen the restriction of setitem on  _Ref object a little bit, can we directly set headers on _Ref object?

```python
ref: SchemaRef = ...
ref["headers"] = { 
    "X-RateLimit-Limit": {
        "decsription": "...",
        "type": "string"
    }
}
```

**Comment by axnsan12** [comment]
The issue is not that you can't set attributes on ref objects, but that there's (currently) no way to declaratively create a ref to a hardcoded value. 

Also, you would need to set the `headers` field on the `Response` object, not on its `schema`.

**Comment by axnsan12** [comment]
You could do it as explained in #211.
