### ISSUE TITLE
inconsistent behavior after version1.10.2 

### ISSUE THREAD

**Issue by lipmanp** [axnsan12/drf-yasg#274]
prior releases from 1.7.0 until 1.10.2, there would be  a HTTP header for basic authentication when specify oauth2 with client id and client secret.
**Authorization: Basic TXlDbGllbnRJZDpNeVBhc3N3b3Jk**
however it will be disappear after version 1.10.2.
I'm using the below authentication setting:
```json
SWAGGER_SETTINGS = {
    "USE_SESSION_AUTH": False,
    'SECURITY_DEFINITIONS': {
        'My token Auth': {
            'type': 'oauth2',
            'authorizationUrl': OAUTH2_AUTHORIZE_URL,
            'tokenUrl': OAUTH2_TOKEN_URL,
            'flow': 'password'
        }
    },
    'OAUTH2_CONFIG': {
        'clientId': 'MyClientId':,
        'clientSecret': 'MyPassword',
        'appName': 'MyApp',
    }
}
```

**Comment by axnsan12** [comment]
I tried to reproduce this and failed.

I added a mock oauth provider to the test project (https://drf-yasg-master.herokuapp.com/cached/swagger/), and after logging in with the oauth scheme the token is correctly sent to all endpoints with a closed lock (i.e. those whose security requirements are satisfied by the scheme).

```
curl -X POST "https://drf-yasg-master.herokuapp.com/people/" -H  "accept: application/json" -H  "authorization: Bearer XSMN8DcWRT2aDasIDbQb7gfeUkdMuc" -H  "Content-Type: application/json" -H  "X-CSRFToken: nDj04UWYLfUmkkYKBJM6axXUBSCVvCvWNn4CHPxz0nQtCnHZgeBK6qJVlnO2HMr7" -d "{  \"identity\": {    \"first_name\": \"string\",    \"last_name\": \"string\"  }}"```

**Comment by lipmanp** [comment]
Hi @axnsan12 ,
what is the drf-yasg version being used in (https://drf-yasg-master.herokuapp.com/cached/swagger/)?
it is working fine in my project with version 1.10.2. but failed with version 1.11.x

**Comment by axnsan12** [comment]
It automatically deploys the latest version on ``master``.

**Comment by axnsan12** [comment]
Does the swagger.json show any differences between the two versions? Does your browser console print any errors?

**Comment by axnsan12** [comment]
Closing for lack of info. Feel free to reopen as appropriate.
