### ISSUE TITLE
Questions re: DRF renderer_classes

### ISSUE THREAD

**Issue by beaugunderson** [axnsan12/drf-yasg#28]
We use [djangorestframework-camel-case](https://github.com/vbabiy/djangorestframework-camel-case) and set our views' `renderer_classes` to `CamelCaseJSONRenderer`.

Because of this our Swagger/OpenAPI output differs from the actual output; a field specified as `staff_member` is represented as `staffMember` in the view output but incorrectly as `staff_member` in the Swagger output.

What's the best way to remedy this, and are you interested in remedying it within this project? (If not, I could always post-process the output myself).

**Comment by axnsan12** [comment]
Hello,

I have also been thinking about custom renderers and `CamelCaseJSONRenderer` specifically, and I haven't yet found a clean way to handle them. I do however think that camel cased input/output is a useful and common enough case that it would be worth providing a built-in integration.

I will look into this for 1.1.

**Comment by axnsan12** [comment]
Implemented in #30.

Should work in 1.1.0 which is now on pypi.
