### ISSUE TITLE
flex is not maintained anymore

### ISSUE THREAD

**Issue by blueyed** [axnsan12/drf-yasg#285]
https://github.com/pipermerriam/flex/commit/b94c2d57d0ee85eb00a9b4d341fd7fbf6b01c1de

It should probably get removed from the README, `extras_require[validation]` etc?

**Comment by axnsan12** [comment]
Thanks for the notice.

**Comment by blueyed** [comment]
You're welcome!
Just stumbled upon https://github.com/olipratt/swagger-conformance and wondered if it could be used?

**Comment by axnsan12** [comment]
That seems to be an API fuzzing tool rather than a schema validation tool.

https://github.com/pyopenapi/pyswagger (used by the lib you linked) could be interesting.

**Comment by blag** [comment]
Hi, I'm the new maintainer for flex. It's now maintained again. Please add it back.
