### ISSUE TITLE
Error Parsing Schema when FileUploadParser Present

### ISSUE THREAD

**Issue by froomzy** [axnsan12/drf-yasg#288]
We have built a post where our users can upload documents. We have a manual parameter that defines the file that is uploaded:
```
DOCUMENT_UPLOAD_PARAM = openapi.Parameter(
    name="file",
    in_=openapi.IN_FORM,
    type=openapi.TYPE_FILE,
    required=True,
    description="Document data"
)
```
We define the following on the `post` method:
```
@parser_classes((FormParser, FileUploadParser, MultiPartParser,))
```

When we try to generate the schema it fails with the following error:
```
drf_yasg.errors.SwaggerGenerationError: cannot add form parameters when the request has a request body; did you forget to set an appropriate parser class on the view?
```
This is happening because the check if there are form params when there is non-form related stuff uses something that does not take into consideration the `FileUploadParser`, whose `media_type` is `*/*` [source code](https://github.com/axnsan12/drf-yasg/blob/d2cc0a348c2d9505a19e6ee7acea1e86fb63d277/src/drf_yasg/inspectors/view.py#L179)
```
if has_body_parameter or not any(is_form_media_type(encoding) for encoding in self.get_consumes()):
```

So. My issue here is that this seems to be being unnecessarily constrained. I think that we should be able to do this, and were able to in prior versions (I updated today and it changed on me). My prefered outcome would be to lossen this check back up to where it was before. Next most preferred would be to allow the `FileUploadParser` to be part of the allowed things. If neither of those are acceptable, then some guidance on how to document this setup would be appreciated.

**Comment by axnsan12** [comment]
FileUploadParser is not a form parser and thus cannot be homogeneously represented together with the other two. The correct representation for that would by a single string body parameter with binary format.

Since openapi 2 does not allow "or" we can't really do much.

The best that can be done is ignoring it in that check, since it's a default parser.
