### ISSUE TITLE
Love this project, But Hate the name 

### ISSUE THREAD

**Issue by joseph-vedadi** [axnsan12/drf-yasg#292]
The project is very nice and well maintained. 
But the name is ridiculous. Could you please name is something meaningful .. 
I know what is it stand for, but Google is not that smart yet 👎

**Comment by axnsan12** [comment]
Well, drf-openapi and django-rest-swagger were already taken at the time this project was created, so I don't know what fitting name I could have chosen while at the same time avoiding confusion between the two.

**Comment by Joojoo1020** [comment]
Thanks for your reply .. I will think about good names :)
