### ISSUE TITLE
Only show examples not the model 

### ISSUE THREAD

**Issue by joseph-vedadi** [axnsan12/drf-yasg#296]
For API Responses, how can I only show examples and not the model? 
in fact, I do not want to show any of my models definitions. 

Thanks.

**Comment by axnsan12** [comment]
The [Response object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject) can have an ``examples`` field while having an empty ``Schema``. I don't think this is possible for request bodies.
