### ISSUE TITLE
Global header

### ISSUE THREAD

**Issue by BojanKogoj** [axnsan12/drf-yasg#297]
My API requires special header to make sure application version is not too low. Any way I can add this to documentation? It applies to all endpoints, and it's not authentication. I think this is related to https://github.com/axnsan12/drf-yasg/issues/123

**Comment by axnsan12** [comment]
You could override [SchemaGenerator#get_operation](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_operation) to add a header [Parameter](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.openapi.Parameter) to all operations.

**Comment by joseph-vedadi** [comment]
Could you please example more .. 
I have : 
```
schema_view = get_schema_view(
    openapi.Info(
        title="API",
        default_version="v1",
        description="My APIS",
        contact=openapi.Contact(email="my@my.com"),
        license=None,
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    re_path("api/", include(router.urls)),
    re_path(
        r"docs/?",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    )
]
```
```
where am I supposed to call get_operation?

**Comment by Augustinio** [comment]
> You could override [SchemaGenerator#get_operation](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_operation) to add a header [Parameter](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.openapi.Parameter) to all operations.

Is it possible to get something a bit more specific? It's a very common issue. Where are you supposed to override that function? Where is that function called?

**Comment by Panter7777** [comment]
Hi, guys. here you go an example!

class CustomerGeneratorSchema(OpenAPISchemaGenerator):
    def get_operation(self, *args, **kwargs):
        operation = super().get_operation(*args, **kwargs)
        your_header = openapi.Parameter(
                name=<NAME_OF_YOUR_HEADER>,
                description="Description",
                required=True,
                in_=openapi.IN_HEADER,
                type=openapi.TYPE_STRING,
                default='<DEFAULT_VALUE>'
            )
        operation.parameters.append(your_header)
        return operation


schema_view = get_schema_view(
   openapi.Info(
      title="Some titile",
      default_version='v1',
      description="Your",
   ),
   public=True,
   permission_classes=(AllowAny, ),
   generator_class=CustomerGeneratorSchema
)

    urlpatterns += [
        # Docs for APIs
        path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    ]

**Comment by booker-h** [comment]
@Panter7777  tested your example and it is working sharp, thank you
