### ISSUE TITLE
How does NamespaceVersioning work?

### ISSUE THREAD

**Issue by Tusky** [axnsan12/drf-yasg#298]
I'm trying to create the API with namespace versioning, but according to #221 it should automatically pick it up?

I've tried adding `<string:version>` in the redoc api URL, but that doesn't seem to work, the only way I could find was to add it to patterns, but that seems like not the correct way of doing.

**Comment by Tusky** [comment]
I see, thanks for clarifying 👍 That's obvious now that you mention it.

**Comment by bulkerke** [comment]
@Tusky can you give an example of how you solved this? I'm having the same issue

**Comment by Tusky** [comment]
I had a `<project_name>/api/v1.py` and `<project_name>/api/v2.py` file.
```
app_name = 'v1'

schema_view = get_schema_view(
    openapi.Info(
        title="API",
        default_version='v1',
    ),
    public=False,
    permission_classes=[permissions.IsAdminUser],
)

urlpatterns = [
    re_path('^swagger(?P<format>.json|.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    ...rest of the v1 apis...
]
```
and both was linked in the project urls:
```
urlpatterns = [
    ...rest...
    path('api/v1/', include('<project_name>.api.v1', namespace='v1')),
    path('api/v2/', include('<project_name>.api.v2', namespace='v2')),
    ...rest...
]
```

**Comment by bulkerke** [comment]
@Tusky Thank you! url should then be: http://192.168.99.103:8000/api/v1/ ?

**Comment by Tusky** [comment]
Yeah,  whatever you desire, they just need to be separated out :)

**Comment by bulkerke** [comment]
@Tusky why do you need the:?
 path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

**Comment by Tusky** [comment]
You can add that or not, it depends on the doc style you want. If you use a custom one and you just need the scheme you need the first line only, if you use swagger the 2nd as well, if you need redoc then the third one. it's up to you what you want to have in the end.

I use a custom one, that's just the default in the drf-yasg docs which I have copied it for to describe what was I doing.

**Comment by jaydipkmn** [comment]
@axnsan12 @Tusky  Should my app name to be "v1" only ?
I am using this settings:
REST_FRAMEWORK = {
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_VERSION': 'v1',
}

and  urls for app are defined in api.urls.py as :
```
router = DefaultRouter()
# all the routers goes herer
urlpatterns = [
# additinally ulr included here
]
urlpatterns += router.urls
```

my url-conf looks like :
config/ulrs.py
```
schema_view = get_schema_view(
    openapi.Info(
        title="My API",
        default_version='v1',
    ),
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # REST web services
    re_path(r'/v1/', include('api.urls')),
    # I had to use below syntax otherwise schemas docs are not getting generated 
    # re_path(r'/v1/', include(('api.urls', 'v1'), namespace='v1')),
    re_path(r/v1/docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]
```
I hadd to inlcude "v1" in my namespace or else schemas are not getting generated.
Or i had to remove "DEFAULT_VERSION" from my settings. 
The code that is not allowing schemas to be generated is located [here](https://github.com/axnsan12/drf-yasg/blob/b99306f71c6a5779b62189df7d9c1f5ea1c794ef/src/drf_yasg/generators.py#L45)

Is there anything worng in my setup or is yasg is expecting v1 to be present in namespace ?
