### ISSUE TITLE
Add ArrayField Solution to Docs

### ISSUE THREAD

**Issue by chgad** [axnsan12/drf-yasg#303]
Hi,

i was looking for "How to implement the ArrayField(models.CharField(choices=TYPES, max_length=3))".

And the 'serializers.MultipleChoiceField()` from #102  solution worked for me. 

Could this be added to the Docs in a Section like "Tipps 'n Tricks "?

**Comment by axnsan12** [comment]
The bug in #102 is fixed. The solution of using `MultipleChoiceField` to serialize the `ArrayField` bears no relation to this library.
