### ISSUE TITLE
Read-only cannot be nullable

### ISSUE THREAD

**Issue by Geekfish** [axnsan12/drf-yasg#310]
Hello,

We have a use-case that I believe demonstrates a bug.
We will often use a ModelSerializer, so will have something like:

```python
class Foo(models.Model):
    name = models.CharField(max_length=20)
    some_attribute = models.CharField(max_length=20, null=True, blank=True)
    # ....

class FooModelSerialzer(serializers.ModelSerializer):
    class Meta:
        model = Foo
        fields ("id", "name", "some_attribute")
```

if we want to use the serializer just for output (the response body), we will often just add:

```python
        read_only_fields = fields
```

This seems to work mostly OK and no fields are marked as `required`, as expected.

However by marking the fields as read-only, **any `Nullable` annotations are lost**.

For example, above, we would expect `some_attribute` to be marked as a  **Nullable string**, but it is not.
Only if we remove it from read_only_fields then it gets marked correctly as `Nullable`.

I think that the behaviour should be that if a field is nullable, it should be marked as nullable regardless of whether it's read-only or not. The user of the API needs to know if a field may be null in the response (even if it's read-only), as well as if a field may allow submitting null values.

I'm not sure if this is a problem with the schema generation or with redoc, but I would suspect the former.

Let me know if you need more information.

**Comment by axnsan12** [comment]
I think this is indeed something that can be fixed. Will look into it.

**Comment by axnsan12** [comment]
Ok, so it turns out this is a REST Framework issue. ModelSerializer fields can never have any validation attributes besides `read_only` - https://github.com/encode/django-rest-framework/blob/31bf59708121127994bdbcd038f4f76bb28059d7/rest_framework/utils/field_mapping.py#L271-L274.

Add `extra_kwargs = { 'some_attribute': {'allow_null': True} }` to your `Meta` and it will work.

**Comment by Geekfish** [comment]
Thanks for looking into it @axnsan12 and the valuable suggestion!
