### ISSUE TITLE
Redoc authenticatuion 

### ISSUE THREAD

**Issue by balavenkatesh3322** [axnsan12/drf-yasg#311]
Hey,
Redoc not showing authenticated API documentation If I enable swagger authentication. After enabling **''REFETCH_SCHEMA_WITH_AUTH' :True,'** settings swagger authentication working fine but Redoc not showing all API.

**Comment by axnsan12** [comment]
How would you imagine that would work in redoc? It doesn't have any interactive features, and no way to enter credentials.

Cookie auth requires no special support and is the only method that would work in redoc.

**Comment by balavenkatesh3322** [comment]
Thanks for your support.
If swagger has authentication then how can i see Redoc documentation?
