### ISSUE TITLE
How to wrapping with envelope?

### ISSUE THREAD

**Issue by teamhide** [axnsan12/drf-yasg#314]
I want to wrapping response value with `data`

In my class view code like this.

```
class UserList(BaseAPIView):
    @swagger_auto_schema(responses={200: UserSerializer(many=True)})
    def get(self, request: Request) -> Union[Response, NoReturn]:
```

And response is here -> `{'user_id': 'test', 'user_pw':'123'}`

But I want to wrap it like this -> `{'data': {'user_id': 'test', 'user_pw':'123'}}`

Is there any solution here?

**Comment by axnsan12** [comment]
You can override `get_response_schema` in `SwaggerAutoSchema`.

**Comment by rsichny** [comment]
my personal preference is overriding `get_default_response_serializer`:

```
    def get_default_response_serializer(self):
        response_serializer = super().get_default_response_serializer()
        if response_serializer is not None:
            response_serializer_class = response_serializer.__class__
            response_serializer = type(
                f'Enveloped{response_serializer_class.__name__}',
                (Serializer,),
                {
                    'data': response_serializer_class(required=True)
                }
            )(context=self.view.get_serializer_context())
        return response_serializer
```

**Comment by axnsan12** [comment]
Closing this since it's a usage question. @rsichny also provided a good solution.

**Comment by davidemerritt** [comment]
Just want to add in case anyone else runs into this, anxsan12's suggestion to use `get_response_schema` is `get_response_schemas` now.

**Comment by limberger** [comment]
Hi!

My implementation:

`
    def get_response_schemas(self, response_serializers):
         """
            creates a 'data' object enveloping the response
         """
        schemas=super().get_response_schemas(response_serializers)
        if '200' in schemas:
            schema = schemas.get('200').get('schema')
            if not schema:
                print("sem schema")
            else:
                data = openapi.Schema(title='data', type=openapi.TYPE_OBJECT, 
                        properties=OrderedDict([('data',schema)]))
                d['schema'] = data

        return schemas


`
