### ISSUE TITLE
sorting elements

### ISSUE THREAD

**Issue by fenist19** [axnsan12/drf-yasg#316]
Now elements are sorted by URL. method with tag auth and url 'other' 
comes after the method with url 'next' without tag, 
How to sort the list redoc-first element with tags, sorted by tags, elements without tags are located after tags?
'other' with tag auth comes before methods without tags.

**Comment by axnsan12** [comment]
You could try to override `get_paths_object` in the schema generator, assuming redoc honours the server-side ordering of the paths.

**Comment by robertour** [comment]
Here is a `hackish` way of sorting the entries in GUI by the order that you inserted the roures in the router:

This all go in `urls.py`:

1.  Use the rest_framework routers:

```python
from rest_framework import routers
router = routers.DefaultRouter()
router.register(r'twitter'`
outer.register(r'user'`, 

...

```

2. Add this code to reinsert the routs in the appropiate order. This needs to live in `urls.py` because there is global access to the `router`:

```python
from drf_yasg import openapi
from drf_yasg.generators import OpenAPISchemaGenerator

class CustomSchemaGenerator(OpenAPISchemaGenerator):
    def get_paths_object(self, paths):
        return openapi.Paths({p: paths[p]
                     for x, _, _ in router.registry
                     for p in list(paths.keys())
                     if p.startswith(x, 1)})

```

3. Add the CustomGeneratorClass to the schema_view

```python
schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
    generator_class = CustomSchemaGenerator
)
```

**Comment by apampaluna-tije** [comment]
Hi, this method could help me to sort the endpoint's tags? i need order the methods and tags from a specific way.
if i copy this code in my urls.py file, all the endpoints disappear.
