### ISSUE TITLE
Swagger-codegen params order is changing with every update on the backend breaking the frontend

### ISSUE THREAD

**Issue by aldokkani** [axnsan12/drf-yasg#319]
When using swagger-codegen to generate typescript-angular swagger the params order is changed thus breaking my frontend application.

![screenshot_2019-02-21_14-14-15](https://user-images.githubusercontent.com/25223111/53168487-63d0fe00-35e3-11e9-99c5-fbfa262eaefe.png)

**Comment by axnsan12** [comment]
Hello!

The screenshot doesn't tell me much. Order consistency is indeed something we care about, and there are a few tests to check for that. If you found a case where the output order changes between runs on the same code, please do provide a minimal reproduction and/or a PR with tests. 😄

**Comment by aldokkani** [comment]
@axnsan12 It doesn't change between runs on the same code, but doing some modification to some endpoint all other endpoint are effected. I just commented out one endpoint, all the other endpoints are effected, the order of the params is changed.

**Comment by axnsan12** [comment]
Well, ok, I still need a way to reproduce it.

**Comment by aldokkani** [comment]
comment out an endpoint got to your url/swagger.json or wherever you name it, check the diff of the json file before and after. or use codegen typescript-angular and see untouched services change.
Will this work with you?

**Comment by axnsan12** [comment]
I deleted about half of the urls in the testproj and the rest of the endpoints remained completely unchanged on a `python testproj/manage.py generate_swagger tests/reference.json --overwrite --user admin --url http://test.local:8002/`.

**Comment by aldokkani** [comment]
@axnsan12 Here are two snippets from swagger.json after commenting out a URL of  an `APIView` not related to the mentioned `ModelViewSet` in anyhow, see how the `parameters` array order is changed:
https://gist.github.com/aldokkani/27c83bc529d7fcdee5bf312c7c9ca8e6
https://gist.github.com/aldokkani/1eec92d293dbde6cd2ab9e8875853a66

I hope you believe me this time because this matter is very important we are facing a production problem.

How do you guarantee that the params order isn't changed upon every change?
Why don't you order them by required and then alphabetically?

**Comment by axnsan12** [comment]
They are ordered by their serializer ordering, or by the `manual_parameters` order. The ordering is kept by using OrderedDict everywhere.

I'm not saying I don't believe you, I'm saying I need some code I can run to see and debug the problem.

**Comment by aldokkani** [comment]
Did you test the behavior when using Django Filters and rest framework filters?

**Comment by axnsan12** [comment]
I don't think so, no. Please do include it in your repro code.

**Comment by aldokkani** [comment]
Excuse me but what repo?

**Comment by axnsan12** [comment]
*repro*, as in (iminimal) reproduction. When you report a bug that is not eaily verifiable and reproducible by other developers, you should provide a runnable example to aid in debugging.

https://stackoverflow.com/help/mcve

**Comment by aldokkani** [comment]
It turned out to be not drf-yasg problem.
