### ISSUE TITLE
Different example for each HTTP method

### ISSUE THREAD

**Issue by AlviseSembenico** [axnsan12/drf-yasg#322]
Hi, I was wondering if it possible to provide different example for a Serializer class for any HTTP method through the `swagger_schema_fields`. Because the POST expects only a subset of the all objects field, while in the GET response all the object is serialized. 
![screenshot from 2019-02-26 10-16-39](https://user-images.githubusercontent.com/28757412/53401213-aa41a680-39af-11e9-9b51-825240f5101e.png)
The first part is related to a POST, the latter to a GET>
In the picture you can see that the id is retrieved and shown for the GET, while in the POST not. But if I remove it, the it is remove also from the second.
Thank you!

**Comment by axnsan12** [comment]
Marking the fields read_only in your serializer should do it.

**Comment by axnsan12** [comment]
The example in the sidebar is generated automatically by redoc. Not related to this library.

**Comment by axnsan12** [comment]
And if you want to manually generate it you can use the example field of the [Response object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject) together with the example field on the [Schema object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject) to provide different request/response examples.

If you want a different request example for each Operation (HTTP method), things get hairy. See #70.
