### ISSUE TITLE
Way to help/support this awesome lib

### ISSUE THREAD

**Issue by Amoki** [axnsan12/drf-yasg#323]
This lib is bigger and bigger and works very well.
@axnsan12 do a very good job and it should take him a lot of time.

My company relies on it and it seems fair to help the maintainers and the project.

Is there a Patreon or similar where we can help you? :)

**Comment by axnsan12** [comment]
Thanks for the kind words!

Money has never been a driving factor for this project, but I'm not one to turn down a sign of appreciation 😄. I've gone set up a [Buy Me a Coffee page](https://www.buymeacoffee.com/cvijdea) for any generous folks. 

There isn't a legal entity for `drf-yasg` for more formal sponsorship arrangements, so the basic donation page should do.
