### ISSUE TITLE
min_length/max_length for ListFields is not generating in schema right

### ISSUE THREAD

**Issue by AngellusMortis** [axnsan12/drf-yasg#324]
If you add `min_length` or `max_length` to a `ListField`, it generates `minLength`/`maxLength` in the output schema. It should be generating it as `minItems`/`maxItems` per [the spec](swagger.io/docs/specification/data-models/data-types/#array-length).

Steps to reproduce:
1. Set up test project
2. Add the following to some serializer (I added it to `TodoTreeSerializer`)
```
test = serializers.ListField(child=serializers.CharField(), min_length=1)
```
3. View the model in the Swagger output for that field, it should be `minItems: 1`, but is actually `minLength: 1`.

![image](https://user-images.githubusercontent.com/490848/53503249-b300ae00-3a7d-11e9-9d93-7a18b6b4a93b.png)

![image](https://user-images.githubusercontent.com/490848/53503271-bd22ac80-3a7d-11e9-868d-fd41ed04843e.png)

I tried to track this down and the best I can tell, the `ListFIeld` is not going into `get_basic_type_info` which does `find_limits` and is suppose to add the right `minItems`.

**Comment by axnsan12** [comment]
Thanks for reporting this.

**Comment by AngellusMortis** [comment]
Sweet. Does that mean we get a new release?

**Comment by axnsan12** [comment]
Yeah, I'll try to get it done today or tomorrow.
