### ISSUE TITLE
Using ReferenceResolver in custom APIView

### ISSUE THREAD

**Issue by romor** [axnsan12/drf-yasg#325]
I want to use references like `$ref: "#/definitions/MyResponse"` in the Swagger file.

My code looks like this: 

    resolver = ReferenceResolver(SCHEMA_DEFINITIONS)
    resolver.with_scope(SCHEMA_DEFINITIONS).set(
        'MyResponse', Schema(type=TYPE_STRING)
    )

And the view decorator:

    @swagger_auto_schema(
        responses = {200: Response('response description', SchemaRef(resolver, 'MyResponse'))},
    )

As a result, the path object itself gets described correctly including the `$ref` reference, but the `definitions:` section in the Swagger file keeps empty and does not list `MyResponse` there, yielding an illegal Swagger file.

Is this an issue in the library or did I use it in a wrong way?

This may be related to #211?

Something more: 
The code example given in the Documentation at `ReferenceResolver` did not answer this and also seems to be syntactical wrong here: `definitions = ReferenceResolver.with_scope('definitions')`

**Comment by axnsan12** [comment]
You are right, this is most certainly not what you want. There isn't currently a simple way to add a reference objectat "compile time" - as said in #211, you'll have to do it dynamically.

**Comment by romor** [comment]
Thanks for the feedback. Let me tell you why this is needed for me:
Some Swagger code generators (at least TypeScript fetch, what I am using) use the definition settings to automatically create data types (or Interfaces, in TypeScript).

**Comment by axnsan12** [comment]
I'm aware of that. You'll just have to insert the referene in code that runs at request time (`SwaggerAutoSchema`, inspectors, views, etc) instead of with a decorator at initialization time.

**Comment by timothyjlaurent** [comment]
I'd love a more fleshed out version of this approach.

**Comment by helloanh** [comment]
What do you mean by dynamically adding this?  Is there an example somewhere?
