### ISSUE TITLE
X taggroups

### ISSUE THREAD

**Issue by josephbiko** [axnsan12/drf-yasg#326]
I would like to set custom tags for views, and add them to their own taggroups, but I cannot find anything in the docs about this, how would I go about this?

**Comment by axnsan12** [comment]
> add them to their own taggroups,

I don't know what this means, but I'll assume it's some vendor extension. The docs cover how to set attributes at most levels of OpenAPI objects. OpenAPI structure is out of scope for this project, it's covered very well in https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

For tags specifically, you would probably want to modify `Operation` objects by subclassing `SwaggerAutoSchema`.

**Comment by anmola31** [comment]
@josephbiko Did you get the solution, how to do this?

**Comment by moritztk** [comment]
I am also interested.

**Comment by josephbiko** [comment]
Well, I've written a lot of custom code that deals with this. I can send it if you want, but it's rather specific

**Comment by TauPan** [comment]
There's an example here: https://github.com/Redocly/redoc/issues/1178#issuecomment-593988169 which works for me (my solution is also specific to the app... a generic solution would require more work).
