### ISSUE TITLE
[Question] Not generating response schema

### ISSUE THREAD

**Issue by mscansian** [axnsan12/drf-yasg#329]
Hello guys, I'm implementing a REST endpoint that provides an "action" (it uses POST, but it's not really a resource creation). The client sends a POST request (no parameters required) and the endpoint returns `my_foo` and `my_bar` values as JSON.

The API works perfectly, I've tested myself and it correctly returns the data it should. My issue is when generating the documentation using drf_yasg.

Even though the endpoint is present in the documentation, for some reason, the Response Schema is not being generated. In the Responses section it just shows `201 Created` (which is correct), but it doesn't provide any response schema (it should be `my_foo` and `my_bar`).

Below is some pseudo-code of what my implementation looks like. I'm using DRF generic `CreateAPIView`. So, what am I'm missing?

```
class MyView(CreateAPIView):
    serializer_class = MySerializer

    def get_serializer(self, *args, **kwargs):
        return super().get_serializer(instance=self.get_object(), *args, **kwargs)

    def get_queryset(self):
        return MyModel.objects.filter(foobar=my_complex_filter)


class MySerializer(serializers.Serializer):
    my_foo = serializers.IntegerField(source='id', read_only=True)
    my_bar = serializers.SerializerMethodField(read_only=True)

    class Meta:
        fields = ('my_foo', 'my_bar')

    def get_my_bar(self, obj):
        # Return some complex data

    def save(self):
        # Do something with the instance
        self.instance.save()
```

**Comment by axnsan12** [comment]
You are using `get_object` in your `get_serializer` method. This won't work when generating the openapi schema. This should also have been logged to the server's output.

See also #333.

**Comment by Dana299** [comment]
> You are using `get_object` in your `get_serializer` method. This won't work when generating the openapi schema. This should also have been logged to the server's output.
> 
> See also #333.

Are there any ways to solve it for now? It seems to me that adding huge @swagger_auto_schema decorator to my actions in ViewSet is not a good idea.
