### ISSUE TITLE
Schema generation HTTPresponse

### ISSUE THREAD

**Issue by josephbiko** [axnsan12/drf-yasg#330]
I have a view that returns a httpresponse with a file.
    
    def retrieve_file(self,request,*args,**kwargs):      
            media =self.get_object()
            response = HttpResponse()
            response['Content-Type'] = media.mime_type
            response['X-Accel-Redirect'] = media.file.path
            response['Content-Disposition'] = f'form-data; name="{media.filename}";filename="{media.filename}"'
            return response

As this is not using a serializer,  and auto_schema does not support httpresponses, how do I generate a schema for this?

Kind regards

**Comment by axnsan12** [comment]
This is not possible. Use a serializer or annotate with `response_body` or `manual_parameters`.
