### ISSUE TITLE
CI failing on pull request

### ISSUE THREAD

**Issue by parander** [axnsan12/drf-yasg#338]
Trying to do a pull request for a minor patch i did to is_list_view, however the CI fails on 3 test cases both before and after my patch (python version >=3.6). CI seems to work on python version 3.5 though (both before and after the patch) but i guess all of them must pass for me to be able to submit the pull req?

Any suggestions on how to proceed?

Btw my wild guess is that the 3.5 vs 3.6 difference is due to "PEP 468: Preserving Keyword Argument Order" which was fixed in 3.6.

**Comment by axnsan12** [comment]
Seems to have fixed itself. Thanks for the report.
