### ISSUE TITLE
[question] Add `fields` parameter

### ISSUE THREAD

**Issue by lorddaedra** [axnsan12/drf-yasg#339]
I would like to use serializers with dynamically modifying fields with all my ViewSets list methods. Example: `?fields=field1,field2,field3`
https://www.django-rest-framework.org/api-guide/serializers/#dynamically-modifying-fields

I need swagger schema to generate clients.

How to do that? Can you explain and may be show ViewSet mixin with example code...

Not such good but possible workarounds which I see
1. I use django-filter and can create dummy filter for fields if needed. it will solve problem `how to add parameter to swagger.json/yaml` but add new problem `how to make fake filter`
2. I can also parse and patch your swagger.json/yaml and create some custom view with my customized swagger.json/yaml

**Comment by axnsan12** [comment]
If you just need to add a query parameter, you can use `swagger_auto_schema` with `manual_parameters`. To achieve csv [you can use `collection_format='csv'`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object).
