### ISSUE TITLE
Serpy serializer

### ISSUE THREAD

**Issue by AndreaFox93** [axnsan12/drf-yasg#341]
Hi, i'm using other serializers like Serpy and almost everything works but i get an error when trying to load the swagger page:

drf_yasg/inspectors/base.py", line 212, in _get_partial_types
'Serializer' object has no attribute 'help_text'

Of course the problem is that i'm not using the DRF serializer that has the help_text attribute, that project it's really a masterpiece with django.

To address the issue may the code can be improved like this:

**Before**
`
description = force_real_str(field.help_text) if field.help_text else None
`

**After**

`
help_text = getattr(field, 'help_text', None)
description = force_real_str(help_text) if help_text else None
`

For now i'm subclassing the _serpy.Serializer_ adding the help_text attribute

Thanks

**Comment by axnsan12** [comment]
Fixed with #342
