### ISSUE TITLE
Fix request: Generate JSONField to `object`, not to `string` by default

### ISSUE THREAD

**Issue by symonsoft** [axnsan12/drf-yasg#345]
In case of using JSONField in serializer currently the type `string` is generated in swagger schema for corresponding field. And after client generation it makes weird transformation parsed JSON to string which can be converted back with `eval` (which is potentially dangerous).

Using `object` instead of `string` would be more correct.

**Comment by axnsan12** [comment]
> Using object instead of string would be more correct.

The JSONField can hold any JSON type, including object, array, string, float, book, etc. There is no OpenAPI construct to represent this accurately so I decided to just give up on that.


> And after client generation it makes weird transformation parsed JSON to string which can be converted back with eval 


I don't understand this.

**Comment by symonsoft** [comment]
> I don't understand this.

When generated client receives the data it converts the data to string. So if any of the mentioned type arrives client converts it to string which is not expected and even more it isn't simple irreversible.

Look:
`['aaa', 'bbb']` becomes `"['aaa', 'bbb']"`,
`{'a': 1, 'b': 2}` becomes `"{'a': 1, 'b': 2}"`,
`1.001` becomes `"1.001"`
and so on...
There is no point in having such values. And in common case to convert it back you cannot just cast it to desired type, but need to run `eval` or something.

**Comment by symonsoft** [comment]
> There is no OpenAPI construct to represent this accurately

There is `object` type which is forcing client leave data as it parsed by JSON-parser

**Comment by axnsan12** [comment]
> it isn't simple irreversible [...] need to run eval or something

wouldn't `JSON.parse` suffice?

I can't find information about any such type: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

**Comment by symonsoft** [comment]
> wouldn't JSON.parse suffice?
No, because it isn't valid JSON. It's python object converted to string.

> I can't find information about any such type
I guess any type different from primitive is used as-is. And `object` is Python's legitimate class. Also, It is processed by generators as supposed: in case of using `object` type it leaves data as it is.

**Comment by axnsan12** [comment]
You are both right and wrong. The OpenAPI object type is used to represent JSON *objects*, that is, key-value mappings. The fact that lists and primitves extend the "object" type in many languages makes this work in some cases, but it is not correct.

In JSON/JSON Schema/OpenAPI an int, float, etc is *not* an object.

**Comment by symonsoft** [comment]
I suspect that is silently supported. Otherwise, how can that be explained that there is special handling for `object` type in generated Python and Javascript clients?

> In JSON/JSON Schema/OpenAPI an int, float, etc is not an object.

I guess any valid sub-JSON (dict, list) can be treated as an object.
