### ISSUE TITLE
Code samples for curl in Redoc UI

### ISSUE THREAD

**Issue by timur-orudzhov** [axnsan12/drf-yasg#356]
Redoc has feature that code samples, ability to write examples of code to accomplish request. I think, i would be great, if that feature will be integrated or some examples will be provided in the docs and, i think, **curl** is a great candidate to be included in redoc ui.

<img width="566" alt="Screenshot 2019-04-30 at 11 15 51" src="https://user-images.githubusercontent.com/3646772/56948804-ee7d2e80-6b39-11e9-9fa2-40652708de47.png">

**Comment by axnsan12** [comment]
You should probably open this issue on the Redoc tracker, not here. https://github.com/Redocly/redoc/
