### ISSUE TITLE
Parameters should use description instead of title

### ISSUE THREAD

**Issue by fazpu** [axnsan12/drf-yasg#36]
The drf-yasg generates object definitions, where the parameters use "title" attribute (example shown below). I believe this goes against the [swagger v2 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject) and it should be called "description" instead.

```
"Login": {
      "required": [
        "password"
      ],
      "type": "object",
      "properties": {
        "username": {
          "title": "Username",
          "type": "string"
        },
        "email": {
          "title": "Email",
          "type": "string",
          "format": "email"
        },
        "password": {
          "title": "Password",
          "type": "string"
        }
      }
    },
```

**Comment by axnsan12** [comment]
Hello,

That is actually a [Schema object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject), whose properties can have both title and description. The title is taken from the `label` attribute on serializers fields, and I believe is appropriate. 

If you want a description you have to set the fields' `help_text`.

**Comment by fazpu** [comment]
Thank you.
