### ISSUE TITLE
How to change language the swagger shows?

### ISSUE THREAD

**Issue by 244462375** [axnsan12/drf-yasg#360]
I can't find an option which can change the language of swagger on documentation. How can I do that?

**Comment by axnsan12** [comment]
I'm not sure which language you speak of. The language of code samples is determined by `swagger-ui`/`redoc`. The language of the UI is likewise implemented in the corresponding UI project.

The language of the strings in the swagger JSON document is out of the scope of `drf-yasg`, and you should look into Django translation support.
