### ISSUE TITLE
Generate response content type for file attachment

### ISSUE THREAD

**Issue by conversica-markrodriguez** [axnsan12/drf-yasg#366]
I tried the following but the `Response content type` is still `application/json`. I would like to have it as `application/octet-stream` - thanks

    @swagger_auto_schema(
        query_serializer=DocumentQuerySerializer,
        responses={
            '200': openapi.Response('File Attachment', schema=openapi.Schema(type=openapi.TYPE_FILE)),
            '400': 'Bad Request',
            '401': 'Not Authorized',
            '404': 'Not Found'
        },
        produces='application/octet-stream',
        operation_id='Retrieve a Document',
        operation_description='GET server:PORT/documentstore/docs?id=string'
    )
    def get(self, request, *args, **kwargs):
...

**Comment by conversica-markrodriguez** [comment]
> I tried the following but the `Response content type` is still `application/json`. I would like to have it as `application/octet-stream` - thanks
> 
> ```
> @swagger_auto_schema(
>     query_serializer=DocumentQuerySerializer,
>     responses={
>         '200': openapi.Response('File Attachment', schema=openapi.Schema(type=openapi.TYPE_FILE)),
>         '400': 'Bad Request',
>         '401': 'Not Authorized',
>         '404': 'Not Found'
>     },
>     produces='application/octet-stream',
>     operation_id='Retrieve a Document',
>     operation_description='GET server:PORT/documentstore/docs?id=string'
> )
> def get(self, request, *args, **kwargs):
> ```
> 
> ...

I got to work by using a custom `SwaggerAutoSchema` subclass and over-ridding `get_produces`.

**Comment by axnsan12** [comment]
Glad you worked it out!
