### ISSUE TITLE
Add DRF Token Auth to swagger

### ISSUE THREAD

**Issue by nixphix** [axnsan12/drf-yasg#367]
How to add DRF [token auth](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) to swagger docs? It is not clear in the [document](https://drf-yasg.readthedocs.io/en/stable/security.html) as to how it should be declared.

**Comment by axnsan12** [comment]
```python
   SWAGGER_SETTINGS = {
      'SECURITY_DEFINITIONS': {
         'DRF Token': {
               'type': 'apiKey',
               'name': 'Authorization',
               'in': 'header'
         }
      }
   }
```

should be enough. You'll have to manually add the `Token` prefix (or whatever you set) to the token input in `swagger-ui`.

**Comment by rafa-acioly** [comment]
@axnsan12 the class `TokenAuthentication` from drf already use the `Token` prefix so it shouldn't be used as default on drf-yasg?
Is there anything in the docs that show how to add the `token` prefix to the ui input?

**Comment by labohkip81** [comment]
Add  to your settings:
```python 
   SWAGGER_SETTINGS = {
      'SECURITY_DEFINITIONS': {
         'DRF Token': {
               'type': 'apiKey',
               'name': 'Authorization',
               'in': 'header'
         }
      }
   }
```
Then from the ui add:
``` Bearer <YOUR-TOKEN-WXWXWXWX>```

**Comment by matiasAS** [comment]
Hello @labohkip81 , It does not work for me. In my case I use Token <token>, not Bearer

**Comment by ozkit** [comment]
I also have this issue when working with django-rest-knox
