### ISSUE TITLE
Python 3.4 is no longer supported 

### ISSUE THREAD

**Issue by michael-iden** [axnsan12/drf-yasg#368]
Hi @axnsan12, 
We have discovered that 3.4 is no longer supported because a dependency has dropped their 3.4 wheel. The requirement in question is [ruamel.yaml>=0.15.34](https://github.com/axnsan12/drf-yasg/blob/master/requirements/base.txt#L3) but the [0.15.95](https://pypi.org/project/ruamel.yaml/0.15.95/) version of this dependency released today throws an error on installation in a 3.4 environment

We were able to explicitly define `ruamel.yaml==0.15.94` to build our applications without issue but we understand if python 3.4 support is ready to be dropped and we just need to call that out in the documentation. 

Thanks!

**Comment by axnsan12** [comment]
Python 3.4 support will be dropped in the next release. Thanks!
