### ISSUE TITLE
readOnly on SchemaRef 

### ISSUE THREAD

**Issue by luxcem** [axnsan12/drf-yasg#369]
Let say I have a nested serializer like this:

```python
class AccountSerializer(Serializer):
    name = CharField()

class PostSerializer(Serializer):
    title = CharField()
    account = AccountSerializer(read_only=True)
```

The corresponding Schema generated for account field in Post is `SchemaRef([('$ref', '#/definitions/Account')])` but the "read_only=True" is lost. 

How can I keep the readOnly attribute with nested serializer?

**Comment by SrdjanCosicPrica** [comment]
Duplicate #343
