### ISSUE TITLE
Urls not correctly "currled"

### ISSUE THREAD

**Issue by chgad** [axnsan12/drf-yasg#37]
Hi,

i encountered the following:

when clicking "try it out!" in one of my GET Endpoints the curl prompt beneath it states a wrong statement :`curl -X GET "localhost://localhost:8000/api/myendpoint/(P101[0-9]+)" -H  "accept: application/json" -H  "X-CSRFToken: x4bdC0d9Chl2ZThQEpJCi1WzadO0NTIPVa5FXSqkIRvjJ9xvJvBzvZWZLvQ3viDC"`

This is obviously a wrong behavior. The correct, and succesfull, curl should look like this : 
`curl -X GET "localhost:8000/api/myendpoint/101" -H  "accept: application/json" -H  "X-CSRFToken: x4bdC0d9Chl2ZThQEpJCi1WzadO0NTIPVa5FXSqkIRvjJ9xvJvBzvZWZLvQ3viDC"`

my urls.py looks like this : 

`[...]
url(r'^myendpoint/(?P<pk>[0-9]+)', myendpoint.as_view)
[...]
`
This might be an "localhost" problem (I can not validate the issue for the production system, docs aren't online till now) , but still shouldn't ouccur.

**Comment by axnsan12** [comment]
Hello @chgad,

Does the "try it out" function work from the web UI? (I.e. is it just the curl URL which has problems?)

I tried, but can't manage to reproduce the issue. What python/rest-framework/Django versions are you using? Can you provide the generated swagger.yaml or .json spec for your api, or a minimal example which exhibits the issue?

Thanks.

**Comment by chgad** [comment]
Hi,

im running django 1.11.7 ,drf 3.7.7 on a python version 3.6.2.

![swagger_wrong_curl](https://user-images.githubusercontent.com/21121667/34650958-c4fd4ee8-f3c9-11e7-981a-0c1f928dfff5.png)

This is a screenshot of the wrong behavior. Im not sure what your saying about the .json/.yaml spec ? hwo would this help ?

**Comment by axnsan12** [comment]
I'm trying to figure out what happens, as I said, I can't manage to reproduce it. The json/tank spec is the source of the documentation - you can get it by accessing <docs URL>?format=openapi, or by using schema_view.without_ui().

Back to your problem, are you by any chance using path() instead of url() for routing your urls?

Does the app itself work?

**Comment by chgad** [comment]
Ah now i got it.

here is the spec:

[e_flfA5q.txt](https://github.com/axnsan12/drf-yasg/files/1609976/e_flfA5q.txt)

Nope i'm not using path() and yes my app works just fine. I can't geive feedback about "live behavior" since the docs aren't online yet.

**Comment by axnsan12** [comment]
Also how are you instantiating the schema view, and how are you accesing it in the browser? (i.e. the full URL) - it's strange to see that it picks up `localhost` as the URL scheme.

**Comment by chgad** [comment]
I instatiate it as it's said in the "Getting started", no customization. i acces it via `localhost:8000/api/swagger`.
All Api Endpoints are nested under `api/`

**Comment by axnsan12** [comment]
Hello,

I think I have some ideas:

* your (terminal) pattern should end in $ - so `r'^myendpoint/(?P<pk>[0-9]+)$'` instead of `r'^myendpoint/(?P<pk>[0-9]+)'`
* if you are manually providing a `url` to `get_schema_view`, it should be an absolute url with protocol - `http://localhost:8000/` instead of `localhost:8000/`

**Comment by chgad** [comment]
Yeah!

The Problem was that i declared an incorrect url in the `get_schema_view`.

I declared `localhost:8000/api/` instead of , what you said, `http://localhost:8000/api/`.

This fact of an absoulute url could be stated in the docs (?). It would definetly clarify it abit to prevent further Problems with the url.

Thanks for the fast and coninuous help.
I close this Issue for now.

**Comment by axnsan12** [comment]
Re-opening to remember to improve handling of this.
