### ISSUE TITLE
Add support for custom Pagination

### ISSUE THREAD

**Issue by gyukebox** [axnsan12/drf-yasg#373]
I have been writing my API docs using this library, and encountered situations like this:  
I customized my api pagination scheme like this:
```json
{
  "count": 0,
  "data": [
    {}
  ],
  "paging": {
    "previous": "http://example.com",
    "next": "http://example.com",
  }
}
```
However, the auto-generated response scheme rendered as:
```json
{
  "count": 0,
  "next": "http://example.com",
  "previous": "http://example.com",
  "results": [
    {}
  ]
}
```

Is there a way to make api response scheme to render with custom pagination format, or any plan to make it happen?

**Comment by axnsan12** [comment]
You should implement and use a custom `PaginatorInspector`.
