### ISSUE TITLE
Exclude post method and operation description not working

### ISSUE THREAD

**Issue by daveyu1975** [axnsan12/drf-yasg#377]
code as follows
method_decorator(name='create', decorator=swagger_auto_schema(auto_schema=None))
method_decorator(name='list', decorator=swagger_auto_schema(operation_description="GET /dashboards"))
class DashboardAPIView(ListCreateAPIView):
     queryset = Dashboards.objects.all().order_by('dash_name')
    serializer_class = DashboardSerializer

    def perform_create(self, serializer):
        sequence_no = get_next_sequence_number_test_dashboard()
        serializer.save(sequence_no=sequence_no)
Post method showing in UI

**Comment by axnsan12** [comment]
Your view is a `ListCreateAPIView` so you should decorate `post` and `get`, not `create` and `list` (which are `ViewSet` actions).
