### ISSUE TITLE
Try-it-out presenting wrong input type in swagger's UI

### ISSUE THREAD

**Issue by ColinWaddell** [axnsan12/drf-yasg#383]
Howdy - a deep dive into the documentation isn't getting me anywhere so hopefully someone can help here.

I've got a model with a lookup field generated using `hashid_field.HashidField()` as provided by the [django-hash-field](https://github.com/nshafer/django-hashid-field) library.

I've got my serializers all hooked up so this is used as the lookup field when passing data around. So far so good, from a DRF point of view everything is working as expected.

The problem is the swagger UI. This reference field is a string, however the try-it-out feature of swagger is presenting an Integer input box and rejecting any string placed in there.

Here is my model, url view and serializer. I've stripped out a lot of code but the core here still generates the same incorrect Try-it-out panel:

```
## model.py

class Schedule(models.Model):
    reference = HashidField()
    modified = models.DateTimeField(auto_now=True)


## view.py

class ScheduleAPIView(viewsets.ModelViewSet):
    queryset = models.Schedule.objects.all()
    serializer_class = serializers.ScheduleSerializer
    permission_classes = [IsAuthenticated]
    lookup_field = 'reference'
    lookup_value_regex = '[0-z]+


## serializer.py

class ScheduleSerializer(serializers.ModelSerializer):
    reference = HashidSerializerCharField(
        source_field='schedule.Schedule.reference',
        read_only=True,
    )

    url = serializers.HyperlinkedIdentityField(
        view_name='schedule:api:ScheduleObject-detail',
        lookup_field='reference'
    )

    class Meta:
        model = schedule_models.Schedule
        fields = (
            'reference',
            'url',
            'modified'
        )


## urls.py

router = routers.SimpleRouter()
router.register(
    r'schedule',
    views.ScheduleAPIView,
    base_name='ScheduleObject',
)

api_info = openapi.Info(
    title="ExpressWay Global",
    default_version='v0.1',
    description="ExpressWay Global",
)

schema_view = get_schema_view(
   api_info,
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # API Documentation
    url(
        r'^swagger/$',
        schema_view.with_ui(
            'swagger',
            cache_timeout=0
        ),
        name='schema-swagger-ui'
    ),
]
```

As you can see the `reference` field in Try-it-out only accepts integers:

![image](https://user-images.githubusercontent.com/1848325/59519797-94091900-8ec0-11e9-862e-ebc18c44a282.png)

If anyone has any clues about getting the correct field in the form there that'd be awesome.

Cheers!

**Comment by axnsan12** [comment]
The problem is that the `HashidField` extends `IntegerField` but behaves like a `CharField`. Not very OO-friendly! 

The fact that it shows as a string in the request body part is the actual bug here, or rather oversight - PK reference fields should probably look at their corresponding model field.

But I digress, to fix your issue you'll have to write a `FieldInspector` which serializes your `HashidField` to a String instead of Number.

**Comment by axnsan12** [comment]
See https://github.com/axnsan12/drf-yasg/issues/332

**Comment by ColinWaddell** [comment]
Awesome! Thanks @axnsan12  :trophy:
