### ISSUE TITLE
Rendering existing OpenAPI specifications

### ISSUE THREAD

**Issue by eamanbekov** [axnsan12/drf-yasg#393]
In our project, we have a documentation-first flow. So you have to write OpenAPI specs first and only then you can start developing that feature. That's why I don't really need a "swagger generation".

I want to specify a path to the `.yml` file or a folder containing them and serve it. Does this package have such a feature?

Thank you!

**Comment by devmonkey22** [comment]
I'm a little new to this package, but it sounds like you just want to use `swagger-ui` directly and pass it the URL or `spec` json in its swagger settings.

If you really want to use this library still, I bet you could override the `SPEC_URL` setting to point to your hand-coded openapi spec file (how painful is that?), and just tweak the renderers to use the `SwaggerUIRenderer` only via `get_swagger_view(...).with_ui(...)`

**Comment by eamanbekov** [comment]
@devmonkey22 
**Thank you for your response!**

Yeah, that's exactly what I ended up doing. I've set up `swagger-ui` according to this [tutorial](https://dev.to/matthewhegarty/swaggerui-inside-django-rest-framework-1c2p).

I tried doing it using `swagger-ui` docker image, but the references(`$ref`) to other files were not working
