### ISSUE TITLE
Schema default value not used

### ISSUE THREAD

**Issue by arkadyark** [axnsan12/drf-yasg#40]
Trying to set a default value for a Schema inside of a Parameter. It does not seem to be getting picked up in Swagger when I use the "Try it out" functionality.

My schema looks like this:

```
    @swagger_auto_schema(
            operation_id="Get a mission plan",
            responses={
                200: 'test'},
            manual_parameters=[
                openapi.Parameter(
                    name='Organization',
                    in_=openapi.IN_HEADER,
                    description="Organization name",
                    required=True,
                    schema=openapi.Schema(
                        type=openapi.TYPE_STRING,
                        default="Organization 1",
                    )
                )
            ]
        )
```

Perhaps providing a more in depth example in testproj, that uses more of the OpenApi parameters, would be helpful. From what I read [here](https://swagger.io/docs/specification/adding-examples/) it seems the example field should be used rather than default, but it does not seem to be an available field in the Schema class?

**Comment by arkadyark** [comment]
Actually, looking a bit more, it seems like putting an example parameter value for a header is not supported in OpenAPI v2 (see [this thread](https://stackoverflow.com/questions/43933516/how-to-specify-examples-for-get-parameters-in-swagger)). Then I'm eagerly awaiting [this issue](https://github.com/axnsan12/drf-yasg/issues/33) to be resolved!

**Comment by axnsan12** [comment]
Hello,

Your example is wrong because in OpenAPI 2.0, parameters can only have a `schema` attribute if they are `in: body`. Your header parameter can only have a plain `type`, and an optional `format`, `pattern`, `enum`, etc - see Parameter Object in the OpenAPI 2.0 specification.

With that said, `default` is a valid attribute for `Parameter`, so you can just move it out of the schema and it will work.

**Comment by axnsan12** [comment]
A quick read over [this](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#swagger-spec-overview) could maybe clear up a bit more stuff.

Will also look into adding more assertions against using wrong combinations of attributes like this.

**Comment by axnsan12** [comment]
Related to the OpenAPI 3 issue - as stated in its text, it won't likely be resolved in the near future (few months at least), since most 3rd party tools have no support for the interesting new features or even the 3.0 spec itself.
