### ISSUE TITLE
overridding def get_serializer_class(self): causes api params to not be displayed

### ISSUE THREAD

**Issue by daveyu1975** [axnsan12/drf-yasg#402]
if I have this

class TestsAPIView(ListCreateAPIView):

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return Serializer1
        else:
            return Serializer2

The docs for GET method does not have the request parameters displayed

**Comment by daveyu1975** [comment]
i meant response parameters

**Comment by caspervk** [comment]
You can use `if self.action == "list"` and `if self.action == "create"`.

**Comment by axnsan12** [comment]
This behaviour is tested and should be working. If it's not please provide a complete working example.
