### ISSUE TITLE
Add new method to buy author coffe

### ISSUE THREAD

**Issue by VChertukhin** [axnsan12/drf-yasg#404]
![2019-07-09](https://user-images.githubusercontent.com/17051615/60918960-3688a200-a29d-11e9-83e1-6c6066f8d538.png)
I wasn't able to buy you coffe, due to capcha bug, probably add patreon?

**Comment by axnsan12** [comment]
While I appreciate the intention, this is a relatively small project and I don't want to clutter it too much with $$ stuff.
