### ISSUE TITLE
Upgrading to DRF 3.10.0 breaks settings

### ISSUE THREAD

**Issue by mhoonjeon** [axnsan12/drf-yasg#410]
After upgrading to DRF == 3.10.0 following error message appears when trying to run server
```
ImportError: Could not import 'drf_yasg.generators.OpenAPISchemaGenerator' for API setting 'DEFAULT_GENERATOR_CLASS'. ImportError: cannot import name 'SchemaGenerator' from 're
st_framework.schemas.generators' (/Users/...../.local/share/virtualenvs/......./lib/python3.7/site-packages/rest_framework/schemas/generators.py).
```

Apparently, `SchemaGenerator` has been renamed to `BaseSchemaGenerator`, with some changes.

Adding the following lines to SWAGGER_SETTINGS in settings.py seems to work.

```
SWAGGER_SETTINGS = {
    "DEFAULT_GENERATOR_CLASS": "rest_framework.schemas.generators.BaseSchemaGenerator",
....

```

**Comment by mhoonjeon** [comment]
It seems someone is already on this issue. See [PR](https://github.com/axnsan12/drf-yasg/pull/408)

**Comment by nourwolf** [comment]
I don't think changing the setting is enough. `SchemaGenerator` wasn't just renamed. Using the `BaseSchemaGenerator` results in an error when opening the docs.

**Comment by tuky** [comment]
I would love to read a statement from @axnsan12 regarding DRF's switch to OpenAPI (https://www.django-rest-framework.org/community/3.10-announcement/). Will it make sense to continue YASG? Should we refactor it to reuse more OOB features? Will it cease to exist by integrating its exclusive features to DRF? However, thank you for this amazing project.
