### ISSUE TITLE
1.16.1 depends on packaging, but does not install it 

### ISSUE THREAD

**Issue by dkliban** [axnsan12/drf-yasg#412]
```python
from drf_yasg.generators import OpenAPISchemaGenerator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/pulp/lib64/python3.6/site-packages/drf_yasg/generators.py", line 16, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

**Comment by edison7500** [comment]
need to install packaging
```
pip install packaging
```

**Comment by ArnaudLevaufre** [comment]
The fix is implemented in commit e6219ab, one commit after the 1.16.1 release. Would it be possible to release a new bugfix version including this fix ? Anyways it will be fixed in the next release.

**Comment by dkliban** [comment]
@axnsan12 Can you please release 1.16.2 to fix this?

**Comment by hidaris** [comment]
@axnsan12 ping

**Comment by syurchenko** [comment]
please release version without packaging issue

**Comment by johnthagen** [comment]
It would be really nice to include #428 in 0.16.2 as well as that fixes a recent regression in type hint support.

**Comment by syurchenko** [comment]
It would be very nice to merge it and release new version

**Comment by axnsan12** [comment]
Hey everyone, sorry for going dark for such a long period. I'll get to cleaning up issues and releasing any needed bug fixes soon.

**Comment by johnthagen** [comment]
> sorry for going dark for such a long period

No worries! Thanks for working on this!
