### ISSUE TITLE
Add possibility to set ReDoc and Swagger UI settings

### ISSUE THREAD

**Issue by AlexandreSi** [axnsan12/drf-yasg#419]
Hi all,

First, thanks for the work you're doing on this repo!

I am currently using drf-yasg to generate a ReDoc swagger but I couldn't find a way of setting the UI settings, that you mention in the docs at https://drf-yasg.readthedocs.io/en/stable/settings.html#redoc-ui-settings.

I'd be happy to open a PR for that purpose. What do you think?

Alexandre

**Comment by Crocmagnon** [comment]
Did you try the example at the top of the page you linked ? https://drf-yasg.readthedocs.io/en/stable/settings.html#settings
=> In a dictionary named `REDOC_SETTINGS` in `settings.py` ?

**Comment by AlexandreSi** [comment]
@Crocmagnon My bad, I was specifically searching for `noAutoAuth` setting and didn't realize it was the right way to set it. In this case, I will open a short PR to:

- add the missing settings
- upgrade the redoc version to v2.0.0-rc.10

**Comment by Crocmagnon** [comment]
These seem like two different things, you might want to open two PR's 😉

**Comment by AlexandreSi** [comment]
Good idea, will do!
