### ISSUE TITLE
swagger_auto_schema strange behaviour

### ISSUE THREAD

**Issue by timur-orudzhov** [axnsan12/drf-yasg#429]
Recently I've faced with strange behaviour, when manually register views of the third party package. I'm trying to provide a custom response schema via `swagger_auto_schema` to specific view, but that schema also propagated to other views: jwt-create, jwt-refresh. Has anybody any clues what is going wrong?

```python
urlpatterns = [
    path(
        r'tokens/jwt/create/',
        simple_jwt_views.token_obtain_pair,
        name='jwt-create',
    ),
    path(
        r'tokens/jwt/refresh/',
        simple_jwt_views.token_refresh,
        name='jwt-refresh',
    ),
    path(
        r'tokens/jwt/verify/',
        swagger_auto_schema(
            method='POST',
            security=[],
            responses={'201': TokenObtainSerializer()}
        )(simple_jwt_views.token_verify),
        name='jwt-verify',
    )
]
```

**Comment by timur-orudzhov** [comment]
i've realized, that problem is enclosed in the drf-simplejwt. In that library, views are inherited from a base view class and that was cause of such weird behaviour.

**Comment by facundomedica** [comment]
How did you solve this @timur-orudzhov ?

**Comment by timur-orudzhov** [comment]
@facundomedica for those views I provided some wrapper:

```python
class TokenRefreshView(simplejwt_views.TokenRefreshView):

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)
```
