### ISSUE TITLE
Drop Python 2.7 Support

### ISSUE THREAD

**Issue by johnthagen** [axnsan12/drf-yasg#432]
As of DRF 3.10 ([3.10 Announcement](https://www.django-rest-framework.org/community/3.10-announcement/) / https://github.com/encode/django-rest-framework/pull/6615), Python 2.7 support has been dropped. `drf-yasg` can now consider dropping Python 2.7 in a future release as well.

[Python 2.7 is EOL Jan 1, 2020](https://pythonclock.org/).

[Django 2.0+ also dropped support for Python 2.7](https://docs.djangoproject.com/en/2.2/faq/install/#what-python-version-can-i-use-with-django).
- Support for Python 2.7 and Django 1.11 ends in 2020.

**Comment by johnthagen** [comment]
Related: #442

**Comment by axnsan12** [comment]
🎉

**Comment by axnsan12** [comment]
Dropped like it's hot.
