### ISSUE TITLE
"No operations defined in spec!" and wrong base path when `app_name` not defined

### ISSUE THREAD

**Issue by BielStela** [axnsan12/drf-yasg#446]
if using `get_schema_view` in  `included` URLconf modules, you need to define `app_name` variable, otherwise `get_schema_view` guesses wrong base path and fails to generate specs

**Comment by danilocastelhano1** [comment]
Can you explain with examples? i'm getting this error too, i have 3 modules, 
in these modules, i have url.py and in the root url i pass:

urlpatterns = [
    url(r'^$', schema_view_new.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view_new.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^(?P<version>(v1))/module_xxxx/', include('module_xxxx.urls')),
    url(r'^(?P<version>(v1))/module_yyyy/', include('module_yyyy.urls')),
    url(r'^(?P<version>(v1))/module_zzzz/', include('module_zzzz.urls')),
    url(r'^', include(router.urls)),
]

**Comment by BielStela** [comment]
Hello @danilocastelhano1 I don't remember exactly where I was having this issue but I think we fixed it defining a variable `app_name` in each module url.py file.

**Comment by Tammura** [comment]
@BielStela If you actually fix your issue, you can close it :)
