### ISSUE TITLE
web UI style error

### ISSUE THREAD

**Issue by zhimingzhang123** [axnsan12/drf-yasg#448]
I want to change some  notes, like search, 
<img width="400" alt="8" src="https://user-images.githubusercontent.com/31529120/64158439-0f002100-ce6b-11e9-8db4-1df6bff54452.png">

I noticed a change in style, the position of the input box has changed, of course, this is not a big problem.
If it can be solved,please help me, thanks.

**Comment by axnsan12** [comment]
This is probably best reported to swagger-ui, maybe some issue with their handling of non-latin unicode characters.
