### ISSUE TITLE
SerializerMethodField + type annotations regression

### ISSUE THREAD

**Issue by beaugunderson** [axnsan12/drf-yasg#450]
We upgraded to 1.16.1 and hit https://github.com/axnsan12/drf-yasg/issues/385 with `Optional[int]` as well as another issue with `List[int]`, which is previously unreported. Both now resolve to `string`.

I believe the open PR https://github.com/axnsan12/drf-yasg/pull/428 would fix both issues. :)

**Comment by axnsan12** [comment]
#428 is now merged
