### ISSUE TITLE
Migrating django-rest-swagger to drf-yasg issue. How to display input parameters ?

### ISSUE THREAD

**Issue by axilaris** [axnsan12/drf-yasg#453]
I am trying to migrate my API from django-rest-swagger==2.1.1 to drf-yasg

Meaning, trying to use this since I am migrating Django 1.11.7 --> 2.2
djangorestframework==3.9
drf-yasg==1.16.1

In the current code, I'ved used django-rest-swagger simply by creating the API this way: (https://gist.github.com/axilaris/92d9d2de6bdd2476cdd02fb535d9bde5 - here are more details in url.py, api.py, swagger_schema.py)

in api.py:
@api_view(['POST'])
def get_countries(request):
    # ----- YAML below for Swagger -----
    """
    description: countries list
    parameters:
      - name: token
        type: string
        required: true
        location: form   
    """
    ......
    return Response(countries_list, status=status.HTTP_200_OK)

Having now enabled 
djangorestframework==3.9
drf-yasg==1.16.1

I notice the new swagger does not have any input forms parameter like in this screenshot
https://i.imgur.com/YLYihRi.png

How can I customize drf-yasg based on my current API since I dont want to break the mobile to have that kind of documentation. It doesnt matter if its swagger or redoc ?

**Comment by littlehome-eugene** [comment]
you can use `query_serializer` for GET or `request_body` for POST ..

**Comment by axnsan12** [comment]
Docstring overrides are not supported by drf-yasg. You have to use programmatic methods such as the `swagger_auto_schema` decorator.
