### ISSUE TITLE
PATCH mehod with required field in swagger

### ISSUE THREAD

**Issue by Hanzhizheng** [axnsan12/drf-yasg#459]
Hi,
Serializer like this
```
class SomeSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.SomeModel
        fields = '__all__'
```
There are some must have fields defined in models.SomeModel.

Why request a PATCH partial update method is same as a POST create method? I have to fill all required fields in swagger...
What should I do?

**Comment by etene** [comment]
Hello,

I'm not sure I understand; do you mean that you want to have required fields even for PATCH requests ?

**Comment by axnsan12** [comment]
This is related to a known issue. Details and discussion here: https://github.com/axnsan12/drf-yasg/issues/70

There are also some good solutions proposed in that thread.

**Comment by mic159** [comment]
I had to just create another serializer that removes the required flag in the `get_fields` method:

```python

class MyUpdateSerializer(MySerializer):
    # Only for schema generation, not actually used.
    # because DRF-YASG does not support partial.
    def get_fields(self):
        new_fields = OrderedDict()
        for name, field in super().get_fields().items():
            field.required = False
            new_fields[name] = field
        return new_fields
```

Then just use that in the `swagger_auto_schema` request_body option.
