### ISSUE TITLE
JWT Bearer token authentication

### ISSUE THREAD

**Issue by arvindnrbt** [axnsan12/drf-yasg#46]
I tried setting up my Access token in the Authorize field. It didn't work. When I check the curl request there is no header parameter for Authorization. Can someone tell me how to add Bearer Token Auth?

**Comment by axnsan12** [comment]
Hello,

Something like this should work: 

```python
   'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
```

You will have to click the green authorize button in the top right and set the acces token; you will have to add the `Bearer` prefix manually when setting the token, as OpenAPI 2.0 has no support for authorization header prefixes - e.g. `Bearer <token here>`

**Comment by alirezasharzeh** [comment]
I am a newbie in django but I saw auto prefix is setting in multiple auto doc swaggers(in fastapi and some other nonpythonic freamwork). so it is possible to add this feature! so why it isn't in this package? is there any alternative that have this feature? or can be enabled by some settings?

**Comment by Parcurcik** [comment]
Hi, did you solve it?

**Comment by arif123654** [comment]
> Hello,
> 
> Something like this should work:
> 
> ```python
> SWAGGER_SETTINGS = {
>    'SECURITY_DEFINITIONS': {
>         'Bearer': {
>             'type': 'apiKey',
>             'name': 'Authorization',
>             'in': 'header'
>         }
>     }
> }
> ```
> 
> You will have to click the green authorize button in the top right and set the acces token; you will have to add the `Bearer` prefix manually when setting the token, as OpenAPI 2.0 has no support for authorization header prefixes - e.g. `Bearer <token here>`

It worked for me. Thanks.
