### ISSUE TITLE
support for request.GET.getlist

### ISSUE THREAD

**Issue by walthhy** [axnsan12/drf-yasg#463]
django has a method request.GET.getlist to parse params(with same key) into a list

For example: `GET /api/test?tag=xxx&tag=yyy`
`request.GET.getlist('tag', None)` will store xxx ans yyy into a list.

However, if I use `@swagger_auto_schema` with `openapi.Parameter('tag', openapi.IN_QUERY, description="filter the tags", type=openapi.TYPE_ARRAY, items=openapi.Items(type=openapi.TYPE_STRING))`

I will get swagger generating code like GET /api/test?tag=xxx,yyy

`
curl -X GET "http://localhost/api/test?tag=xxx,yyy"
`

How should I use dfr-yasq to get correct swagger code like /api/test?tag=xxx&tag=yyy

Or shall I ask django support to handle tag=xxx,yyy as a list?

**Comment by axnsan12** [comment]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

You should add `collectionFormat="multi"`
