### ISSUE TITLE
Data object for request_body

### ISSUE THREAD

**Issue by savvaoff** [axnsan12/drf-yasg#47]
Is it possible to get rid of "data" node in case when request structure is defined using "request_body" attribute?

<img width="294" alt="screen shot 2018-01-15 at 16 04 04" src="https://user-images.githubusercontent.com/3892914/34943787-3140a254-fa0e-11e7-8be9-8d2d4b303994.png">

**Comment by axnsan12** [comment]
Hello,

I am sorry but I do not really understand your question. The data node **is** the request body. It is what is sent in the body part of a POST/PUt/PATCH request.

You can get rid of it by not using request_body...

**Comment by savvaoff** [comment]
it's ok, if it should be like that (please, close the issue in the case).

PS.
previously when i created swagger docs manually, all the body params are displayed without "data" node in the doc.

**Comment by savvaoff** [comment]
...and old rdf swagger doc generators do it the same "no data" way:

<img width="648" alt="screen shot 2018-01-15 at 16 20 09" src="https://user-images.githubusercontent.com/3892914/34944295-0f246a78-fa10-11e7-80ef-ff594bc77d3a.png">

**Comment by axnsan12** [comment]
It seems to me that those are **form** parameters, not JSON body parameters. You will find that this library generates the same format for format request (i.e. if your remove json renderers/parsers from the view).

However you will also find that form parameters do not support nesting, and the library your are referencing above would probably incorrectly represent any nested serializers in the request body as a plain string value.

**Comment by axnsan12** [comment]
You might find this an interesting read; http://drf-yasg.readthedocs.io/en/stable/custom_spec.html#swagger-spec-overview

Specifically the part about Schema vs Parameter.

**Comment by axnsan12** [comment]
Maybe an option to prefer form parameters could be useful for cases where there is no nesting?

**Comment by savvaoff** [comment]
@axnsan12 
thanks.
it works well when DEFAULT_PARSER_CLASSES is set to FormParser/MultiPartParser.

**Comment by axnsan12** [comment]
Glad it worked out for you!

**Comment by hedleyroos** [comment]
@axnsan12 thread necromancy, but related to your earlier comment. I found a way to make form parameters support nesting. Is there a place to contribute this as a recipe?

**Comment by wajahatahmed245** [comment]
I want to request data in form data not in JSON how can I change that in yasg ? by default it is json form I want it to be in form data form 
![image](https://user-images.githubusercontent.com/32391965/66733756-fb88a280-ee79-11e9-9b9f-05d3862d431d.png)

**Comment by bay007** [comment]
https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#swagger-spec-overview
* request_body 
`
@swagger_auto_schema(methods=['put', 'post'], request_body=UserSerializer)
`
