### ISSUE TITLE
Provide consumes and produces at the root of the schema

### ISSUE THREAD

**Issue by Darkheir** [axnsan12/drf-yasg#48]
Hey,

I would like to provide a list of types that the API consumes and produces at the root of the schema but I didn't find the way to achieve it...

The only way I found is to modify the `get_schema` method of `OpenAPISchemaGenerator` se it looks like this:

```python
consumes = ['application/vnd.api+json']
produces = ['application/vnd.api+json']
return openapi.Swagger(
    info=self.info, paths=paths,
    _url=url, _prefix=prefix, _version=self.version,
    consumes=consumes, produces=produces,
    **dict(components)
)
```

Is there a way to achieve it without modifying the code, as a setting for example ?

**Comment by axnsan12** [comment]
Hello,

You could implement your changes without modifying the library code by just extending `OpenAPISchemaGenerator`:

```python
class CustomSchemaGenerator(OpenAPISchemaGenerator):
    def get_schema(self, request=None, public=False):
        swagger = super(CustomSchemaGenerator, self).get_schema(request, public)
        swagger.consumes = ['application/vnd.api+json']
        swagger.produces = ['application/vnd.api+json']
        
        return swagger
```

And then you can pass it to [get_schema_view](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.views.get_schema_view) as the `generator_class` argument.

Note however that `consumes` is also set at the Operation level, and you might have to change it there too - see [here](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#swaggerautoschema), [here](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_operation).

**Comment by Darkheir** [comment]
Yes, That what I was thinking about doing if there was no setting allowing it.

Don't you think that this can how attributes should be settable from the config of the project ?

**Comment by axnsan12** [comment]
It could be argued about lots of things that they should be configurable via settings, but there is only so much that you can encompass with declarative syntaxes. Subclassing provides a way to provide missing functionality according to everyone's particular use case, and I don't think this particular one is worth a setting. 

`consumes` should already be getting set for each operation as the media type of the first parser class on the view. However, some improvements which I do agree with would be also setting the `produces` filed on operations in the same way (which is not currently set at all), and maybe setting the top-level `consumes` and `produces` according to `DEFAULT_PARSER_CLASSES`/`DEFAULT_RENDERER_CLASSES`.

I will try to look into it.
