### ISSUE TITLE
yaml fille Character encoding problem

### ISSUE THREAD

**Issue by ruanhailiang** [axnsan12/drf-yasg#480]
I access this URL, http://127.0.0.1:8001/api/swagger.yaml,It works, but the Chinese characters in the content become Unicode.
Example：
```
swagger: '2.0'
info:
  title: "\u7528\u6237\u6743\u9650\u7BA1\u7406API\u63A5\u53E3\u6587\u6863"
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /api
```
I don't know how to deal with this problem. Who can help me? Thanks.

**Comment by axnsan12** [comment]
You would have to change the dumper used to encode yaml, to call the .dump method with allow_unicode=True.

You could do this by overriding `SwaggerYAMLRenderer`, and subclassing the class returned by `get_schema_view` to inject this renderer.
