### ISSUE TITLE
Multiple Serializer in a View

### ISSUE THREAD

**Issue by efe** [axnsan12/drf-yasg#487]
Hello,

A view returns different serializers by looking the query parameter.

```python
def get_serializer_class(self):
    bundle_type = self.request.query_params.get('bundle_type')
    if bundle_type == "large":
        return LargeSerializer
    else:
        return SmallSerializer
```

How should I document this?

**Comment by PaulWay** [comment]
I think the problem is that that wouldn't be a valid OpenAPI / Swagger spec.  AFAICS the spec can't change what type it outputs based on any knowledge of the actual query.

**Comment by davidmgvaz** [comment]
This is supported in OpenAPI 3.0:

https://github.com/OAI/OpenAPI-Specification/issues/270#issuecomment-284062885

Just need to wait for drf-yasg to support 3.0

**Comment by efe** [comment]
@davidmgvaz thank you! i look forward for the new release. :)
