### ISSUE TITLE
Calling .get_object() inside .get_serializer_class() raises AssertionError

### ISSUE THREAD

**Issue by 27149chen** [axnsan12/drf-yasg#50]
Tested on the example project "testproj".
Steps:
1. In view SnippetDetail, commented out serializer_class.
2. Added a method get_serializer_class, calling self.get_object() inside it
3. Opened http://localhost:8000/swagger/
4. AssertionError raised.
Exception Type: AssertionError at /swagger/
Exception Value: Expected view SnippetDetail to be called with a URL keyword argument named "pk". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly.

**Comment by 27149chen** [comment]
Hi, 
How to set schema=None, is there any examples? Thanks.

**Comment by axnsan12** [comment]
Hello,

You would add the class-level attribute `schema = None` to the view, or add the `@schema(None)` decorator if it is a function-based view.

**Comment by 27149chen** [comment]
Thank you for your answer :)
I have two more questions, please kindly reply.
1. How to set the http schema, the default is http, I can set it by pass url to the get_schema_view method, but it just work for test , in production, I don't know the ip/hostname.
2. The authorize seems not working. I checked the requests(try it out on swagger UI) after authorized, nothing is added.

**Comment by axnsan12** [comment]
1. The scheme and URL should be inferred automatically (using Django's standard request handling) from the location you are serving your swagger document, if you do not expicitly set an URL - see, for example http://drf-yasg-demo.herokuapp.com/cached/swagger/ serving an example project. If that is not the case, you should probably look into properly forwarding the request URL/scheme through your reverse proxy or WSGI setup to let Django know them
2. That is weird, which authentication scheme exactly are you using? Can you provide an example reproducing the issue?

You might have to look into http://drf-yasg.readthedocs.io/en/stable/settings.html#security-definitions for providing details about your authorization mechanism - by default it is set to HTTP basic authentication, which means that clicking authorize in swagger UI will set the user and password for basic auth; which will probably not work in your setup unless you have an authentication class that handles basic auth

**Comment by 27149chen** [comment]
Hi,
1. we use nginx outside serving https, and forward the requests to django using http, is that the problem? How to let django know it is a https request? I notice in the nginx config we added an header "Scheme", does it help?
2. I'm using the example, set "apiKey" in "SECURITY_DEFINITIONS", name is "Authorization", in is "header". After authorize on UI, I try to GET /snippets/, expact the curl box to add something like "-H "Authorization: value" ", but it didn't. Check the firefox console, no such header is added to this request.

**Comment by axnsan12** [comment]
1. No, it is not a problem, it's quite a common setup. You just have to do some hand-waving to make Django's build_absolute_uri work with it - something like https://design.canonical.com/2015/08/django-behind-a-proxy-fixing-absolute-urls/ (can't find something for nginx, but should be along the same lines)
2. It seems that there is a problem with security requirements not being set on endpoints... I'll have to check

**Comment by 27149chen** [comment]
Hi,
1. It looks great, but django doesn't need to know the absolute url for most cases, and I just simply want the scheme(s), should we have something like a general setting in the config file?

BTW, I have another question: Some of my request params are generated as http body while some as form data, what is the principle? In fact one of my endpoints' POST data is generated as form data wrongly, I want to know why. Thank you.

**Comment by axnsan12** [comment]
1. If you really insist on not configuring the URL, you can set `url=''` in `get_schema_view`. This will prevent the `schemes` and `host` fields from being generated at all, which will force `swagger-ui` to determine the appropriate endpoint locally (in the browser). This will make Try it out work, but is a partially wrong thing to do. I would still recommend configuring your reverse proxy correctly.

Another setting is not something I'm inclined to add, the way hosts and schemes are determined is already pretty complicated.

About body vs form, the principle is quite simple: form data will be generated when the `parser_classes` of a view consist only of `FormParser` or `MultiPartParser`. HTTP body is generated in all other cases.

**Comment by 27149chen** [comment]
my parser_classes is (FormParser, MultiPartParser, JSONParser,), should it be a form data?

**Comment by axnsan12** [comment]
Hmm, no it should not.

Seems to be a bug in [get_consumes](https://github.com/axnsan12/drf-yasg/blob/a46b684fea0522bede31a77cdcfbfb3cb631ab23/src/drf_yasg/inspectors/view.py#L312) which wrongly assumes that non-form parsers come first.

I'll push a fix later today, but temporary workaround is to put the JSONParser at the start of the array (if that does not mess up your request handling).

**Comment by 27149chen** [comment]
No, I can't change it, it is DRF's ObtainAuthToken view, I'll waiting for your commit, thanks.

**Comment by 27149chen** [comment]
Hi,

I notice that Swagger-ui support rendering page on either client side or sever side. Since we are using AngularJS, I wonder if it is configurable for the client side solution.

**Comment by axnsan12** [comment]
Hello,

That is out of the scope of this project. You could skip on using the `swagger-ui` distribution bundled with `drf-yasg`, and deploy your own. You would then use the `swagger.yaml`/`swagger.json` endpoint without UI, as shown in the readme example, and configure your swagger-ui deployment to render from that endpoint.
