### ISSUE TITLE
Help wanted: File download as Response

### ISSUE THREAD

**Issue by ozhaozhao** [axnsan12/drf-yasg#501]
> I tried the following but the `Response content type` is still `application/json`. I would like to have it as `application/octet-stream` - thanks
> 
> ```
> @swagger_auto_schema(
>     query_serializer=DocumentQuerySerializer,
>     responses={
>         '200': openapi.Response('File Attachment', schema=openapi.Schema(type=openapi.TYPE_FILE)),
>         '400': 'Bad Request',
>         '401': 'Not Authorized',
>         '404': 'Not Found'
>     },
>     produces='application/octet-stream',
>     operation_id='Retrieve a Document',
>     operation_description='GET server:PORT/documentstore/docs?id=string'
> )
> def get(self, request, *args, **kwargs):
> ```
> 
> ...

I got this to work by using a custom `SwaggerAutoSchema` subclass and over-ridding `get_produces`.

_Originally posted by @conversica-markrodriguez in https://github.com/axnsan12/drf-yasg/issues/366#issuecomment-492452428_

**Comment by ozhaozhao** [comment]
“custom SwaggerAutoSchema subclass and over-ridding get_produces.” Can somebody explain how to implement this?

**Comment by etene** [comment]
Hello, this is already pretty well explained in the documentation:
- Using custom `SwaggerAutoSchema` subclasses is covered [here](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#swaggerautoschema),
- The `get_produces` method is documented [here](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.inspectors.SwaggerAutoSchema.get_produces).

**Comment by ozhaozhao** [comment]
@etene it does work, thank you.

**Comment by BenStirrup** [comment]
It would have been helpful to actually post the implementation.

**Comment by heveaconnectakila** [comment]
@BenStirrup  yeah talk about it... 

This works, adding this here please improve and add it to documentation @axnsan12 if possible?

```
import os

from django.http import HttpResponse
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.generics import GenericAPIView


class MyView(GenericAPIView):

    @action(methods=['get'], detail=False)
    @swagger_auto_schema(
        operation_description="pdf",
        manual_parameters=[openapi.Parameter("id", openapi.IN_PATH, description="doc id", type=openapi.TYPE_STRING)],
        responses={
            "200": openapi.Response('File Attachment', schema=openapi.Schema(type=openapi.TYPE_FILE))
        }
    )
    def get(self, request, id, *args, **kwargs):
        file_path = "..."
        file_handle = open(file_path, mode='rb')
        size = os.path.getsize(file_path)
        response = HttpResponse(file_handle, status=status.HTTP_200_OK, content_type='application/pdf')
        response["Content-Disposition"] = f"attachment; filename='{id}.pdf'",
        response["Content-Length"] = f"{size}"
        return response

```
