### ISSUE TITLE
drf_yasg.errors.SwaggerGenerationError: cannot instantiate nested serializer as Parameter

### ISSUE THREAD

**Issue by ranvijay-sachan** [axnsan12/drf-yasg#503]
I'm trying to upload a file from 'drf-yasg' but in model its showing `readonly true`.
if i use `parser_classes = (MultiPartParser,)` in my viewset  then getting `cannot instantiate nested serializers as Parameter`.Please give me some hint to resolve this issue.

Sample code:

views.py

```
class RequesterViewSet(viewsets.ModelViewSet):
    """
    list of departments
    """
    queryset = Requester.objects.all()
    parser_classes = (MultiPartParser,)
    serializer_class = RequesterSerializer


```

serializers.py

```
class RequesterSerializer(serializers.ModelSerializer):
    files = serializers.FileField(source='requester_files', read_only=False)

    class Meta:
        model = Requester
        fields = ('id', 'request_type', 'requested_person', 'on_behalf_of', 'project','files')
```

models.py

```
class Requester(TrackerModel):

    created_date = models.DateTimeField(auto_now_add=True)
    request_type = models.CharField(choices=REQUEST_TYPE, default='Items', max_length=10)
    requested_person = models.ForeignKey(MyUser, related_name='requested_person', on_delete=models.PROTECT)
```

```
class RequesterFile(TrackerModel):
    file = models.FileField(upload_to="files/requester/%Y/%m/%d")
    requester = models.ForeignKey(Requester, on_delete=models.PROTECT, related_name='requester_files')
```

**Comment by dzbrozek** [comment]
Try to add to you view

```
def get_parsers(self):
    if getattr(self, 'swagger_fake_view', False):
        return []

     return [parser() for parser in self.parser_classes]
```

**Comment by axnsan12** [comment]
Representing arrays of files is not doable with OpenAPI 2.0 restrictions. You should probably just exclude your view from the swagger doc, or apply @dzbrozek's suggestion which will render the files field as read-only.

**Comment by eagledev-tank** [comment]
I have same problem

class TargetAudienceSerializer(serializers.ModelSerializer):
    class Meta:
        model = TargetAudience
        fields = ['id', 'name']


class WhatYouWillLearnSerializer(serializers.ModelSerializer):
    class Meta:
        model = WhatYouWillLearn
        fields = ['id', 'topic']


class CourseCreateSerializer(serializers.ModelSerializer):
    target_audiences = TargetAudienceSerializer(many=True)
    learning_points = WhatYouWillLearnSerializer(many=True)

    class Meta:
        model = Course
        fields = ['title', 'image', 'description', 'target_audiences', 'learning_points']

    def create(self, validated_data):
        target_audiences = validated_data.pop('target_audiences')
        learning_points = validated_data.pop('learning_points')
        course = Course.objects.create(**validated_data)

        for audience in target_audiences:
            TargetAudience.objects.create(course=course, **audience)

        for points in learning_points:
            WhatYouWillLearn.objects.create(course=course, **points)

        course.update_course_data()
        return course
