### ISSUE TITLE
Adding custom vendor tags to the yaml specification document

### ISSUE THREAD

**Issue by sulantha2006** [axnsan12/drf-yasg#509]
I am using drf-yasg to create a swgger YAML file. I am using the `generate_swagger` command to generate a YAML file. I need to add a custom YAML tag similar to the following in the YAML file. I was not able find a way to add without defining a Custom Generator. 
`x-google-backend:`
     `address: https://sdflas.sdkha.ca`

**Comment by axnsan12** [comment]
Defining a custom generator is the perfectly good solution to this.
