### ISSUE TITLE
Endpoints not showing from serializer_class but the models

### ISSUE THREAD

**Issue by andersondborges** [axnsan12/drf-yasg#51]
How I set to get response and request from serializer_class not model?
All my endpoints is showing from the models.

**Comment by axnsan12** [comment]
Hello @andersondborges,

Could you give more details about your problem? All endpoints use `get_serializer` method of views when inspecting a view's serializer, which is in line with Django Rest Framework's default behavior. If that does not work for you please provide concrete examples of what you are trying to achieve.

**Comment by axnsan12** [comment]
In absence of a code example I'm going to close this. I will reopen if you come back with an example to reproduce the issue.
