### ISSUE TITLE
Using swager_auto_schema decorator with a request_body on partial_update falsely shows required fields.

### ISSUE THREAD

**Issue by dragonpaw** [axnsan12/drf-yasg#511]
Given: 

```python
class MyViewSet(...)
    @swagger_auto_schema(
        request_body=MySerializer(partial=True),
        operation_description="Update a thing (All fields are actually optional)",
        responses={status.HTTP_200_OK: MySerializer},
    )
    def partial_update(self, request, *args, **kwargs):
        # Do stuff, and things.
```

The resulting docs show all the usually-required fields of the MySerializer as required, when in fact since its a partial_update method, and `MySerializer` was initialized with `partial=True`, there's no required fields at all.

**Comment by axnsan12** [comment]
Due to spec limitations it's not possible to properly support partial with OpenAPI 2.0, sorry about that.
