### ISSUE TITLE
Is there a way to override the default documentation for `/request/` actions?

### ISSUE THREAD

**Issue by maxmcclorey** [axnsan12/drf-yasg#512]
I have a ViewSet action called `request`

`    @action(detail=True, methods=['post', 'get'], permission_classes=[AllowAnyExceptReadOnly])
    def request(self, request, *args, **kwargs):`

I wrote a `swagger_auto_schema` for it, but it is getting ignored.  Instead the documentation reads "Wrapper allowing to enhance a standard HttpRequest instance."

Is there a way to override this behavior?

**Comment by axnsan12** [comment]
A method named request is not a good idea in general, you can find many issues about it on the net. Just rename the method in your code and use the `path` argument of `@action`.
