### ISSUE TITLE
Option to generate served schema in JSON format instead of YAML

### ISSUE THREAD

**Issue by deepaerial** [axnsan12/drf-yasg#515]
I've added `schema_view.without_ui` to my url patterns:
```python
urlpatterns = [
    # ...
    path(
        'swagger.json',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json'
    ),
    path(
        'swagger/',
        schema_view.with_ui('swagger', cache_timeout=0),
        name='schema-swagger-ui'
    ),
    path(
        'redoc/',
        schema_view.with_ui('redoc', cache_timeout=0),
        name='schema-redoc'
    ),
]
```
When calling `my_host/swagger.json` I get file `swagger.json` with YAML contetnt inside. Is there any parameter that allows me to generate and serve Swaggger schema (no UI)  in JSON format. 
**P.S** This is techniacallly question and I've already posted it on [SO](https://stackoverflow.com/questions/59357438/serving-generated-swagger-schema-in-django-with-drf-yasg) but maybe I will get answer here. Sorry, if this question was asked previously.

**Dependencies**:
```json
        "django": {
            "hashes": [
                "sha256:6f857bd4e574442ba35a7172f1397b303167dae964cf18e53db5e85fe248d000",
                "sha256:d98c9b6e5eed147bc51f47c014ff6826bd1ab50b166956776ee13db5a58804ae"
            ],
            "index": "pypi",
            "version": "==3.0"
        },
        "djangorestframework": {
            "hashes": [
                "sha256:05809fc66e1c997fd9a32ea5730d9f4ba28b109b9da71fccfa5ff241201fd0a4",
                "sha256:e782087823c47a26826ee5b6fa0c542968219263fb3976ec3c31edab23a4001f"
            ],
            "index": "pypi",
            "version": "==3.11.0"
        },
        "drf-yasg": {
            "hashes": [
                "sha256:4cfec631880ae527a91ec7cd3241aea2f82189f59e2f089119aa687761afb227",
                "sha256:504cce09035cf1bace63b84d9d778b772f86bb37d8a71ed6f723346362e633b2"
            ],
            "index": "pypi",
            "version": "==1.17.0"
        },
```

**Comment by etene** [comment]
Overriding your [`SchemaView`](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.views.SchemaView)'s [`renderer_classes`](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.views.SchemaView.renderer_classes) attribute to only include [`SwaggerJSONRenderer`](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.renderers.SwaggerJSONRenderer) should do the trick.

**Comment by axnsan12** [comment]
Simply using a named capture for the format, as documented in the quickstart guide, will switch between formats according to the extension without the need to override anything:

```
    re_path(
        'swagger(?P<format>\.json)',
        schema_view.without_ui(cache_timeout=0),
        name='schema-json'
    ),
```

In DRF, this is the standard way of switching the renderer content type based on the url.
