### ISSUE TITLE
Combine manual parameters from mixins

### ISSUE THREAD

**Issue by rvishna** [axnsan12/drf-yasg#516]
I have a view set that looks like this:

```
from rest_framework import viewsets, mixins

@method_decorator(
    name="list",
    decorator=swagger_auto_schema(
        manual_parameters=[
            openapi.Parameter(
                "param1",
                openapi.IN_QUERY,
                description="Description for param1",
                type=openapi.TYPE_BOOLEAN,
            )
        ]
    ),
)
class Mixin1(mixins.ListModelMixin):
    pass

@method_decorator(
    name="list",
    decorator=swagger_auto_schema(
        manual_parameters=[
            openapi.Parameter(
                "param2",
                openapi.IN_QUERY,
                description="Description for param2",
                type=openapi.TYPE_BOOLEAN,
            )
        ]
    ),
)
class Mixin2(mixins.ListModelMixin):
    pass

class MyViewSet(Mixin1, Mixin2, viewsets.ModelViewSet):
   pass
```

`param1` and `param2` alter the behavior of the view set in different ways, so I would like to keep them in separate mixins. If I look at the generated docs for `MyViewSet`, I expected to see both `param1` and `param2` as query parameters, but I only see the parameters from the first mixin in the list.

Is it possible to achieve combining query parameters from mixins this way?

**Comment by axnsan12** [comment]
Well, not really, since only one of those methods is really going to be called, so it wouldn't make sense to take parameters from both. 

You could probably write your own logic for this using a SwaggerAutoSchema override, but I don't know exactly how to go about implementing it.
