### ISSUE TITLE
AcceptHeader versioning

### ISSUE THREAD

**Issue by ezet** [axnsan12/drf-yasg#519]
Is it possible to get this working with AcceptHeader versioning?

I have created a custom auto schema which has been heavily modified to suit our needs, but I cannot seem to find any way to even begin adding support for this without modifying library code. I feel like a natural place to add this would be in `get_response_serializers`, but it doesn't seem possible to define different schemas based on the requested content type, only the response code.

Am I missing something? Is there a way to define different schemas based on the 'response content type' selector that is available in the Swagger UI?

**Comment by axnsan12** [comment]
Hello. You should be able to do this by subclassing SchemaGenerator. You can look at how NamespaceVersioning is handled, but in essence all you have to care about is `self.request.version` and appropriately segregating the versions in should_include_endpoint.

I don't think there's a way to have a single swagger json cover all of the versions. You'll need to have separate instances that return different schemas, e.g.

`curl -H "Accept: application/json; version=1.0" http://localhost/swagger.json"` vs `curl -H "Accept: application/json; version=2.0" http://localhost/swagger.json"` which would return the different views over the API. This is similar to how namespace versioning is handled and I actually expect it to, for the most part, work out of the box.

**Comment by affan10** [comment]
@ezet Were you able to achieve this? If yes, can you please share the details.

**Comment by ezet** [comment]
I did end up implementing a custom solution for this. My current solution modifies the schema such that each version is represented by a different HTTP response code. E.g., for a given endpoint, the schema generator will generate a `200.1` response for version 1, `200.2` for version 2, and so on. This works well with both redoc and swagger UI, and allows me to view all versions within the single endpoint.

**Comment by affan10** [comment]
Great! Can you share some code samples?
