### ISSUE TITLE
Multiple schema view pages

### ISSUE THREAD

**Issue by ivanhtemp** [axnsan12/drf-yasg#524]
Hi everyone. I would like to know the way of creating separated Swagger pages for different Django apps. I looked up in this project but I didn't find any about this.

**Comment by axnsan12** [comment]
You can just call get_swagger_view multiple times with different urlconfs.

**Comment by adonig** [comment]
I'm sorry for commenting in a closed issue, but I'm confused how to do it. I have two APIs and want two Swagger views. Now if I create two swagger views with get_swagger_view and then use @swagger_auto_schema the methods are visible in both swagger views. How can I tell swagger_auto_schema to add the method only to a certain swagger view?

**Comment by axnsan12** [comment]
By passing pattenrs and/or urlconf arguments to get_schema_view.
