### ISSUE TITLE
Scheme Configuration

### ISSUE THREAD

**Issue by techdragon** [axnsan12/drf-yasg#525]
The current situation seems to be determining the value of the top level `schemes:` key by taking the currently in use URL Scheme, which leads to different documents based on use of HTTP and HTTPS... it should be possible to configure the library so that our `schemes:` value is correct and _consistent_ regardless of how it was accessed.

**Comment by axnsan12** [comment]
You can use `get_swagger_view(url=...)` or the DEFAULT_API_URL to provide a fixed url.

https://drf-yasg.readthedocs.io/en/stable/openapi.html#default-behavior
