### ISSUE TITLE
Swagger UI not generating on Heroku

### ISSUE THREAD

**Issue by MandelaK** [axnsan12/drf-yasg#526]
I'm having an issue where the Swagger UI is not being generated on Heroku, but on my local machine everything is working just fine. I believe I set everything as expected in my django urls, so I am not sure what could be the problem. Below is a snippet of my root `urls.py` file:
```
schema_view = get_schema_view(
   openapi.Info(
      title="APII",
      default_version='v1',
      description="Just some text",
      terms_of_service="",
      contact=openapi.Contact(email="contact@contact.com"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

...

urlpatterns = [
    path('api/v1/docs/', schema_view.with_ui('swagger', cache_timeout=0), name='api-documentation'),
    path('', RedirectView.as_view(url='api/v1/docs/',
                                  permanent=False),
         name='api_documentation'),
]
```

**Comment by MandelaK** [comment]
Here is the url for my deployed heroku app `https://shyper-logistics.herokuapp.com/api/v1/docs/` ... as you can see, it does not render any Swagger UI components ... Inspecting the network tab on dev tools shows all requests were returned with a `404` response. Please help, thank you.

**Comment by MandelaK** [comment]
So it was a problem with static files not loading properly. After installing [django-heroku](https://github.com/heroku/django-heroku), it handled all that for me. I feel dumb, but I learned a lot in the process. I will close this now.

**Comment by gomeslucasm** [comment]
how django_heroku was set in setings.py? I have the same problem
