### ISSUE TITLE
How can i set mylogo in the top of my api list?

### ISSUE THREAD

**Issue by danilocastelhano1** [axnsan12/drf-yasg#527]
Hi guys, how can i set my logo in the top of my api list? Today is listed the default logo, wanted to put the logo of my company, is there a possibility? 

![image](https://user-images.githubusercontent.com/52941839/72382702-99e60780-36f8-11ea-8bd6-61c0ec5c0edc.png)

**Comment by samson1998** [comment]
I feel you should be able to make a tweak from the index.html file so as to replace it. Try it out and revert.

**Comment by keezysilencer** [comment]
You can pass the data through  the get_schema_view as x_logo[dict]
`schema_view = get_schema_view(
    openapi.Info(
        title="SNIPPET  API",
        default_version='v1.0',
        description="Test Description",
     
        license=openapi.License(name="BSD License"),
        x_logo={
            'url': "https://random.com/url/to-your-image.png"
        }
    ),

)`

**Comment by danilocastelhano1** [comment]
Thx

**Comment by ifranco14** [comment]
@danilocastelhano1 could you do it by  passing  the x_logo param? I'm not being  able to do it :(

**Comment by danilocastelhano1** [comment]
> @danilocastelhano1 could you do it by passing the x_logo param? I'm not being able to do it :(

Yes, i made passing the x_logo:
```
x_logo={
            "url": "my_logo_url",
            "backgroundColor": "#f1f1f1",
            "href": "/"
        },
```

**Comment by ifranco14** [comment]
Hi @danilocastelhano1, thanks for the answer! 

Following up with my question, did it work for Swagger? In my case, it is working in ReDoc but not in Swagger (and of course I totally prefer Swagger hahah)

**Comment by danilocastelhano1** [comment]
for swagger i did a trick on css:
```
#swagger-ui .topbar .wrapper .topbar-wrapper a{
    background-image: url(/static/images/my_logo.png);
    width: 194px;
    height: 31px;
    background-size: contain;
}
```

for documentation i did this:
```
schema_view_new = get_schema_view(
    openapi.Info(
        title="Title",
        default_version='v1',
        description='desc',
        terms_of_service="https://mylink/terms-conditions/",
        contact=openapi.Contact(name='Jon',
                                email='jonsnow@mail.com',
                                url='my_url'),

        license=openapi.License(name='licence name',
                                url='url_licence'),
        x_logo={
            "url": "my_logo_url/image.png",
            "backgroundColor": "#f1f1f1",
            "href": "/"
        },
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
    url='',
)
```
after that in my urls.py i use my "schema_view_new" and call like this:
```
url(r'^$', schema_view_new.with_ui('swagger', cache_timeout=3600), name='schema-swagger-ui'),
url(r'^documentation/$', schema_view_new.with_ui('redoc', cache_timeout=3600), name='schema-redoc'),
```
in my browser i access like this:
127.0.0.1/   <- for swagger 
127.0.0.1/documentation <- for redoc

**Comment by ifranco14** [comment]
Great! That's pretty the same I did :)

And last question @danilocastelhano1, which is the right place to put that css? Should I extend the swagger-iu template?

**Comment by danilocastelhano1** [comment]
yes, i duplicate both html (swagger-ui.html) and (redoc.html) and created a new class extending renderers.py and in class: SwaggerUIRenderer i pass my html path `template = 'rest_framework_swagger/swagger-ui_custom.html'` and in this block i added my css custom class:
```
{% block main_styles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/> /*MY CUSTOM CSS CLASS  FROM STATIC FOLDER*/
        <link rel="stylesheet" type="text/css" href="{% static 'drf-yasg/swagger-ui-dist/swagger-ui.css' %}">
{% endblock %}
```

**Comment by ifranco14** [comment]
Thanks mate! I really appreciate all your answers :)
