### ISSUE TITLE
Post Request Forbidden error, when user is login  

### ISSUE THREAD

**Issue by anmola31** [axnsan12/drf-yasg#539]
without login post method working fine. but when login, I'm getting 403: Forbidden error.

Below is the configuration.

SWAGGER_SETTINGS = {
    'LOGIN_URL':'/admin/login',
    'LOGOUT_URL': '/admin/logout',
}

urls.py
urlpatterns1=[re_path(r'^', include('api.urls')),]

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=False,
   permission_classes=(permissions.AllowAny,),
    patterns=urlpatterns1
)
urlpatterns =urlpatterns1+ [
    url(r'^swagger(?P<format>\.json|\.yaml)$', login_required(schema_view.without_ui(cache_timeout=None)), name='schema-json'),
    url(r'^swagger/$', login_required(schema_view.with_ui('swagger', cache_timeout=None)), name='schema-swagger-ui'),
    url(r'^redoc/$', login_required(schema_view.with_ui('redoc', cache_timeout=None)), name='schema-redoc'),
    path('admin/', admin.site.urls),

]
views.py 
request_category_put = openapi.Schema(type=openapi.TYPE_OBJECT, required=['question_id','choice_id'],
    properties={
        'question_id': openapi.Schema(type=openapi.TYPE_INTEGER, ), ### <-- I have the ID here.
        'choice_id': openapi.Schema(type=openapi.TYPE_INTEGER, )
    },
    example={
            'question_id' : 1,
            'choice_id' : 1,
        }
)
class SubmitChoice(APIView):
    @swagger_auto_schema(
        request_body=request_category_put,
        responses={
            '200': "success",
            '400': 'Bad Request',
            '404': 'Not found'
        },
    )
    def post(self, request, *args, **kwargs):
         ..................
         return response

**Comment by axnsan12** [comment]
This is probably not related to drf-yasg. Example and demo site works fine. If you still think it's a bug please provide full project to reproduce.
