### ISSUE TITLE
Error AttributeError: 'AnonymousUser'

### ISSUE THREAD

**Issue by danilocastelhano1** [axnsan12/drf-yasg#544]
I Have this trouble when I Open my documentation:

 view's MyViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view
', False)` to detect and short-circuit this

line 33, in get_queryset
return MyModel.objects.filter(container=self.request.user.container)
AttributeError: 'AnonymousUser' object has no attribute 'container'

Somebody know how to solve this please?

**Comment by axnsan12** [comment]
use getattr(self, 'swagger_fake_view ', False) to return early from your get_queryset in a way that does not depend on request parameters.

**Comment by danilocastelhano1** [comment]
> use getattr(self, 'swagger_fake_view ', False) to return early from your get_queryset in a way that does not depend on request parameters.

Sorry but a did not understand, when i use that? Can you write a example please? Thanks

**Comment by JhonatanRian** [comment]
I'm having the same problem, did you manage to solve it?

**Comment by danilocastelhano1** [comment]
Hi i changed the job and i don't know the other devs solved this issue

**Comment by TheGardenMan** [comment]
I used something like this to solve the issue

`return MyModel.objects.filter(container=getattr(self.request.user, 'container', None))`.

You should add `if` conditions if you are not sure `request.user` will always have `container`.
