### ISSUE TITLE
Schema generation for SerializerMethodField returning dict

### ISSUE THREAD

**Issue by moritztk** [axnsan12/drf-yasg#546]
Hi!
I have some SerializerMethodField props that are returning dicts, e.g.
```python
    def get_price(self, obj):
        return dict(
            base_price=PriceSerializer({"amount": obj.amount, "currency": obj.currency}).data,
            total=PriceSerializer({"amount": obj.total_amount, "currency": obj.currency}).data,
        )
```
How can I get drf-yasg to generate the correct schema for this?

**Comment by axnsan12** [comment]
You can use `@swagger_method_field`, and either change the code to return the data using a serialzier,   or manually create your own `openapi.Schema`.

**Comment by moritztk** [comment]
Hi @axnsan12, thanks for your answer.
what's the `swagger_method_field`? I cannot find it in the docs.
https://drf-yasg.readthedocs.io/en/stable/search.html?q=swagger_method_field&check_keywords=yes&area=default

**Comment by axnsan12** [comment]
Sorry, the decorator is called swagger_serializer_method https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html

**Comment by moritztk** [comment]
Thanks for your answer @axnsan12 

I tried your proposition with `openapi.Schema`, but I cannot quite get it to work
```
    price_schema = openapi.Schema(
        title="Price",
        type=openapi.TYPE_OBJECT,
        properties={
            "amount": openapi.Schema(title="amount", type=openapi.TYPE_INTEGER, format=openapi.FORMAT_EMAIL,),
            "currency": openapi.Schema(title="currency", type=openapi.TYPE_STRING,),
        },
        required=["amount", "currency"],
    )
    @swagger_serializer_method(serializer_or_field=openapi.Schema(
        title="Price",
        type=openapi.TYPE_OBJECT,
        properties={
            "base_price": price_schema,
            "total": price_schema,
        },
        required=["base_price", "total"],
    ))
    def get_price(self, obj):
    return dict(
        base_price=PriceSerializer({"amount": obj.amount, "currency": obj.currency}).data,
        total=PriceSerializer({"amount": obj.total_amount, "currency": obj.currency}).data,
    )
```

I get the error message
> AssertionError: passed field is already a SwaggerDict object

Any idea what I am doing wrong?

**Comment by moritztk** [comment]
It looks like I am running into here: https://github.com/axnsan12/drf-yasg/blob/548489a5395ad7a2a1179661feef895fad086882/src/drf_yasg/inspectors/base.py#L272

I guess it's not possible to just pass the schema into `swagger_serializer_method`?

**Comment by OskarPersson** [comment]
I'm running into the same problem. I've also tried using TypedDict:

```
def get_token(self, user) -> TypedDict('Token', {'access_token': str, 'refresh_token': str, 'expires_in': int}):
    return {
        'access_token': 'foo',
        'refresh_token': 'bar',
        'expires_in': 10
    }
```


but this only results in:

```json
"token": {
    "title": "Token",
    "type": "object",
    "readOnly": true
},
```

@axnsan12 What is the correct approach?

**Comment by wygmjdd** [comment]
Hi，thanks for this question.

I used like this, it worked.

```py
key1_swagger_use = serializers.ListField(
    child=serializers.CharField(),
    help_text=_('xxx')
)


class XxSerializer(serializers.ModelSerializer):
    key1 = serializers.SerializerMethodField(source='key1')

    class Meta():
        model = XxModel
        fields = (
            'key1', 'key2', 
        )

    @swagger_serializer_method(key1_swagger_use)
    def get_key1(self, obj):
        return obj.key1.split('/')
```
