### ISSUE TITLE
Scroll bug when click side nav and scroll up

### ISSUE THREAD

**Issue by gmlwo530** [axnsan12/drf-yasg#578]
Hello!
First of all, thanks, I am using it well.

I found bug in redoc template.

This bug is appeared [demo app](https://drf-yasg-demo.herokuapp.com/cached/redoc/) (also, in my project)

**Situation**
1. Click 'people' tab in side nav
2. Scroll down to 'people_list' section until URL changed to `https://drf-yasg-demo.herokuapp.com/cached/redoc/#operation/people_list`
3. Scroll up very little, then suddenly page is moved to top

I captured video about bug and pasted.

How can i fix it???

Video : [bug_video.zip](https://github.com/axnsan12/drf-yasg/files/4507627/bug_video.zip)

**Comment by aniforprez** [comment]
This might be better documented in the ReDoc repo rather than here since it's a problem with their script. I'm facing the same issue

**Comment by aniforprez** [comment]
https://github.com/Redocly/redoc/issues/1168

Here's the issue on the redoc repo. They're sorting it and I assume this repo will update to use the new script source in the template

**Comment by gmlwo530** [comment]
@aniforprez 

Ah, thank you!!!!

Then, 
So should i close this issue?

**Comment by aniforprez** [comment]
Yeah you can close this. There's a PR to fix the issue too https://github.com/axnsan12/drf-yasg/pull/543

**Comment by gmlwo530** [comment]
Ok, Thank You!
