### ISSUE TITLE
Repeat endpoint with suffix {format} when use path function

### ISSUE THREAD

**Issue by zengzhengrong** [axnsan12/drf-yasg#579]
Django 2.2 & DRF 3.9.2
Example:
```
urlpatterns = format_suffix_patterns([
    path('list/', category_list, name='category-list'),
    ...
```
<img width="334" alt="0ba3a846963e44bd2511ae586a2bb50" src="https://user-images.githubusercontent.com/23110784/79942223-e8920300-8498-11ea-867a-5cfc12a2483d.png">

use re_path
```
re_path(r'^list/$', category_list, name='category-list'),
```
It look normally
<img width="251" alt="e205ab4495a583b9b195c90b7570724" src="https://user-images.githubusercontent.com/23110784/79942413-59d1b600-8499-11ea-89c9-a52b819be3db.png">
I use path func on anywhere ,So how to fix that ？Thank  your awesome repo~
BTW, When I access /swagger/ ,The console come out 404 for some static file
```
[22/Apr/2020 13:00:01] "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js.map HTTP/1.1" 404 1771
[22/Apr/2020 13:00:01] "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js.map HTTP/1.1" 404 1804
[22/Apr/2020 13:00:02] "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css.map HTTP/1.1" 404 1753
```

**Comment by zengzhengrong** [comment]
The cause is format_suffix_patterns model ,remove ```format_suffix_patterns ```

**Comment by germaindd** [comment]
you can create a custom OpenAPISchemaGenerator as a work around for this issue to avoid duplicate entries in the generated schemas:

```python
from drf_yasg.generators import OpenAPISchemaGenerator


class CustomSchemaGenerator(OpenAPISchemaGenerator):
  def should_include_endpoint(
    self, path: str, method: str, view, public: bool
  ) -> bool:
    return not path.endswith("{format}") and super().should_include_endpoint(
      path, method, view, public
    )
    
schema_view = get_schema_view(
  ...,
  generator_class=KaryaSchemaGenerator
)
```
