### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by hnykda** [axnsan12/drf-yasg#590]
Hey. May I ask @axnsan12 if this project is dead or? There are things like [this](https://github.com/axnsan12/drf-yasg/pull/543) being unnoticed and things being broken for quite some time. There were only few commits on Feb 17 by the author, but no PRs have been accepted since Nov 16.

Could the owner please communicate what is his intended goal with this repo and either ask for contributors, archive, or help with moving this forward? 

Otherwise I don't think it should be mentioned in the DRF docs: https://www.django-rest-framework.org/topics/documenting-your-api/#drf-yasg-yet-another-swagger-generator

**Comment by MissiaL** [comment]
There is a similar project that is being actively developed now. You can help with this!
https://github.com/tfranzel/drf-spectacular

**Comment by johnthagen** [comment]
I suggest this issue get pinned for more visibility if @axnsan12 has a little time to do that.

I just discovered that no tests have been running on Django 3.0 (#636), so I do agree this project needs some TLC if possible, or at least a notice if it is not being maintained so users can be made aware. I do hope this project continues as it's a very useful library.

**Comment by johnthagen** [comment]
If new maintainers are needed, perhaps a pinned issue asking for new maintainers could help.

**Comment by johnthagen** [comment]
Another pending issue users should be aware of is that this project will not work with Python 3.10 and newer if #473 is not fixed.

**Comment by johnthagen** [comment]
DRF 3.12 breaking change that is urgently needed: #641

**Comment by johnthagen** [comment]
Please see #662. This project is now maintained once again and has multiple maintainers to reduce the risk of this happening again in the future.

**Comment by onegreyonewhite** [comment]
@JoelLefkowitz is the project still alive? do you need help?

**Comment by JoelLefkowitz** [comment]
> @JoelLefkowitz is the project still alive? do you need help?

Yup, looking to cut a new release this week with the latest PRs

**Comment by onegreyonewhite** [comment]
> Version 1.21.5 now released with support for python 3.10

What?) We successfully already using it on Python 3.10 half of year. Python 3.11 also works too.

**Comment by JoelLefkowitz** [comment]
Yup but we didn't have any tests targeting it, now we do
