### ISSUE TITLE
Change "Response content type"

### ISSUE THREAD

**Issue by fvitello** [axnsan12/drf-yasg#592]
Hi,

i need to change the shown "Response content type" of one of my api from application/json to text/plain according to the response header ( that is content-type: text/plain ).

Is there any way to change to do this?

Thank you

**Comment by chgad** [comment]
You might want to take a look into the stuff mentioned in #501 .

**Comment by fvitello** [comment]
Thank you, i was able to add the text/plain  response content type but now when the api is executed i got the following reponse 
```
{
  "detail": "Could not satisfy the request Accept header."
}
```

my function returns the following
```
return HttpResponse(str(parset_str), content_type='text/plain')
```

How can i solve?
Thanks

**Comment by chgad** [comment]
Are you working with a serializer for this view?

**Comment by fvitello** [comment]
i have tried to remove the serializer but nothing is changed

**Comment by chgad** [comment]
Could you provide your customschema and the invocation of the `swagger_auto_schema`decorator ?

**Comment by fvitello** [comment]
```
class TextPlainAutoSchema(SwaggerAutoSchema):
    def get_produces(self):
        return ["text/plain"]
    def get_consumes(self):
        return ["text/plain"]
    

 @swagger_auto_schema(auto_schema=TextPlainAutoSchema,
                        responses={200: 'parset for this subtask (as plain text, not json)',
                                    403: 'forbidden',
                                    404: 'Not found'},
                          #produces='text/plain',
                        operation_description="Get parset for the specifications of this subtask")

```

**Comment by chgad** [comment]
>  ` #produces='text/plain',`

Why is this line commented out?

>     def get_consumes(self):
>         return ["text/plain"]

have u tried skipping this? Becaus as it's said here

> Could not satisfy the request Accept header.

there is an issue with the accept header not with the response header.

**Comment by fvitello** [comment]
Removed the comment on produces but still same issue.
Also removing the get_consumes the issue is still present.

Debugging the issue i saw that changing the response consent type the -H of the curl:

`curl -X GET "http://127.0.0.1:8000/api/subtask/2000000/parset/" -H  "accept: text/plain" -H  "X-CSRFToken: fwF4FV71kAo7OOBTropOvWUZsd4uUGlRIEfPU8nQolOxCsBmo16u2acKcRZqBNts"`

is "accept: text/plain", previously was "accept: application/json"

**Comment by chgad** [comment]
Maybe it's an issue with the supportet RequestRenderers as shown [here](https://stackoverflow.com/questions/30903951/django-doesnt-parse-a-custom-http-accept-header#30904124)

**Comment by fvitello** [comment]
Thanks, 
with a "PlainTextRenderer" the issue is solved but now everything in my django rest framework is plain text.
How can i apply the renderer to a specific api?
The @renderer_classes used here
https://www.django-rest-framework.org/api-guide/renderers/
is not recognized in my environment

**Comment by chgad** [comment]
Have you just setting the Classattribute `renderer_classes=[PlainTextRenderer,]`

**Comment by fvitello** [comment]
Yes, and using the classattribute renderer_classes=[PlainTextRenderer,] it works fot the entire view class. I would like to have a "function-based" renderer, is this possible?

**Comment by chgad** [comment]
Since your problem with this package is solved let's close the issue. 

For Further help contact me via e-mail .

**Comment by axnsan12** [comment]
As I understand this is resolved. Thanks @chgad!
