### ISSUE TITLE
Allow to show viewset even if permissions failing

### ISSUE THREAD

**Issue by Arti3DPlayer** [axnsan12/drf-yasg#593]
```
    def has_permission(self, request, view):
        parents_query_dict = view.get_parents_query_dict()
        try:
            user_id = int(parents_query_dict['user_id'])
        except (KeyError, ValueError):
            return False
        return user_id == request.user.id
```

I have a viewset with permission that check current user id and query param. Is this possible somehow disable that permission for swagger, because it is always False

**Comment by chgad** [comment]
Why would you do this? Without the provided permission anyone who got your docs-url can view the entries of any user he likes. I would highly recommend to NOT do what you are asking to do.

**Comment by Arti3DPlayer** [comment]
yes, my bad, I should put this into `has_object_permission`

> Without the provided permission anyone who got your docs-url can view the entries of any user he likes

I'm using nested router, so if user will have access to User object, then he will have access to this Object too.
