### ISSUE TITLE
How to set headers on response returning an array

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [axnsan12/drf-yasg#60]
I have a custom pagination class `MyPagination` subclassed from `PageNumberPagination` that puts the count and links to the first, prev, next and last pages in headers on the response. The end point returns an array without an envelope object. I would like to include this in the swagger docs. This is as far as I've gotten:
```python
class MyPaginatorInspector(inspectors.PaginatorInspector):
    def get_paginated_response(self, paginator, response_schema):
        assert response_schema.type == openapi.TYPE_ARRAY, "array return expected for paged response"
        paged_schema = None
        if isinstance(paginator, (MyPagination)):
            paged_schema = openapi.Schema(
                type=openapi.TYPE_ARRAY,
                items=response_schema,
                # The properties worked as long as type was openapi.TYPE_OBJECT
                properties=OrderedDict((
                    ('count', openapi.Parameter('number of elements in result',
                                                openapi.IN_HEADER, type=openapi.TYPE_INTEGER)),
                    ('first', openapi.Parameter('url to the first page in the result',
                                                openapi.IN_HEADER, type=openapi.TYPE_STRING)),
                    ('prev', openapi.Parameter('url to the previous page in the result',
                                               openapi.IN_HEADER, type=openapi.TYPE_STRING)),
                    ('next', openapi.Parameter('url to the next page in the result',
                                               openapi.IN_HEADER, type=openapi.TYPE_STRING)),
                    ('last', openapi.Parameter('url to the last page in the result',
                                               openapi.IN_HEADER, type=openapi.TYPE_STRING)),
                ))
            )

        return paged_schema

def get_list_schema_decorator():
    # ... snip
    return swagger_auto_schema(operation_description=operation_description,
                               manual_parameters=manual_parameters,
                               responses=responses,
                               paginator_inspectors=[MyPaginatorInspector]
                               )
```
but I get the error that "AssertionError at /swagger/: only object Schema can have properties".

Any pointers would be appreciated

**Comment by axnsan12** [comment]
Hello!

1. You cannot have ``Parameter``\ s nested in a ``Schema``, no matter if it is an array or object.
2. Header parameters or responses are sadly not very well supported as of now. The ``get_paginated_response`` method of ``PaginatorInspector`` only deals with wrapping the response schema, while you need to add header Parameters to the [response object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responseObject). I'd say you could get it done by overriding here: https://github.com/axnsan12/drf-yasg/blob/a211184478e6f0ca348312438c9c29d7b535b0fa/src/drf_yasg/inspectors/view.py#L209

**Comment by axnsan12** [comment]
I'm going to close this as it's just a question. If you feel that there is any actionable issue feel free to reopen (or submit a PR 😄 )
