### ISSUE TITLE
How to write @swagger_auto_schema for uploading a file?

### ISSUE THREAD

**Issue by Atidhaya** [axnsan12/drf-yasg#600]
Hello! I want to simply do the file uploading. After reading through the documentation, and reading issues in here. I came up with the following code, still. It doesn't seem to work as intended.

I decided to use manual_parameters because as the doc said, parameter can describe file uploads via type = file. but only as part of a form Operation. 

So I simply use openapi.Parameter and make my view use FormParser class. 

```
@swagger_auto_schema(
        operation_description='Upload container excel, if the columns and data are valid. Containers will be created. '
                              'If container with such name already exists, it will be update instead',
        operation_id='Upload container excel',
        tags=[tag],
        manual_parameters=[openapi.Parameter(
                            name="file",
                            in_=openapi.IN_FORM,
                            type=openapi.TYPE_FILE,
                            required=True,
                            description="Document"
                            )],
        responses={400: 'Invalid data in uploaded file',
                   200: 'Success'},
    )
    @action(detail=False, methods=['post'], parser_classes=(FormParser, ), name='upload-excel', url_path='upload-excel')
    def upload_excel(self, request):
        file = request.FILES.get('file')
        try:
            df = pd.read_excel(file)
      ...omitted code...
```

However, then I received this error. 

`drf_yasg.errors.SwaggerGenerationError: cannot instantiate nested serializer as Parameter`

There is #503  talking about this, but I'm not sure how to resolve it with my method. I did try adding 

```
def get_parsers(self):
    if getattr(self, 'swagger_fake_view', False):
        return []

    return super().get_parsers()
```

to my view. The problem still persists. 

I also tried to remove the parser classes, override auto_schema with my own, simply 

```
class ExcelUploadAutoSchema(SwaggerAutoSchema):

    def get_consumes(self):
        return ['multipart/form-data']
```

and 

```
 @swagger_auto_schema(
        auto_schema=ExcelUploadAutoSchema,
        operation_description='Upload container excel, if the columns and data are valid. Containers will be created. '
                              'If container with such name already exists, it will be update instead',
      .....
```

Still producing the same error. 

Did I miss anything? I would really appreciate the help!

**Comment by cheng2v** [comment]
You should assign MultiPartParser instead of FormParser to the parser_classes in action decorator .

**Comment by axnsan12** [comment]
I believe @cheng2v is right, it should work with MultiPartParser.

**Comment by dstrikerider** [comment]
Can any one tell me how to upload multiple files using swagger in django...
in short using openapi2.0 and drf_yasg.
