### ISSUE TITLE
Cannot use list query parameter for get function of APIView 😱 Could not render this component, see the console.

### ISSUE THREAD

**Issue by sri-vathsa** [axnsan12/drf-yasg#603]
```
list_param = openapi.Parameter('list', openapi.IN_QUERY, description="list param",
                               type=openapi.TYPE_ARRAY, items=openapi.TYPE_INTEGER)
```
I need to send a list of integers in the query of a get endpoint. Created the above parameter and wrapped the get method of an ```APIView``` class with the following
```
@swagger_auto_schema(manual_parameters=[list_param], responses={'200': sample_serializer} )
```
When I open the autogenerated swagger I am getting the following error:

😱 Could not render this component, see the console

**Comment by dedeye** [comment]
try items={'type':'integer'}

**Comment by axnsan12** [comment]
Yep, `items` should be `=openapi.Items(type=openapi.TYPE_INTEGER)` (or just plain `{'type': 'integer'}` as hinted by @dedeye)
