### ISSUE TITLE
support coreapi.autoschema

### ISSUE THREAD

**Issue by JorisBenschop** [axnsan12/drf-yasg#605]
Hi, I just swithced to yasg, and I noticed my manual parameters are ignored in the resulting swagger page. I user coreapi.AutoSchema.get_manual_fields to add these. The definitions of the parameters are in the ApiView. How do I get DRF-YASG to include these ?

```
class Django_API_Call(APIView):
    manual_fields = [
        coreapi.Field("list",
                      required=False,
                      location="query",
                      description="only return a list of available cron classes",
                      schema=coreschema.Boolean()),
        coreapi.Field("cron_class",
                      required=False,
                      location="query",
                      description="execute only this cron class",
                      schema=coreschema.String(), ),
    ]

    schema = AutoSchema(manual_fields=manual_fields)
    
    def get(self, request):
        return Response(data='data')
```

**Comment by axnsan12** [comment]
coreapi is deprecated and support will soon be removed from drf-yasg. Consider rewriting the manual parameters by following this documentation: https://drf-yasg.readthedocs.io/en/stable/custom_spec.html
