### ISSUE TITLE
ReDoc failed to render this spec

### ISSUE THREAD

**Issue by DimasInchidi** [axnsan12/drf-yasg#61]
if i add `'USE_SESSION_AUTH': False` or `'SHOW_REQUEST_HEADERS': True` to `SWAGGER_SETTINGS` i get page that said

> Oops... ReDoc failed to render this spec can't assign to property "_displayType" on false: not an object

just want to ask, is this something that should not appear or its normal?

**Comment by axnsan12** [comment]
Hello,

``USE_SESSION_AUTH`` only applies to swagger-ui and should not cause errors in ReDoc. I don't know where you're getting ``SHOW_REQUEST_HEADERS`` from, but it's not a setting supported by ``drf-yasg``.

**Comment by DimasInchidi** [comment]
apparently i realize that the reason is not because i add `'USE_SESSION_AUTH': False` or `'SHOW_REQUEST_HEADERS': True` to `SWAGGER_SETTINGS`
but specifically because i add those at `SECURITY_DEFINITIONS`

```
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        ....
        'ANYTHING': False
    }
}
```
this settings above will produce that error

**Comment by axnsan12** [comment]
I also do not know where you are getting ``'ANYTHING'`` from, but that's not valid OpenAPI either.

**Comment by DimasInchidi** [comment]
what i mean by `'ANYTHING'` is any key, thank you now i know that the error produced by invalid SECURITY_DEFINITIONS setting
