### ISSUE TITLE
Django rest swagger_auto_schema customize response body to API VERSION

### ISSUE THREAD

**Issue by bulkerke** [axnsan12/drf-yasg#616]
So I have 2 different api version (API v1 and v2). I want a different Swagger response for those because the output is different. I know that it needs to be done here in the view:

    responses={
                200: openapi.Response(
                    _(
                        "Successfully fetched the array of all sites where the user belongs to."
                    ),
                    SiteSerializer,
                )
            }

But I can't access the "version" (it is stored in self.request.version. 
This is my version url file

    router = routers.DefaultRouter()
    app_name = "v1"
    
    schema_view = get_schema_view(
        openapi.Info(
            title="API",
            default_version="v1",
            description="## Admin dashboard"
        ),
        # validators=['flex', 'ssv'],
        public=True,
        permission_classes=(permissions.AllowAny,),
    )
    
    
    v1_urls = [...]

Do I need to use this schema view to access the version number or use self? and how?

**Comment by axnsan12** [comment]
You can achieve this by overriding get_response_serializers https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.inspectors.SwaggerAutoSchema.get_response_serializers. You should then then be able to use `self.request.version` as usual - `self.request` will be a mocked request object with appropriate attributes set.

See also https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#swaggerautoschema
