### ISSUE TITLE
Is there a way to certain include list of url patterns ?

### ISSUE THREAD

**Issue by Yahyaali1** [axnsan12/drf-yasg#617]
I am trying to include only certain url patterns to be include in the documentation. Is there a way to achieve this ? 

for examples 
url patterns 
```
{base_url}/v1/..
{base_url}/v2/..
{base_url}/v3/..
```
I only want to include v2 and v3 urls in the documentation. 

Note
v2 and v3 then have further patterns such as v2/api etc.

**Comment by chgad** [comment]
Maybe have a look at the solution shown in #465 .

**Comment by axnsan12** [comment]
Correct, you can use the patterns or urlconf arguments of get_schema_view.
