### ISSUE TITLE
Hello developer, can you add path configuration prefix to configuration items?

### ISSUE THREAD

**Issue by aeasringnar** [axnsan12/drf-yasg#618]
Hello developer, I use Nginx to deploy applications during the development process, because I use path to deploy multiple applications, so in Swagger-UI I found that Base-Url can be modified in the configuration, but path is not. Can your add prefix to the configuration?

**Comment by chgad** [comment]
What are you exactly deploying? 
Are you doing something like App1 under `my.example.com/app1` and App2 under `my.example.com/app2`?
Do you want two separate swagger docs for it?

**Comment by aeasringnar** [comment]
You can open my document to view **http://test.shedblood.cn/django/swagger/**.**Base-Url** can be configured, but the following **path** cannot be configured. My example is **Base URL: test.shedblood.cn/django**, where **django** modified the source code and added it.

**Comment by aeasringnar** [comment]
You can open my document to view **http://test.shedblood.cn/django/swagger/**. _Base-Url_ can be configured, but the following path cannot be configured. My example is Base **URL: test.shedblood.cn/django**, where **django** modified the source code and added it.

**Comment by axnsan12** [comment]
You should use SCRIPT_NAME (https://www.python.org/dev/peps/pep-0333/#environ-variables) or FORCE_SCRIPT_NAME (https://docs.djangoproject.com/en/3.1/ref/settings/#force-script-name) to set the path served by the reverse proxy. 

This is what is required for django to properly generate reverse() urls.
