### ISSUE TITLE
TypeError: Decimal

### ISSUE THREAD

**Issue by savvaoff** [axnsan12/drf-yasg#62]
getting this:
"TypeError: Object of type 'Decimal' is not JSON serializable"

for a model with such field:
rate = models.DecimalField(_('Rate'), max_digits=6, decimal_places=3, default=Decimal('0.0'), validators=[MinValueValidator(Decimal('0.0'))])

**Comment by axnsan12** [comment]
Hello,

Can you provide a more detailed stack trace? Thanks.
