### ISSUE TITLE
Empty request _body

### ISSUE THREAD

**Issue by atb00ker** [axnsan12/drf-yasg#626]
I have a view that utilizes `CreateAPIView` from Django DRF and takes a `post` request that does not contain any post data only a parameter in path.

![del12](https://user-images.githubusercontent.com/24985760/90531617-e49a9700-e193-11ea-9025-fe3f35e3ef43.png)

The `data` in the parameter section is not required.
However, an empty dict is still here, can I remove the data section?

(Sorry for asking here, I cannot find a community mailing list in the docs.)

**Comment by jcarizza** [comment]
I'm with the same issue...

**Comment by atb00ker** [comment]
Thanks, `no_body` worked, closing the issue.
