### ISSUE TITLE
Wrong Django3 version in tox file

### ISSUE THREAD

**Issue by tomwojcik** [axnsan12/drf-yasg#634]
That doesn't seem to be Django 3.

https://github.com/axnsan12/drf-yasg/blob/9ccf24c27ad46db4f566170553d49d687b6d21d6/tox.ini#L29

**Comment by johnthagen** [comment]
Wow, good catch @tomwojcik. A little scary to be running Django 3 in production without this library being tested.

I do hope @axnsan12 finds time to merge PRs (#590).

**Comment by axnsan12** [comment]
Fixed now. Thanks for the report.
