### ISSUE TITLE
How to tag whole ViewSet?

### ISSUE THREAD

**Issue by TmLev** [axnsan12/drf-yasg#651]
I have the following ViewSet:

```python
class AuthorViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer
    permission_classes = [permissions.AllowAny]

    # note that no methods are overridden
```

I want `drf_yasg` to generate custom schema such that all action methods will be tagged as `Authors`.

The documentation says that my options are to either decorate each method by declaring it and using `@swagger_auto_schema` like so:
```python
class AuthorViewSet(viewsets.ModelViewSet):
    # ...
    @swagger_auto_schema(tags=["Authors"])
    def list(self, request, *args, **kwargs):
        return super().list(request, *args, **kwargs)
```

Or use Django's `@method_decorator` like so:
```python
@method_decorator(name="list", decorator=swagger_auto_schema(tags=["Authors"]))
class AuthorViewSet(viewsets.ModelViewSet):
    # ...
```

Both options require tedious repetition which I would like to avoid. 

I've also tried to implement my own decorator:
```python
def decorate_viewset_methods(names, decorator):
    if names == "__all__":
        names = [
            "create",
            "retrieve",
            "update",
            "partial_update",
            "destroy",
            "list",
        ]

    def decorate(cls):
        for name in names:
            method = getattr(cls, name)
            setattr(cls, name, decorator(method))

    return decorate
```

But it didn't quite work out.

So my question is how can I decorate all action methods at once?

**Comment by axnsan12** [comment]
You can override SwaggerAutoSchema#get_tags to implement any logic you want - https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.inspectors.SwaggerAutoSchema.get_tags

For example, you might generate the tags based on the class name, or based on a class attribute (using self.view, self.path, self.method).

**Comment by TmLev** [comment]
Wouldn't it be nice just to specify tags in `APIView` field?
```python3
class SomeView(APIView):
    queryset = SomeModel.objects.all()
    serializer_class = SomeModelSerializer
    schema_tags = ["model", "list"]
```

**Comment by mohitbestpeers** [comment]
@TmLev, Did you find any solution?

**Comment by TmLev** [comment]
@mohitbestpeers, I think my approach with decorator was just missing a return statement:
```python
def decorate_viewset_methods(names, decorator):
    if names == "__all__":
        names = [
            "create",
            "retrieve",
            "update",
            "partial_update",
            "destroy",
            "list",
        ]

    def decorate(cls):
        for name in names:
            method = getattr(cls, name)
            setattr(cls, name, decorator(method))
        # ⬇️ Note this line.
        return cls

    return decorate
```

This _should_ work, although I haven't checked.

Also, someone on StackOverlfow suggested customising `SwaggerAutoSchema`:
https://stackoverflow.com/questions/64185352/how-to-tag-whole-viewset-in-drf-yasg

**Comment by mohitbestpeers** [comment]
@TmLev , tysm 
So should I use it like 
`@decorate_viewset_methods(name="__all__", decorator="swagger_auto_schema(tags=['something'])")`

**Comment by TmLev** [comment]
Yeah, except you'll want to remove double quotes around the `swagger_auto_schema()` like so:
```python
@decorate_viewset_methods(name="__all__", decorator=swagger_auto_schema(tags=['something']))
```

**Comment by mohitbestpeers** [comment]
> Yeah, except you'll want to remove double quotes around the `swagger_auto_schema()` like so:
> 
> ```python
> @decorate_viewset_methods(name="__all__", decorator=swagger_auto_schema(tags=['something']))
> ```

Thank you so much @TmLev, It worked.

**Comment by hantsaniala** [comment]
Thanks for the lead @TmLev, here is an improved version of mine. Because my viewset class inherits from a BaseViewSet class, all class that inherit this parent are affected by too.

```python
from django.utils.decorators import method_decorator


def decorate_viewset_methods(name, decorator):
    if name == "__all__":
        names = [
            "create",
            "retrieve",
            "update",
            "partial_update",
            "destroy",
            "list",
        ]

    def decorate(cls):
        for name in names:
            if hasattr(cls, name):
                # Retrieve the actual function from the class
                method = getattr(cls, name)
                # Apply the decorator and bind it back to the class
                decorated_method = method_decorator(decorator)(method)
                setattr(cls, name, decorated_method)
        return cls

    return decorate
```
