### ISSUE TITLE
Demo sourcecode

### ISSUE THREAD

**Issue by esseti** [axnsan12/drf-yasg#655]
Is there anywhere the sourcecode of the project that generates the "demo": https://drf-yasg-demo.herokuapp.com/cached/swagger/

I would love to see how the code has been documented to see how it works, but i can't find a project where the code is.

**Comment by arponpes** [comment]
Hi!

If I understood correctly you want this: https://github.com/axnsan12/drf-yasg/tree/master/testproj

**Comment by esseti** [comment]
yes! thanks.
