### ISSUE TITLE
Blank Page After Deployment

### ISSUE THREAD

**Issue by keremvatandas** [axnsan12/drf-yasg#670]
Hello, swagger works on localhost without any problems. But after deploying to the server, the blank page comes up. There is no error message.

My Nginx Conf,
```

...
location /swagger/ {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass https://<IP>/swagger/;
}
....
```

I'm using drf-yasg==1.17.1 version. Has anyone had a problem like this?

![Screen Shot 2020-11-05 at 12 13 55](https://user-images.githubusercontent.com/6032205/98222039-6616ef80-1f61-11eb-840f-513a45b21715.png)

**Comment by keremvatandas** [comment]
I resolve the problem. My Nginx configuration is located on the frontend machine. It is necessary to specify the static file as proxy_pass.

**Comment by MisanthropicDeity** [comment]
Can you give a detailed solution @keremvatandas

**Comment by st3fus** [comment]
Yeah, can you post a detailed solution please? Got the same issue @keremvatandas
