### ISSUE TITLE
base_url issue in SWAGGER UI

### ISSUE THREAD

**Issue by Chidambaranathan14** [axnsan12/drf-yasg#673]
Could you please help me to resolve this issue https://stackoverflow.com/questions/64784245/base-url-issues-in-drf-yasg-swagger

**Comment by Chidambaranathan14** [comment]
Found the solution. Hence closing it

**Comment by hubertokf** [comment]
what was te solution?

**Comment by surendra-swifly** [comment]
What's the solution ? Can you reply?
