### ISSUE TITLE
Correct way to describe query parameters using serializers

### ISSUE THREAD

**Issue by arlopezg** [axnsan12/drf-yasg#677]
Hello,

I've started to document an API with YASG. So far it's worked very well, the only trouble I've had has been **using nested serializers**, and the doubts stem from:

- The docs saying that "nested serializers (...) [will cause the schema generation to fail with an error](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.utils.swagger_auto_schema)" when using `query_serializer` to describe the request params.
- My view's request depending on smaller, utility serializers, that are reused across many other requests

**Example:**

```python
# serializers.py
from rest_framework import serializers

class SomeObjectSerializer(serializers.Serializer):    
    id = serializers.IntegerField()
    name = serializers.CharField(required=False, allow_blank=False)

class MultipleIncludesSerializer(serializers.Serializer):
    include = ObjectRequestSerializer(many=True, allow_empty=False)

class MyReportRequestSerializer(serializers.Serializer): 
    # This is the one used in YASG's `query_serializer`
    some_field = MultipleIncludesSerializer()
    another_field = serializers.CharField()
```

```python
# view.py
from drf_yasg.utils import swagger_auto_schema

from .serializers import MyReportRequestSerializer

class ReportViewSet():
    @swagger_auto_schema(
        operation_id="Example request",
        query_serializer=MyReportRequestSerializer
    )
    def create(self, request):
        (...)
```

**Result**
If I try to generate my schema, I get the following error: 

```drf_yasg.errors.SwaggerGenerationError: cannot instantiate nested serializer as Parameter```

I get that nested params are not allowed in `query_serializer` - but what else can I do to describe this request parameters?

**Comment by dineshtrivedi** [comment]
Did you find how to do this, @arlopezg ?

I am currently having the same issue

**Comment by arlopezg** [comment]
I ended up using [drf-spectacular](https://github.com/tfranzel/drf-spectacular) and it worked out just fine.

**Comment by dineshtrivedi** [comment]
Awesome, @arlopezg !
Thank you very much, I will check it out

**Comment by Bubbassauro** [comment]
Just leaving this here in case other people are having trouble with this.
I used the `query_serializer` parameter:

```python
from rest_framework import serializers
from rest_framework import viewsets
from drf_yasg.utils import swagger_auto_schema

class CustomParametersSerializer(serializers.Serializer):
    myparam = serializers.CharField(help_text="My manual querystring parameter")

class MyViewSet(viewsets.ViewSet):
    @swagger_auto_schema(query_serializer=CodeValidationSerializer)
    def my_route(self, request):
        ...
```
