### ISSUE TITLE
ModuleNotFoundError: No module named 'rest_framework_gisdrf_yasg'

### ISSUE THREAD

**Issue by Delios82** [axnsan12/drf-yasg#679]
Hi, I have installed this plugin for Django 3.1.4, but when I launch runserver I get the error "ModuleNotFoundError: No module named 'rest_framework_gisdrf_yasg'"

**Comment by axnsan12** [comment]
You're missing a comma in your vertical list of INSTALLED_APPS. This causes the two consecutive string literals to be concatenated by the compiler.
