### ISSUE TITLE
Having both lookup_field (pointing to a non string field) and lookup_value_regex on a viewset explodes

### ISSUE THREAD

**Issue by gcbirzan** [axnsan12/drf-yasg#68]
Firstly, this is incredibly hard to debug, as no info about where this happens, one has to use a debugger to find out. 

Secondly, this is just wrong. It shouldn't be up to the swagger generator to decide whether a regular expression will end up being correct. And, even if it was, it should be, at best, a warning.

**Comment by axnsan12** [comment]
Hello!

More details, like a concrete view/serializer that manifests the problem, and exactly which part blows up, what errors are thrown, etc. would help in pinpointing and solving the problem 😄

**Comment by gcbirzan** [comment]
It's not trivial to show you an exception/example until tomorrow morning EU time, but:

https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/openapi.py#L365 - you end up with a pattern here, but the type is integer.

And you end up with a pattern there, because of https://github.com/axnsan12/drf-yasg/blob/a211184478e6f0ca348312438c9c29d7b535b0fa/src/drf_yasg/generators.py#L408

But, basically, any ModelViewset that has, say `lookup_field = 'id'` and `lookup_value_regex = '\d+'` will reproduce this problem. I think you also need a queryset, but that might be just something I misremember.

**Comment by axnsan12** [comment]
I guess see your point. I suppose the proposed solution would be to forego setting a pattern if the lookup_field is not of type string.

**Comment by gcbirzan** [comment]
That's one solution. I put forth that a better solution is to not have this limitation. It makes no sense, nor does it actually prevent any "huge" mistakes. 

If you insist, however, on breaking on things that are perfectly valid, since it's supposed to check for common mistakes, maybe it'd be nice to mention _where_ the common mistake happens. Currently, that's like being told "ValueError happened in one of your files" when you encounter such an exception.

**Comment by axnsan12** [comment]
Hello,

You are right it is not the job of this library to check and tell you how to write code, but it IS its job to respect the specification of the document it's trying to generate, which [says about the pattern field](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.2.3):

>    5.2.3.2.  Conditions for successful validation
>    A _*string*_ instance is considered valid if the regular expression matches the instance successfully.

The ``raise AssertionError("pattern can only be used when type is string")`` check you are pointing to (and all other sanity checks for types in the ``openapi`` module) is intented to prevent people from directly writing ``openapi.Parameter(type=openapi.TYPE_INTEGER, pattern="blabla")``. It should, barring a bug, never be triggered by the library itself when parsing views and serializers.

Which means that, while in DRF it is valid to have both a ``lookup_field`` and ``lookup_value_regex`` for routing purposes, in OpenAPI it is only valid to apply a ``pattern`` to a ``string`` Parameter or Schema. Which means that it is no mistake of your code, but a bug of this library where it's improperly generating a ``pattern`` for ``integer`` (or any other non-``string``) fields.
