### ISSUE TITLE
why got post data in query_params dict ?

### ISSUE THREAD

**Issue by pyfs** [axnsan12/drf-yasg#697]
```python
class Demo2(APIView):
    authentication_classes = []
    permission_classes = []

    @swagger_auto_schema(query_serializer=ApiSerializer)
    def post(self, request, *args, **kwargs) -> Response:
        return Response(data='get demo2', status=status.HTTP_200_OK)
```

when try it out, why post data just appear in query_params dict ?

![image](https://user-images.githubusercontent.com/67151035/106688584-5c0c9780-6609-11eb-98e4-413834175aa7.png)

**Comment by DVKunion** [comment]
I got the same problem and using by this way to resolve:
`@swagger_auto_schema(request_body=Serializer, responses={'201': SuccessSerializer})`
then the post param will in request body,not url.
hope useful for you.

**Comment by pyfs** [comment]
glad to here your suggestion; i will try it out!  thank u vmuch !
