### ISSUE TITLE
Request parameters example not changing for custom urls in ModelViewset

### ISSUE THREAD

**Issue by nicholasgcoles** [axnsan12/drf-yasg#73]
Hello

Sorry not sure if this is a bug or intended this way!

Basically I have a ModelViewSet which I set ```schema = AutoSchema()``` 

However when I try add a custom function within the ModelViewSet, it does not update to the correct request input parameters in the docs.
```
class UploadViewSet(viewsets.ModelViewSet):
    """
    Model ViewSet handling user api calls
    """
    schema = AutoSchema()
    permission_classes = (UploadPermissions,)
    queryset = Upload.objects.all()
    serializer_class = UploadSerializer

    @list_route(
        methods=['POST'],
        schema=ManualSchema(fields=[
            coreapi.Field(
                "conditions",
                required=True,
                location="query",
                schema=coreschema.Object(),
                description='Conditions field',
                type='string',
                example='123'
            ),
            coreapi.Field(
                "expiration",
                required=True,
                location="query",
                schema=coreschema.String(),
                description='Expiration field',
                type='string',
                example='123'
            )
        ]),
        permission_classes=[],
        authentication_classes=[]
    )
    def handle_upload_request(self, request):
          ## Handle request here ###
```

In the swagger / redoc docs it shows all the urls correctly:

![image](https://user-images.githubusercontent.com/1975028/36734561-88201cea-1bdc-11e8-9509-0033d3d8243d.png)

The default model viewset models show the request input data as
```
{started: 'string', name: 'string', type: 'string', priority: integer}
```

However when I check the request input data for my custom url it is the same as above. Instead I would expect it to be something along the lines of:
```
{condtions: 'string', expiration: 'string'}
```

Perhaps I am doing something wrong or this is not supported?

I hope I have explained this problem well. Thanks so much for the help!

**Comment by axnsan12** [comment]
Hello.

``AutoSchema`` and ``ManualSchema`` are part of Django REST Framework. ``drf-yasg`` replaces those classes with its own functionality. So in fact, the code you posted has no relation to this library.

A look through [the documentation](https://drf-yasg.readthedocs.io/en/stable/) might help clear things up.

**Comment by nicholasgcoles** [comment]
Thanks for the reply! 

Sorry about that, I had thought that perhaps the library interpreted it.

Had a look through the documentation (and your git repo) and managed to achieve what I wanted doing the following:
```
@swagger_auto_schema(
    request_body=openapi.Schema(
        type=openapi.TYPE_OBJECT,
        required=['conditions', 'expiration'],
        properties={
            'conditions': openapi.Schema(type=openapi.TYPE_STRING),
            'expiration': openapi.Schema(type=openapi.TYPE_STRING)
        },
    ),
    responses={
        status.HTTP_200_OK: openapi.Response(
            schema=openapi.Schema(
                type=openapi.TYPE_OBJECT,
                properties={
                    'policy': openapi.Schema(type=openapi.TYPE_STRING),
                    'signature': openapi.Schema(type=openapi.TYPE_STRING)
                }
            ),
            description='Signed policy and signature of upload request'
        )
    }
)
@list_route(methods=['post'])
def handle_upload_request(self, request):
      ### Handle upload request ###
```

Thanks again for the awesome project!
