### ISSUE TITLE
Migrate from Travis CI to Github actions

### ISSUE THREAD

**Issue by JoelLefkowitz** [axnsan12/drf-yasg#739]
The Travis CI pipeline is no longer running for free. I would like to switch over to github actions so that we can have PRs automatically checked. I'm happy to add the configuration files. Does anyone have other suggestions before I go ahead?

**Comment by NeOneSoft** [comment]
I'm very agree with you @JoelLefkowitz since in my humble opinion git hub actions is already a great CI tool for git repos!!

**Comment by JoelLefkowitz** [comment]
Linked PR #741
