### ISSUE TITLE
License and source status unclear for some minimized files

### ISSUE THREAD

**Issue by tijuca** [axnsan12/drf-yasg#756]
# Bug Report

## Description
The upstream source of drf-yasg ships some minimized JS files where the source and by this the license isn't fully clear.

The greater background:
I packaged drf-yasg within Debian as [drf-yasg-nonfree](https://tracker.debian.org/pkg/drf-yasg-nonfree). It's placed within the non-free part (which isn't officially Debian due non-free) as some file are minimized and no source for these files nor a minimal information how to rebuild the minimized files can be rebuilt are added. The ftp-masters want to have a more clear state about the files where the license and source they are taken from isn't fully clear.

In detail these are the *.js files in [the folder src/drf_yasg/static/drf-yasg](https://github.com/axnsan12/drf-yasg/tree/master/src/drf_yasg/static/drf-yasg) and beyond.

So far I could a do research I found out the following things.

[src/drf_yasg/static/drf-yasg/immutable.min.js ](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/static/drf-yasg/immutable.min.js) is based on https://github.com/immutable-js/immutable-js/releases/tag/v3.8.2

[src/drf_yasg/static/drf-yasg/url-polyfill.min.js](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/static/drf-yasg/url-polyfill.min.js) is based on https://github.com/lifaon74/url-polyfill

[src/drf_yasg/static/drf-yasg/insQ.min.js](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/static/drf-yasg/insQ.min.js) no source can be found, license is readable from the minimized file.

[src/drf_yasg/static/drf-yasg/redoc-init.js](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/static/drf-yasg/redoc-init.js) no source can be found, I assume the source is taken from https://github.com/Redocly/redoc/ or the minimized file is somehow taken from there. By this it's assumed the license would be Expat as this is the license of GitHub tree.

[src/drf_yasg/static/drf-yasg/swagger-ui-init.js](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/static/drf-yasg/swagger-ui-init.js) Partially the same as before, but it's mostly obvious the source must be taken from https://github.com/swagger-api

[src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js) This seems to be a minimized version of the old redoc development tree v1.x. Given the information visible on https://github.com/Redocly/redoc/tree/v1.x it's assumed the file is licensed under the MIT license in the end.

[src/drf_yasg/static/drf-yasg/redoc/redoc.min.js](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/static/drf-yasg/redoc/redoc.min.js) looks like it's created from multiple source files from https://github.com/Redocly/redoc

[src/drf_yasg/static/drf-yasg/swagger-ui-dist/*](https://github.com/axnsan12/drf-yasg/tree/master/src/drf_yasg/static/drf-yasg/swagger-ui-dist) Most of the files are minimized and no information is given were the files are originally where taken from. They seems to originally taken from https://github.com/swagger-api/swagger-ui/tree/master/dist and https://github.com/swagger-api/swagger-ui/tree/master/swagger-ui-dist-package

## Is this a regression?
This is not a technical regression, but make the legal situation unclear (from the POV of Debian). Debian wants to be clear which license is applied for every file.

So it would be helpful if the situation of the above listed files within the folders could be make clear by some additional added information about the files, the source of the files and the used license.

Even more appreciated would be the shipping of the source files and how the minimized files would be created from these source files.

**Comment by axnsan12** [comment]
Hello

>  nor a minimal information how to rebuild the minimized files can be rebuilt are added. 

https://github.com/axnsan12/drf-yasg/blob/master/update-ui.sh

All swagger-ui and redoc related files are versions downloaded/linked from their respective github repos and/or npm packages
https://github.com/Redocly/redoc
https://github.com/swagger-api/swagger-ui

swagger-ui-init.js and redoc-init.js are authored by me, as can be seen from their git histories:
https://github.com/axnsan12/drf-yasg/commits/master/src/drf_yasg/static/drf-yasg/swagger-ui-init.js
https://github.com/axnsan12/drf-yasg/commits/master/src/drf_yasg/static/drf-yasg/redoc-init.js

and thus subject to the same license as the rest of the repo.

The source of insQ.min.js is this repo: https://github.com/naugtur/insertionQuery

Hope that clears things up.

If you feel that any potential changes would help clarify the licensing of these dependencies, please feel free to open a PR and I'll try to have a look.

**Comment by tijuca** [comment]
Hi,

as I understand your answer it's not that helpful to me as the FTP-Master are (happily) strict about the DFSG, There are still then some files not clear. You helped to make clear the situation on some of the files in question, but not all of them and the FTP-Master will reject any package build for the Debian archive as long not all parts are clear. So I'd love to get the license situation more clear, the base source of this package here is DFSG conform and the package within the Debian archive could be also completely free regarding the DFSG if I can rebuild the whole package from source.

Debian is considering minimized code as non-free if it can't rebuild from source, also source code that is not clearly covered by a DFSG license. Putting license information within the header of a file helps always to make the copyright holder and the used license clear. I now there are things that all of us would prefer to make instead of doing boring legal stuff, but it's important.

I can try to make some PRs on some parts but I'm not able to do all parts as I'm not the owner of the source.

Some more comments in detail:

> All swagger-ui and redoc related files are versions downloaded/linked from their respective github repos and/or npm packages
https://github.com/Redocly/redoc
https://github.com/swagger-api/swagger-ui

Well, for you and people deeply involved in drf-yasg it might be obvious were the file were taken from, for me it was not. So some comment about the origin would help to get a clear information.

> swagger-ui-init.js and redoc-init.js are authored by me, as can be seen from their git histories:
https://github.com/axnsan12/drf-yasg/commits/master/src/drf_yasg/static/drf-yasg/swagger-ui-init.js
https://github.com/axnsan12/drf-yasg/commits/master/src/drf_yasg/static/drf-yasg/redoc-init.js

Git history isn't that helpful here, it can be faked at anytime and by anyone that has access to the tree, please add some legal information within the head of the files.

> The source of insQ.min.js is this repo: https://github.com/naugtur/insertionQuery

Could the non-minimized source please added to the tree? (The source tree isn't providing any license information btw. :smile: , I know NPM packages are mostly MIT licensed). As written Debian will be happy if the non-minimized source is available as we can rebuild the minimized stuff by our self then.

Can you tell also please something about these files?

> src/drf_yasg/static/drf-yasg/immutable.min.js is based on https://github.com/immutable-js/immutable-js/releases/tag/v3.8.2
src/drf_yasg/static/drf-yasg/url-polyfill.min.js is based on https://github.com/lifaon74/url-polyfill
src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js This seems to be a minimized version of the old redoc development tree v1.x. Given the information visible on https://github.com/Redocly/redoc/tree/v1.x it's assumed the file is licensed under the MIT license in the end.
src/drf_yasg/static/drf-yasg/redoc/redoc.min.js looks like it's created from multiple source files from https://github.com/Redocly/redoc
src/drf_yasg/static/drf-yasg/swagger-ui-dist/* Most of the files are minimized and no information is given were the files are originally where taken from. They seems to originally taken from https://github.com/swagger-api/swagger-ui/tree/master/dist and https://github.com/swagger-api/swagger-ui/tree/master/swagger-ui-dist-package

Any way thanks for your time!
I'm willing to work on the things in question, but I'll need help to get things done well.

**Comment by axnsan12** [comment]
> Can you tell also please something about these files?

Your analysis is accurate.

> src/drf_yasg/static/drf-yasg/url-polyfill.min.js

It's 2021 and we can hopefully move on from supporting IE11. I think I'll go ahead and remove this.

> src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js
> src/drf_yasg/static/drf-yasg/redoc/redoc.min.js
> src/drf_yasg/static/drf-yasg/swagger-ui-dist/*

`rm -f redoc/* redoc-old/* swagger-ui-dist/*` and running the commands in [update-ui.sh](https://github.com/axnsan12/drf-yasg/blob/master/update-ui.sh) (replace `npm update` by `npm ci` to use the frozen version in package-lock.json) should bring you identical files.

**Comment by tijuca** [comment]
I think we can close this now. :-)
Thanks for your cooperation and explanations! The FTP-Masters on Debian did have accepted my updated packaging work recently (based on the outcome of this report!), now the non-free part in Debian is providing also a package called `drf-yasg-nonfree`.

https://tracker.debian.org/pkg/drf-yasg-nonfree
