### ISSUE TITLE
Identically named serializers seem to confuse drf-yasg

### ISSUE THREAD

**Issue by beaugunderson** [axnsan12/drf-yasg#77]
We had two `PatientSerializer`s defined in our project; one of them was used for both views in the Swagger output when in fact each view used a different `PatientSerializer`; my workaround was to rename one of them (probably best that they are not identically named, but still an issue that might bite someone else)

**Comment by axnsan12** [comment]
Hello!

This is [known and documented](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#serializer-meta-nested-class) behaviour. I pondered a bit at the time and conisdered that it's preferable to the alternative (throwing an error). You can follow the steps from the link to resolve the conflict without having to rename the class.

**Comment by axnsan12** [comment]
I'm going to close this off for now. If you have a suggestion about how this situation could be handled better, feel free to reopen it.
