### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by JackLeo** [axnsan12/drf-yasg#771]
# Feature Request

## Description

`Setup.py` reads `README.rst` and limits python compatibility up to 3.9. DRF does support Python 3.10. 
Is there a particular reason or list of bugs why 3.10 is not supported?

## Describe the solution you'd like

Update `README.rst` to list Python 3.10

## Describe alternatives you've considered

N/A

**Comment by JackLeo** [comment]
Apologies if spam. Search did not result in anything in the issues/PRs related to this, just DRF 3.10 version support.

**Comment by JoelLefkowitz** [comment]
Thanks for the suggestion @JackLeo, #758 contains some of the changes for python3.10. The tox targets and GitHub actions matrix will be updated to include python3.10 once support for all its features have been implemented.
