### ISSUE TITLE
Don't display fields of type HiddenField

### ISSUE THREAD

**Issue by therefromhere** [axnsan12/drf-yasg#78]
Hi,   It seems that drf-yasg doesn't support hiding serializers.HiddenField's yet?  A hidden field in my serializer is showing up in the example data and model docs.

It looks like this is a known issue due to this TODO - https://github.com/axnsan12/drf-yasg/blob/9ad55bac9931a93ba2a9f7fd9f8693a0f8070c38/src/drf_yasg/inspectors/field.py#L472 but raising it.

**Comment by axnsan12** [comment]
Hello!

Yes, your interpretation is right, I never really used ``HiddenField`` so I didn't know what the proper behavior for it would be. Your PR is very welcome.

**Comment by break11** [comment]
So, It is not working now, HiddenFields in django rest serializers did not hidden in swagger generated doc...
May be some other field inspectors unhiding that field again?

**Comment by break11** [comment]
Wow, maybe I was wrong, I'm using a small function to create a serializer meta class "genBaseMeta". My simple function gives all subserializers the same "ref_name" - and that's wrong. And when I give the correct "ref_name" to each serializer, and it is different, everything works fine.
