### ISSUE TITLE
Content-Type not displayed correctly

### ISSUE THREAD

**Issue by creyD** [axnsan12/drf-yasg#783]
# Bug Report

## Description

The content type 'image/png' of responses is not visible in the swagger config. This is an issue because on one endpoint we want to serve images directly through the API. Even though this is possible via rest_framework, it is not applied in the swagger view and the generator therefore. Is there another solution for this? Or is it just a bug which/ missing feature?

## Is this a regression?

No

## Minimal Reproduction

```python

Response(content, content_type="image/png")
```

## Stack trace / Error message

There is no error message or exception, it works returning the image, but it doesn't show the correct content type.

**Comment by PaulWay** [comment]
How does the OpenAPI standard handle this?  I get that you can set any content type, but does it then require you to describe that return value in any way?

**Comment by creyD** [comment]
I don't see anything at first glance, but then again, they only really go into detail about the json content. https://spec.openapis.org/oas/v3.1.0

**Comment by PaulWay** [comment]
You can definitely specify the output content type, but then in OpenAPI you have to specify the actual construction of the output.  It might be possible to just describe it as a big string of arbitrary size.

However, the problem I think you're experiencing is that AFAICS `drf-yasg` picks up the content type from the renderers on the output, not the `content_type` return passed.  I.e. it does not call the view method to see what output type is generated, it looks at the viewset class's renderer list.  So I think this may be addressed in `rest-framework` and not in `drf-yasg` per se.
