### ISSUE TITLE
这个 Swagger logo 可以替换吗？或者删除

### ISSUE THREAD

**Issue by wuqiang-001** [axnsan12/drf-yasg#789]
![image](https://user-images.githubusercontent.com/85499933/166208381-acaf4951-a24a-432a-b304-0e0f658678a9.png)

**Comment by wuqiang-001** [comment]
对的，怎么实现呢？

**Comment by wuqiang-001** [comment]
> 

怎么实现呢？

**Comment by creyD** [comment]
One way I see for now would be to use your own `SwaggerUIRenderer(_UIRenderer)` ([code](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/renderers.py) and [docs](https://drf-yasg.readthedocs.io/en/stable/custom_ui.html)) with a custom template. Like Joel said, there is not yet a separate setting for this, but you could build it yourself for now.
