### ISSUE TITLE
Is it possible to show multiple openapi schemas in a response?

### ISSUE THREAD

**Issue by Gilions** [axnsan12/drf-yasg#825]
## Description

If API returns different answers depending on the situation.

Example code:
```
responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                  previous:
                    type: string
                  results:
                      oneOf:
                        - $ref: '#/components/schemas/BaseStocks'
                        - $ref: '#/components/schemas/Apteka36.6Stocks'
                        - $ref: '#/components/schemas/FarmiyaStocks'
                        - $ref: '#/components/schemas/MailruStocks'
                        - $ref: '#/components/schemas/NeofarmStocks'
                        - $ref: '#/components/schemas/YandexStock'
                        - $ref: '#/components/schemas/UtekaStocks'
```
It looks like this in swagпer 

<img width="642" alt="Screenshot 2022-12-06 at 11 08 16" src="https://user-images.githubusercontent.com/68146917/205868361-bb3c39b2-d896-4683-ba5b-27feae048d6e.png">

Is this functionality available?

**Comment by shispt** [comment]
Do you find any solution? I'm just curious about how to implement this.

**Comment by Gilions** [comment]
@shispt For this implementation you need to use OpenAPI 3.0.  Unfortunately, [drf-yasg](https://drf-yasg.readthedocs.io/en/stable/readme.html#openapi-3-0-note) does not support OpenAPI 3.0. For this implementation, I used [drf-spectacular](https://github.com/tfranzel/drf-spectacular).  It is implemented there with [PolymorphicProxySerializer](https://drf-spectacular.readthedocs.io/en/latest/drf_spectacular.html?highlight=PolymorphicProxySerializer#drf_spectacular.utils.PolymorphicProxySerializer)

**Comment by shispt** [comment]
@Gilions Thank you!
