### ISSUE TITLE
Use PyYAML instead of ruamel.yaml

### ISSUE THREAD

**Issue by sevdog** [axnsan12/drf-yasg#833]
## Description
PyYAML is the [default YAML serializer used in Django](https://github.com/django/django/blob/main/django/core/serializers/pyyaml.py) and also the suggested DRF [YAML renderer uses it](https://jpadilla.github.io/django-rest-framework-yaml/).

If someone uses these library with drf-yasg he is going to have two different YAML parsers, which is quite useless.

Also the concurrent library [drf-spectacular uses pyyaml](https://github.com/tfranzel/drf-spectacular/blob/24b8a9890d59900d102490a48e286d08cdcc7ab5/requirements/base.txt#L4).

## Proposal
If there is no particular reason in using `ruamel.yaml` (whcih as of now means "to support YAML 1.2") it will be better to replace it with `pyyaml` (for uniformity) or move it as an optional dependency (since YAML relies on a third party library which is not mandatory to generate a schema).

**Comment by StevenMapes** [comment]
I'd also recommend moving away from ruamel-yaml ASAP as it requires ruamel-yaml-clib which does not support Python 3.11 and this stops this project working with Python 3.11. The project does work in Python 3.10 as I've been running it on that for a while :)

**Comment by onegreyonewhite** [comment]
> I'd also recommend moving away from ruamel-yaml ASAP as it requires ruamel-yaml-clib which does not support Python 3.11 and this stops this project working with Python 3.11. The project does work in Python 3.10 as I've been running it on that for a while including Django 3.2, 4.0 and 4.1 :)

 Very strange because I just generated a schema in Python 3.11 without problems.
 And ruamel-yaml-clib has wheels for Python 3.11.

**Comment by StevenMapes** [comment]
> > I'd also recommend moving away from ruamel-yaml ASAP as it requires ruamel-yaml-clib which does not support Python 3.11 and this stops this project working with Python 3.11. The project does work in Python 3.10 as I've been running it on that for a while including Django 3.2, 4.0 and 4.1 :)
> 
> Very strange because I just generated a schema in Python 3.11 without problems. And ruamel-yaml-clib has wheels for Python 3.11.

Interesting. I'll have to try again if it works then great

**Comment by JoelLefkowitz** [comment]
@sevdog thanks for raising this. I agree that PyYAML is the way to go. This repo's release 1.21.5 introduced support for python 3.10 and in release 1.21.6 I would like to add support for python 3.11.

It's worth pointing out that there is an open PR #806 that advances the ruamel.yaml interfaces to use their version 0.17 methods, however in the long term it is in our interest to be consistent with the rest of the Django tooling and make the switch to PyYAML. I'll have a look at updating the codecs and fields.

**Comment by tfranzel** [comment]
I don't remember the reason why we moved away from `ruamel.yaml` to `pyyaml`, but there was definitely one. `pyaml` works excellently with a couple of light touches.

FYI these were the representer changes we had to make to have a consistent and clean schema:
https://github.com/tfranzel/drf-spectacular/blob/4d50c46c7b6a228c36cbbfe6add0b371f717ce8f/drf_spectacular/renderers.py#L15
