### ISSUE TITLE
Add 'tags' in openapi.swagger

### ISSUE THREAD

**Issue by sxynwh** [axnsan12/drf-yasg#85]
Hi,
I want use SwaggerMarkup(https://github.com/Swagger2Markup/swagger2markup-maven-project-template) to convert a Swagger specification into PDF, but it failed when I try to build with the json file which generated via drf-yasg. The failure reason is that the json file has no field 'tags', the specific field list all endpoint names and it is different from a subfield of get/put/patch/delete.  It is shown as below.
![1](https://user-images.githubusercontent.com/8588845/37328647-e8afb0b2-26d5-11e8-8406-324ae496d3c2.png)

I think adding field ‘tags’ in openapi.swagger to list all endpoint names is clearer to users and the generated Swagger specification after modified will be satisfied with some SwaggerTools.  Some modified codes are shown as below.
1. Define a new Class Tags in openapi.py
2. Add a new parameter 'tags' in openapi.Schema
![2](https://user-images.githubusercontent.com/8588845/37328916-bc40fa76-26d6-11e8-8fc2-5b38db708b0d.png)
3. Define a new function to get tags in generators.OpenAPISchemaGenerator
4. Add tags when calling openapi.Swagger in generators.OpenAPISchemaGenerator.get_schema

**Comment by axnsan12** [comment]
Hello!

First, the library you are using is broken. The OpenAPI spec says explicitly that the ``tags`` key is not required, and if present, is not required to contain all tags that appear in the API. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object

Second, you can override [get_schema](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_schema) in a [custom generator](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#openapischemagenerator), and add the required functionality. You would probably have to build a set of tags by iterating through each operation in each path of the ``paths`` key.

**Comment by sxynwh** [comment]
Great!
Thanks a lot.

**Comment by sxynwh** [comment]
We can download the swagger file via browse, but now I want to get this file by script (not call restapi), would you please give me some advice?

**Comment by axnsan12** [comment]
Read the documentstion.

**Comment by pptime** [comment]
Ok, I see

**Comment by alissonmuller** [comment]
> Second, you can override [get_schema](https://drf-yasg.readthedocs.io/en/stable/drf_yasg.html#drf_yasg.generators.OpenAPISchemaGenerator.get_schema) in a [custom generator](https://drf-yasg.readthedocs.io/en/stable/custom_spec.html#openapischemagenerator), and add the required functionality. You would probably have to build a set of tags by iterating through each operation in each path of the `paths` key.
> 
> Something along the lines of:
> 
> ```python
> def get_schema(*args, **kwargs):
>     swagger = super().get_schema(*args, **kwargs)
>     tags = {tag for path in swagger.paths for op in path.operations for tag in op.tags}
>     swagger.tags = [{'name': tag} for tag in tags]
>     return swagger
> ```
> 
> should do the job.

Just for reference, the following worked for me:
```python
from drf_yasg.generators import OpenAPISchemaGenerator

class CustomOpenAPISchemaGenerator(OpenAPISchemaGenerator):
    def get_schema(self, *args, **kwargs):
        schema = super().get_schema(*args, **kwargs)
        tags = [tag for path_key, path in schema.paths.items() for op in path.operations for tag in op[1].tags]
        schema.tags = [{'name': tag} for tag in tags]
        return schema

schema_view = get_schema_view(
    ... other arguments ...
    generator_class=CustomOpenAPISchemaGenerator,
)
```

**Comment by pptime** [comment]
I did have implemented a similar version, but I hope it could be integrated directly into the library so that the feature can be covered by the unit test of the library. Otherwise, we will have to test it by ourselves whether there is any side effect. But apparently, this implementation is very intuitive and not very error prone.

**Comment by pptime** [comment]
However, the current implementation does not associate the tag with any descriptions or externalDocs. It might be better to provide an interface

**Comment by axnsan12** [comment]
You can add 'description' next to name to have that.

**Comment by pptime** [comment]
Yes, I did so. I am wondering if it could be more generic and provide an
easy to use interface. Like in Django, all the models could be discovered
automatically. But, I guess it could be time consuming to do that every
time at runtime.

Le mar. 2 avr. 2019 à 17:50, Cristi Vîjdea <notifications@github.com> a
écrit :
