### ISSUE TITLE
1.21.6 - Missing redoc.min.map

### ISSUE THREAD

**Issue by petrprikryl** [axnsan12/drf-yasg#855]
# Bug Report

## Description

```
whitenoise.storage.MissingFileError: The file 'drf-yasg/redoc-old/redoc.min.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage
```

The `redoc.min.map` newly referenced [here](https://github.com/axnsan12/drf-yasg/blob/1.21.6/src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js#L8) does not exist. 

There is `//# sourceMappingURL=redoc.min.js.map` in [1.21.5](https://github.com/axnsan12/drf-yasg/blob/1.21.5/src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js#L8) which works fine.

## Is this a regression?

https://github.com/axnsan12/drf-yasg/issues/761

**Comment by sergei-iurchenko** [comment]
Please fix it. I can not collect static with STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

**Comment by wbwlkr** [comment]
Just updated to **1.21.6** (with whitenoise 6.4.0 to 6.5.0) and got the same error message.
I can not execute collectstatic with `STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"`.

Then I put [1.21.5](https://github.com/axnsan12/drf-yasg/blob/1.21.5/src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js#L8) back and it works fine for me too.
Is this a regression ?

**Comment by sergei-iurchenko** [comment]
> Just updated to **1.21.6** (with whitenoise 6.4.0 to 6.5.0) and got the same error message.
> 
> I can not execute collectstatic with `STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"`.
> 
> 
> 
> Then I put [1.21.5](https://github.com/axnsan12/drf-yasg/blob/1.21.5/src/drf_yasg/static/drf-yasg/redoc-old/redoc.min.js#L8) back and it works fine for me too.
> 
> Is this a regression ?

1.21.5 works

**Comment by jaderinoo** [comment]
Same here, had to swap back to 1.21.5.

**Comment by lordoffreaks** [comment]
same here

**Comment by wbwlkr** [comment]
Will it be soon released in a version `1.21.6` ?

**Comment by JoelLefkowitz** [comment]
Yes

**Comment by JoelLefkowitz** [comment]
I'll cut a new release this week

**Comment by JoelLefkowitz** [comment]
Let's do it now
