### ISSUE TITLE
get_schema_fields breaks when using django-filters after last update

### ISSUE THREAD

**Issue by Qadosch** [axnsan12/drf-yasg#856]
# Bug Report

## Description

Used by class `CoreAPICompatInspector`
`get_schema_fields` is implemented on django-filters filter backend. By removing depentancy on `coreapi` in last 1.21.6 the function stopped working.

## Is this a regression?

yes it worked in 1.21.5

**Comment by onegreyonewhite** [comment]
@Qadosch you should install with extra `coreapi` (like `drf-yasg[coreapi]`. Or wait next release with #857 (not required coreapi)

**Comment by Qadosch** [comment]
Duplicate of #857
