### ISSUE TITLE
Schema properties documented as list, but dict can be more suitable

### ISSUE THREAD

**Issue by Nicd** [axnsan12/drf-yasg#87]
[Here](https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/openapi.py#L428), Schema's `properties` is documented as being a list of child Schemas and SchemaRefs. But using something like `properties=[Schema('foo', ...)]` results in documentation showing `{'0': ...}`, as in the property key is an incrementing integer. If you give it a dictionary that goes against the documentation, it works better: `properties={'foo': Schema(...)}` results in `{'foo': ...}` in the documentation.

I'm not too knowledgeable on OpenAPI in general but should the documentation show that `dict` is also acceptable? Or does it work by accident?

**Comment by axnsan12** [comment]
Yes, you are right, the documentation is wrong. ``properties`` must be a ``dict``, it's actually an accident if it works as a list like you say.

**Comment by axnsan12** [comment]
The value of ``properties`` in a ``Schema`` object is required to be a JSON object (a dict): https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.4.4.1

So you are right, the documentation is wrong here; ``properties`` should be a ``dict`` (preferably even an ``OrderedDict``) of ``str`` to ``Schema``, it only works as a list by accident (and it would probably fail validation).
