### ISSUE TITLE
Incorrect Information and Hard to Understand Information

### ISSUE THREAD

**Issue by codingkidprodigy** [axnsan12/drf-yasg#93]
Hello everyone,
I am using Django 2.0.3 and DRF 3.7.7 and am trying to make a REST API for a different application. So, for that reason, I wanted to use a documentation library that does it automatically for me. Before Django 2.0 I couldn't find one that was good, but then I found this one which is the only one that works with Django 2.0.x. However, when I set it up, the documentation with redoc is a little confusing. In the sense that I currently have an Authentication app which allows Users to login or register, and when they are logged in they can view their details and even update it. So when I was looking at the view user and update user part of the documentation the information is a little confusing. I also am using JWT's to make sure the user is valid and I send the token in through a Header called Token and not through the input body. When I go to check the user login and user registration part it shows absolutely nothing except for Responses 201. I don't know why this is happening and this is the one documentation library that I like. If you need any certain code please do ask and I will be able to upload it.

Thanks

**Comment by axnsan12** [comment]
My guess would be that you are not using generic views (``GenericAPIView``, ``GenericViewSet``). Nothing you can do here except manually specifying what serializers are used for each method of your API and what parameters the methods take. See this package's documentation for how to do that.

**Comment by codingkidprodigy** [comment]
So presumably if I use generic views, would it automatically pick up the changes? @axnsan12?

**Comment by codingkidprodigy** [comment]
Nvm I will not be able to use Generic Views for my use case. Guess, I'll have to add in the endpoints manually. Is there no alternative?

**Comment by axnsan12** [comment]
No. In non-generic views you don't declare your serializer classes anywhere for drf-yasg to be able to pick them up automagically.

**Comment by codingkidprodigy** [comment]
Can you elaborate? and maybe this can be a feature sometime soon?

**Comment by axnsan12** [comment]
I'm not sure you understand. It can't be a feature. It's not possible. The information is not there. 

The only way to possibly get that information without executing the view function would be to parse the function's AST at runtime.

With generic views, you set ``serializer_class`` on the views, which use it in specific ways that can be inferred by drf-yasg. With regular views you don't do that, so you have to manually specify them with ``swagger_auto_schema``.
