### ISSUE TITLE
How to add custom header in javascript ???

### ISSUE THREAD

**Issue by jyseeeee** [axnsan12/drf-yasg#98]
(rest_framework_swagger/index.html) using :
    window.swaggerUi.api.clientAuthorizations.add("appVersion",
    new SwaggerClient.ApiKeyAuthorization("appVersion", appVersion, "header"));

    window.swaggerUi.api.clientAuthorizations.add("userType",
    new SwaggerClient.ApiKeyAuthorization("appType", appType, "header"))

    window.swaggerUi.api.clientAuthorizations.add("osType",
    new SwaggerClient.ApiKeyAuthorization("osType", osType, "header"))

(drf-yasg/swagger-ui.html )  not working...

**Comment by axnsan12** [comment]
Well, first, the swagger singleton in that file is named ``ui``, not ``swaggerUi``.

And second, this is a JavaScript issue, check the documentation of ``swagger-ui``.

**Comment by jyseeeee** [comment]
Thank you. I'll study a little more.

**Comment by axnsan12** [comment]
https://github.com/axnsan12/drf-yasg/blob/6dd8ded05d1eae2352c2a71b317289041e36da5b/src/drf_yasg/static/drf-yasg/swagger-ui-init.js#L41

**Comment by latusaki** [comment]
@axnsan12 , I need to pass additional headers with every request, but the value needs to be set from UI as its not static..  I have found this (http://django-rest-swagger.readthedocs.io/en/latest/customization/)  but not sure how to apply on drf-yasg. Any pointers are appreciated.

**Comment by axnsan12** [comment]
Not applicable, pending #178...

**Comment by axnsan12** [comment]
Also, do realize that this library has no ties to django-rest-swagger apart from slight inspiration, so documentation is not generally transferrable.
