### ISSUE TITLE
Missing query parameter titile when using query_serializer

### ISSUE THREAD

**Issue by devxplorer** [axnsan12/drf-yasg#99]
Hi. When I use the query_serializer parameter in the swagger_auto_scheme decorator, there is no shown title for query parameters in redoc (i assume they should be received from serializer fields labels).

To illustrate the problem i created [simple project](https://github.com/devxplorer/yasg_api) and [screenshot from this app](https://i.imgur.com/TTV3Iv1.png).

Is this expected behavior or bug? Or am I doing something wrong?

**Comment by axnsan12** [comment]
[Parameter objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object) do not have a ``title`` attribute, only ``description``.

**Comment by devxplorer** [comment]
Got it, thanks for the answer.
